### ISSUE TITLE
Supporting Angular 2

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#1]

**Comment by chriscoyier** [comment]
Angular 2 is written in TypeScript as I understand it, so hopefully it'll work with TypeScript as well. 

This is our TypeScript implementation: https://github.com/tsabat/typescript_lambda

... which ideally would support React/JSX/TSX as well.

**Comment by chriscoyier** [comment]
From David Aden:

```
I played with CodePen for quite awhile yesterday and would like to use it for examples but I couldn't get it to handle Angular 2 set up the way we'd like to use it which is to create components and use TypeScript. I tried various things: 

1) Using TypeScript. When I turned TS preprocessor on it seemed to choke on decorators/annotations which are in, I believe TS 1.5. 

2) When I added JS dependencies for System.js and TypeScript, my code in the HTML to run System.config couldn't find System, apparently because the dependencies are included after anything in the HTML.

3) When I turned TS preprocessor off and just included System.js and a TS in-browser transpiler with script tags I couldn't get it to run the Angular 2 components. I put my app.ts into a file and included that but still couldn't get it to work. 

Not sure those descriptions make sense, but it would be really nice to have a solution on Codepen for running Angular2 apps using Typescript. 

My pen is at: http://codepen.io/daden/pen/JYvMPG

It's got remnants of various things I tried.
```

**Comment by chriscoyier** [comment]
Some progress: https://github.com/tsabat/typescript_lambda/pull/1

**Comment by tsabat** [comment]
[this](https://github.com/tsabat/typescript_lambda/pull/1) is merged, but I don't understand TypeScript and Angular well enough to know if it worked.  I think just just allowed React to work, not the stuff above.

**Comment by chriscoyier** [comment]
Tim's demo Pen == http://codepen.io/tsabat/pen/a3a5046a2360498b5e00d1600644d880/

**Comment by chriscoyier** [comment]
A [new request from Ionut Costica](http://blog.codepen.io/2015/12/07/typescript-updated-and-faster/#comment-2431605436):

> Is it possible to set the emitDecoratorMetadata flag for TypeScript compilation? It's really useful for Angular2 (if it's not set, Angular2 won't glue together its Dependency Injection right, unless you put in the glue yourself).

But the comment was deleted? Not sure what's up there.

**Comment by mariemosley** [comment]
@chriscoyier that comment was deleted by it author, but they emailed us with a similar request and more detail [4138].

**Comment by chriscoyier** [comment]
From Ionut Costica:

> Here are a few references about typescript & dependency injection (in angular2 and other frameworks):

> http://stackoverflow.com/questions/30311514/injectables-in-angular2

> http://blog.durandal.io/2015/05/06/getting-started-with-aurelia-and-typescript/  -> regards Aurelia+TypeScript, but underlines the same problem in other frameworks (also about dependency injection):
emitDecoratorMetadata is an experimental compiler option that allows the @autoinject decorator to do its job
 
> http://blog.wolksoftware.com/decorators-metadata-reflection-in-typescript-from-novice-to-expert-part-4

>    -> for a much more in-depth look about how the generated metadata (when the emitDecoratorMetadata flag is set to true) is/can be used by frameworks/libraries

> Also, very good explanation of emitDecoratorMetadata as applied to Angular2:
http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html

> The problem is that without it you have to prefix every constructor parameter that must be dependency injected with @Inject() in addition to prefixing the service classes with @Injectable() (though the last link suggests that only @Injectable() should be necessary, it appears something changed between September and now, because in my test app on codepen, the dependency injection only worked when I explicitly marked both the Injectable and the injection point for it).

> Sorry for the long list of links, but the TL;DR version is that emitDecoratorMetadata allows typescript to emit additional information in the transpiled javascript that is very useful for the transparent working of dependency injection systems everywhere (at least Angular2 and Aurelia, with proof linked above).

**Comment by chriscoyier** [comment]
From Radoslav Kirov:

> Here is a working plunker with typescript - http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview

> It uses System.js feature to load typescript compiler on the fly when .ts file is encountered and transpile in the user's browser. I don't see why this setup can't be replicated by codepen given that it does most of the work in the browser. One downside of this approach is that on-the-fly transpilation seems like is not doing any typechecking against Angular2's apis, since that type information is never fed in (no reference to angular's .d.ts files). Still this is good enough for reproducing bugs and has been very useful for issues on github.

> Plunker also supports transpiling on the server-side, given a tsconfig.json and .ts files, but I haven't seen that setup working with angular2. The issue is that, last I checked, that setup needs proper type information for angular2 and there is no way to tell plunker use out npm distrubuted .d.ts files (we don't distribute a single library .d.ts any longer).

**Comment by chriscoyier** [comment]
Our working version of that Plunkr: http://codepen.io/chriscoyier/pen/75189ffd9ffdc9812ec376b662b523f9

(Way less convenient)

**Comment by chriscoyier** [comment]
I think the long term answer here is our Project Editor plan coming later this year, since that Pen above works, it's just inconvenient because of UI.
