### ISSUE TITLE
Command-/ in Jade without Selection Inserts Wrong Comment Syntax

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#10]
Originally reported by @Murilirum here: https://github.com/CodePen/redesign/issues/302

Problem:

![img](http://d.pr/i/13sol/YikfBbAx+)

If you have a SELECTION, it's fine. If you just press the keys without a selection, it's wrong. It's only loosely "wrong" as Jade supports normal HTML comments fine, but might as well do the Jade-style ones that work with the syntax highlighting better.

This is on us, as WE do the comment keyboard shortcut stuff, [not CodeMirror](https://codemirror.net/mode/jade/index.html) as best I can tell.

**Comment by jakealbaugh** [comment]
we *were* doing this. now we *kind of* do it, but through codemirror keybindings, methods, and some custom codemirror magic.
