### ISSUE TITLE
Show browser support

### ISSUE THREAD

**Issue by ClarusDignus** [CodePen/CodePen-Bug-Reporting-Only#100]
It would be immensely more useful if pens displayed browser support. I.e. What browsers the pen will work on.

Right now, as it is, it's a bit of a Russian roulette. I find myself skipping Code Pen solutions whenever I'm linked to them and instead opt for solutions found on sites that clearly outline browser support. The risk of investing the unnecessary foreplay time with CodePen's pens isn't one I'm willing to take.

**Comment by chriscoyier** [comment]
Hey @ClarusDignus -

You aren't alone. A lot of people, including CodePen employees, have wanted this over the years.

The users of CodePen are, of course, free to explain anything they like in a Pen. In the description, they have an unlimited number of characters to detail this kind of thing out.

Then there is the matter of CodePen itself trying to figure out and explain browser support. Here's the tricky question: What does "clearly outline browser support" mean? What constitutes "support" for any given (of the 6 million plus) Pens? It's close to impossible for us to tell. 

For example, perhaps a Pen is demonstrating some kind of grid system in CSS. Perhaps the author used flexbox. It's possible that CodePen could read the CSS and determine flexbox is being used in this Pen, reference a database of browser support for flexbox, and somehow display that. But that Pen is also using likely dozen if not hundreds of other features that would require support level checking. And sub features as well. Perhaps the Pen uses flex-wrap as well. Related to flexbox, but has different levels of support. Then what if the author took the time to create some kind of fallback. Perhaps floats. The Pen now has a lot better browser support, assuming they did things correctly. But how could we know? 

It's tempting to ASK CodePen users to explain browser support of their Pens more clearly. But who's to say they get it right? Does that make CodePen feel more like a job? Don't these things change over time?

I'm sure you can see this is a huge can of worms that likely can't be solved in such a way that makes life better for anybody.

My favorite way to check browser support of things: http://caniuse.com/
