### ISSUE TITLE
The Babel Javascript Preprocessor errors whenever I type anything

### ISSUE THREAD

**Issue by intrepion** [CodePen/CodePen-Bug-Reporting-Only#101]
No matter what I try, I keep getting this error message:

Invalid syntax: babel.

It seems to fix things temporarily if I remove the preprocessor and add it back again, until it saves.

**Comment by intrepion** [comment]
Okay, so my current workaround is to have Editor View in one tab and Debug Mode in another tab.  Whenever I make a change in Editor View, I can refresh the Debug Mode tab and see my changes.

**Comment by chrisdziewa** [comment]
@intrepion I'm having the same problems

**Comment by yukulele** [comment]
Me too, idem for stylus:
```Invalid syntax: Stylus.```

**Comment by sixsided** [comment]
Same. I thought it was due to using an unusual JSX pragma (`/** @jsx preact.h */`) -- I was getting "Invalid syntax: babel" about half of the time. A workaround, at least for my case: turn off autorun and click the "Run" button when you want code to execute.

**Comment by chrisdziewa** [comment]
Even with running it myself I have to run it more than once to get it to
work. Also my full-page view still shows up blank.

**Comment by tsabat** [comment]
hey, so sorry about this issue.  We've fixed it.  You all were right about 50% of the time guess.  We moved new code onto the server which got hung in the load balancer.  So, while some calls may have gone through, others did not, causing this problem.

We're all up-to-date now and the issues should be gone.
