### ISSUE TITLE
Live view not updating with changes to external pen as CSS resource

### ISSUE THREAD

**Issue by Airster** [CodePen/CodePen-Bug-Reporting-Only#102]
When editing a pen that uses another pen as an external CSS resource, changes to the CSS are not showing in LIVE view. Changes to the actual pen itself display fine, but even a hard refresh will not show the changes due to editing the linked CSS.

The only way I can seem to see these changes reflected is to close the live view and both pens, then reopen the main pen and switch to live view.

This has caused me an awful lot of head scratching as to why changes to the CSS weren't doing what I expected or hoped - I'm a bit of a newbie :(

**Comment by mariemosley** [comment]
I'm sorry about that, I can see how it's frustrating. It's not quite a bug, but more of a limitation in what Live View can do. We have an upcoming feature that will make it much easier to work with Pens with multiple files, but for now here's how live view works when a Pen has another Pen as an external CSS resource: 

Live View opens Pen A, the Pen you're currently editing, in a new tab/window and loads everything from Pen A's code panels and settings, including CSS from the external resource, Pen B. 

Then, it watches the code panels in Pen A for changes. Unfortunately it can't reach into Pen B to watch for changes there, too. So, the solution is to close and reopen Live View on Pen A after saving changes on Pen B.

I'm going to add this caveat to the documentation for Live View. Thanks for taking the time to let us know about your experience :)

**Comment by Airster** [comment]
Thanks Marie. That's fine. I just thought you'd want to know about this slightly weird behaviour in what is probably a fairly unusual use-case. Codepen really rocks though!
