### ISSUE TITLE
Can't reach bottom of pane, but only sometimes

### ISSUE THREAD

**Issue by sdras** [CodePen/CodePen-Bug-Reporting-Only#105]
There are times when I'm working at the end of the document in the CSS, or JS view, and it locks before I can get to the end of it. I can still use my arrow keys to get to the text, but I can't see what I'm typing.

Unfortunately, the pen I have that shows this is sensitive for my company, but I'm happy to show one of you privately. I also have a screenshot, attached here.

<img width="512" alt="screen shot 2016-02-18 at 6 59 36 am" src="https://cloud.githubusercontent.com/assets/2281088/13147327/a185569e-d60d-11e5-99ea-f8bf6d5dc4ea.png">

**Comment by mariemosley** [comment]
Hey @sdras :) Thanks for letting us know! I'm seeing this too.

**Comment by mariemosley** [comment]
To reproduce:
It's Chrome only, and only when the editor is on the top. I'm not able to reproduce in Firefox or Safari. 

Video of the problem: http://d.pr/v/11TeC/gU0PZm0k

It's "fixed" if you change editor layout from top to a side layout, then back to top (which may be why it seems intermittent). Video of the problem going away after layout switch: http://d.pr/v/1dy7q/1m4WOjkC

**Comment by chriscoyier** [comment]
There is a new version of CodeMirror we should upgrade to just in case that's an easy fix: https://discuss.codemirror.net/t/release-5-12-0/659 (it's probably not though)

**Comment by mariemosley** [comment]
Fixed! Thanks again for reporting this :)

**Comment by sdras** [comment]
thanks for taking care of it!
