### ISSUE TITLE
Missing font-color on form elements

### ISSUE THREAD

**Issue by Ryuno-Ki** [CodePen/CodePen-Bug-Reporting-Only#108]
On my dark themed Window Manager firefox renders form elements unreadable:

![codepen](https://cloud.githubusercontent.com/assets/3097194/13190338/e7f8cf16-d75c-11e5-80c8-3f14bff84581.png)

Please add:
```css
textarea, input {
    color: #000;
}
```

For reference: I'm using Mate v1.10.2 with NOX Equinox Evolution Dawn window decoration and Firefox 44.0 on Sabayon Linux.

**Comment by chriscoyier** [comment]
I'm a believer in setting color when you set background-color, and we weren't doing that here, so I'll make sure to update that, only scoped to the problem at hand at the moment.
