### ISSUE TITLE
TypeScript syntax highlighting in blog posts is malfunctioning

### ISSUE THREAD

**Issue by Imagine-Programming** [CodePen/CodePen-Bug-Reporting-Only#109]
When I use ```typescript markdown in a blog post, it results in a JavaScript titled block with TypeScript code in there. Shouldn't the code header say TypeScript for clarity? Also, it seems the syntax highlighting in that block is not similar to that of a Pen with TypeScript enabled.

![codepen-blog-bug](https://cloud.githubusercontent.com/assets/489573/13199940/ab4afd62-d835-11e5-8282-4511252f9b40.png)

When compared to the CodePen Pen JS editor:

![codepen-blog-bug-2](https://cloud.githubusercontent.com/assets/489573/13199943/d74b7a54-d835-11e5-9f0f-e6e596ed91b6.png)

**Comment by chriscoyier** [comment]
Good catch. I think I got it fixed. Will go out today.

<img width="1148" alt="screen shot 2016-02-22 at 8 30 33 am" src="https://cloud.githubusercontent.com/assets/69156/13219554/b852ae4c-d93e-11e5-847c-e23a52b17212.png">

**Comment by Imagine-Programming** [comment]
Awesome, thanks!
