### ISSUE TITLE
Asset Manager Omits The CodePen Footer

### ISSUE THREAD

**Issue by bmuenzenmeyer** [CodePen/CodePen-Bug-Reporting-Only#11]
I was looking for the support page from the asset manager while troubleshooting some files, only to realize the footer is missing on this page. I cannot think of a reason for it to not be there, unlike pen-like pages. 

Just my two-cents. Thanks for the AWESOME PRODUCT. :+1:

**Comment by chriscoyier** [comment]
I think it makes sense to put the footer there, adding!
