### ISSUE TITLE
Compass (totally alone) causes error

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#110]
Totally alone:

<img width="720" alt="screen shot 2016-02-22 at 11 17 59 am" src="https://cloud.githubusercontent.com/assets/69156/13224348/1c0429c2-d956-11e5-92c1-10a50568879e.png">

With any valid Sass:

<img width="437" alt="screen shot 2016-02-22 at 11 18 26 am" src="https://cloud.githubusercontent.com/assets/69156/13224355/25008fac-d956-11e5-878e-be1e0de5cffd.png">

**Comment by mariemosley** [comment]
This seems to affect all Sass add-ons, not just Compass. http://d.pr/i/ToMy/3mZrNbpb

**Comment by chriscoyier** [comment]
This is just how boomerang works. Boomerang doesn't like when nothing is returned. 

We just need Boomerang deal with empty requests. 

We're gonna leave this open for 5 more days and then stop caring. lolz.

**Comment by quezo** [comment]
We're serving the correct HTML with the CSS style result of:

```<style class="cp-pen-styles">@import "compass"
</style>```

The 404 problem is that CSS attempts to load 'compass' from the boomerang URL. This is just how it works and not an error on our end.
