### ISSUE TITLE
console.log implementations

### ISSUE THREAD

**Issue by Carniatto** [CodePen/CodePen-Bug-Reporting-Only#113]
This Pen sums it up basically: http://codepen.io/Carniatto/pen/bEXwOX (CHECK THE CONSOLE)

But this consists in using the printf like form of console.log on codepen. This will not work
 it should follow this:

### console.log(object[, object, ...])
 Writes a message to the console. You may pass as many arguments as you'd like, and they will be joined together in a space-delimited line. You can use printf-like string substitution patterns as well which are:

- `String: %s` - console.log('The %s is a %s', animal, cat);
- `Integer: %d, %i` - console.log('Number %d plus %i', 1, 2); *integer not yet supported
- `Floating point number: %f` - console.log('Floating points: %f', 1.5); *numeric formatting not yet supported-
- `Hyperlink: %o` - console.log('Live laugh code at $o', 'http://anti-code.com' );
- `Style formatting: %c` - console.log('%c This is white text on a black background', 'color:#fff;background:#000;');

Regards

**Comment by mariemosley** [comment]
These are great ideas, I'm going to move this onto the wishlist for our console. Thanks!
