### ISSUE TITLE
Keep Find Open

### ISSUE THREAD

**Issue by jakealbaugh** [CodePen/CodePen-Bug-Reporting-Only#114]
This was brought up recently by [Joe Harry](codepen.io/woodwork) in the dev slack, but is something thats driven me crazy for the longest time.

`cmnd + f`, typing a search term, and hitting `return` finds correctly, but in order to find the next instance, i need to hit `cmnd + f` again instead of hitting `return` to go next or `shift + return` to go previous through results.

**Comment by rachsmithcodes** [comment]
assigning myself this cause it also drives me nuts and would be my dream to change it 🌈

**Comment by chriscoyier** [comment]
For the record: https://codemirror.net/demo/search.html

![img](http://d.pr/i/1j9PI/2k7QCsC7+)

A potential solution is to add copy to that dropdown that lists these commands

**Comment by rachsmithcodes** [comment]
oh yeah that would be helpful

**Comment by rachsmithcodes** [comment]
Added these key commands to the key commands info
