### ISSUE TITLE
Template count in dropdown doesn't match templates under profile

### ISSUE THREAD

**Issue by Mestika** [CodePen/CodePen-Bug-Reporting-Only#115]
During a bug-tracking of a different sort ([already reported here, about Pen's not being able to save as templates](https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/61)) I discovered that my list of templates does not match when I can find in the dropdown menu in the menu top right and the templates listed under **my profile > Pens > Templates**

![screencapture-codepen-io-mestika-pens-templates-1456257751119 copy](https://cloud.githubusercontent.com/assets/48558/13265021/18935c56-da71-11e5-935f-1dbbe19fa138.png)

**Comment by chriscoyier** [comment]
I think it's this: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/116
