### ISSUE TITLE
Creating a generator using Babel causes an exception

### ISSUE THREAD

**Issue by danevans** [CodePen/CodePen-Bug-Reporting-Only#118]
I have an example here http://codepen.io/Danston/pen/reBaBX

The error is `ReferenceError: Can't find variable: regeneratorRuntime`

This example is taken from https://leanpub.com/understandinges6/read#leanpub-auto-generators and works when inputted into Babel's web REPL http://babeljs.io/repl/

**Comment by chriscoyier** [comment]
It compiles OK, so I think you just need to add an extra lib or dependency or whatever that defines whatever `regeneratorRuntime` is, as it looks like a client-side thing.

**Comment by danevans** [comment]
I think the version of Babel being included when selecting it from Pen Settings > JavaScript > JavaScript Preprocessor > Babel is wrong. It appears that [babel-standalone](https://github.com/Daniel15/babel-standalone) is what's needed for a browser environment.

> there are some valid use cases for babel-standalone:

> Sites like JSFiddle, JS Bin, the REPL on the Babel site, etc. These sites compile user-provided JavaScript in real-time.

I think this is the version that one would expect to be included when selecting this option because the non-standalone version will throw exceptions in environments like codepen.

**Comment by chriscoyier** [comment]
We do run Babel through Node though. That looks like it's if you wanted to compile Babel in the browser only. We actually take your Babel, send it back to our Node server for processing, and send it back.

**Comment by chriscoyier** [comment]
Check out this Pen:
http://codepen.io/nelix/pen/WQWWvg

Looks like it loads whatever makes `regeneratorRuntime` work.
