### ISSUE TITLE
Log Skipped error message appears to have a hyperlink?

### ISSUE THREAD

**Issue by aarjithn** [CodePen/CodePen-Bug-Reporting-Only#119]
**You** is having a different colour in the text 
`Log Skipped: Sorry, this log was too large for our console. **You** might need to use the browser console instead.`

Is there any use for this? I assumed it was a hyperlink and thought it doesn't seem to make sense.

<img width="1036" alt="screen shot 2016-02-25 at 00 20 23" src="https://cloud.githubusercontent.com/assets/10304259/13305800/f530431a-db55-11e5-9a84-5d1303f6d36f.png">

**Comment by chriscoyier** [comment]
Looks like it's getting syntax highlighted, but shouldn't be.

I think Sass debug statements are getting that too and probably shouldn't be.

**Comment by mariemosley** [comment]
We're moving this to our Known Issues trello board: https://trello.com/c/SJV9AHBI/14-console-log-skipped-error-message-has-a-syntax-highlighting-bug 

Thank you for taking the time to report it!
