### ISSUE TITLE
Organize Showcase Page Opens in Wrong Order

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#12]
I think the root of [this](https://github.com/CodePen/redesign/issues/247) and our (internal) support 3806 is that when you open http://codepen.io/you/organize/ it OPENS in the wrong order.

@pixelass has the issue:

![issuecp](https://cloud.githubusercontent.com/assets/1148334/10711158/bda41f00-7a27-11e5-83c9-6203f9cacdf9.gif)

I can replicate it too, which is where I discovered the problem for me is mostly when I go back to the Organize page, it's the Organize page that opens wrong, not the profile.

![profile-problems](https://cloud.githubusercontent.com/assets/69156/11344082/496b659e-91dd-11e5-91ef-5240a395056a.jpg)

Caching?

**Comment by jakealbaugh** [comment]
fixed
