### ISSUE TITLE
Grammar error on stats page

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#120]
On http://codepen.io/stats/:

"## Pens Hearted have been given by our loving members"

Apologies if this was intentional, sounds super weird to me.

**Comment by mariemosley** [comment]
Good catch, thanks! Correction going out shortly 😀

**Comment by alexzaworski** [comment]
Great, thanks! I also noticed that the quote on that page is attributed using a hyphen (`-`) rather than an em dash (`—`) which is minor but still incorrect.

**Comment by mariemosley** [comment]
That's a bit more widespread through the site than just this page. I'll add this one to our internal todos, thanks :)
