### ISSUE TITLE
Vertical white lines display on hover in podcast page

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#121]
When hovering over an episode on the podcast page, a vertical white line (or two!) appears at some screen sizes. I was only able to reproduce this on a retina screen.

![uwivcov9ww](https://cloud.githubusercontent.com/assets/8040471/13306372/dd414508-db17-11e5-875a-afaaf26b1518.gif)

edit: It isn't *just* on hover, it's just easiest to see on hover since the background is so light otherwise.

**Comment by chriscoyier** [comment]
Think I got that fixed. It was a little `background-clip` in there we didn't need anymore. Still a browser bug I'd say, but nice to have fixed.
