### ISSUE TITLE
Jittery fixed background image on Chrome

### ISSUE THREAD

**Issue by brettdewoody** [CodePen/CodePen-Bug-Reporting-Only#123]
I recently built a pen where I used `background-attachment: fixed`. In Chrome the background image moved around while scrolling. This was not an issue in Firefox or Safari. 

Viewing the pen in Debug mode resolved the issue, but all other views displayed the jittery background image. 

The pen in question - http://codepen.io/brettdewoody/pen/BKBRWX/.

![jitterybackgroundimage](https://cloud.githubusercontent.com/assets/409070/13331031/7d0fc4a2-dbf3-11e5-9cdd-8072b8c28fc1.gif)

**Comment by chriscoyier** [comment]
Not sure exactly what's going on here. 

Here's a video of me in stable Chrome, and it seems OK: http://d.pr/v/1jnmU/1TYJdUqw
