### ISSUE TITLE
Can't log in using github account

### ISSUE THREAD

**Issue by OnkelTem** [CodePen/CodePen-Bug-Reporting-Only#124]
1) I press Login in the upper right corner
2) Then I was presented with the confirming dialog from github
3) Then I was redirected back... yet not logged in

After that I tried pressing Login several times, restarted browser - nothing helps: I'm not logged in.

**Comment by mariemosley** [comment]
I'm sorry about that! That's an account-specific issue we can help you with privately. Please email us at support@codepen.io. Please include your CodePen username in your email.
