### ISSUE TITLE
Able to save and close Pen with more than 5 tags; tags persist until page refresh

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#125]
If you add too many tags to a Pen, you're still able to save/close its settings. If you re-open the settings dialog, the extra tags still display but will vanish on page refresh.

Also, the tags are populated from the input as you type but clicking the `x` next to them does nothing until you've saved your settings which is a bit weird I think.

**Comment by chriscoyier** [comment]
@quezo and I looked at this. We're close to a better solutions.

@quezo - the branch is `tags_bug`

**Comment by chriscoyier** [comment]
We fixed this! 

<img width="454" alt="screen shot 2016-03-21 at 3 09 16 pm" src="https://cloud.githubusercontent.com/assets/69156/13931179/8e6c6b0e-ef78-11e5-94cc-9340ca81a987.png">

**Comment by alexzaworski** [comment]
Hiya Chris,

Were the changes pushed live? I'm seeing the same behavior still (and it looks like maybe you uploaded the wrong screenshot?).

The tag delete buttons totally work now (arguably a larger 'issue' than the whole save+close thing) though if that's what you meant :+1:

**Comment by chriscoyier** [comment]
Correct screenshot:

<img width="449" alt="screen shot 2016-03-21 at 3 20 56 pm" src="https://cloud.githubusercontent.com/assets/69156/13931634/92e7490e-ef7a-11e5-90a3-d949062e5796.png">

Deleting on save is the correct behavior, and we're warning with the red.

**Comment by alexzaworski** [comment]
Hi Chris,

That makes sense, thanks! Is there a reason you allow a save and just auto delete with these versus throwing an error and *not* saving like you do in some other situations (eg malformed URL in external resource link)? 

<img width="800" alt="screen shot 2016-03-21 at 12 37 17 pm" src="https://cloud.githubusercontent.com/assets/8040471/13931703/cc4d0350-ef61-11e5-9796-441e48351599.png">

I'd assume it's just because it's easier to correct the problem computationally in this instance, wanted to bring it up regardless though.

**Comment by quezo** [comment]
Pens save only the first five tags. We decided to allow a save no matter what for this error. We didn't think it was destructive and we're okay with it.

**Comment by alexzaworski** [comment]
Gotcha, thanks for the clarification :)
