### ISSUE TITLE
Attempting to save a deleted Pen fails silently

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#126]
If you open a Pen, delete it from another tab, and then try to save the Pen nothing happens (I'd assume you'd want to either create a new Pen or throw an error here). Also, if you open that Pen's settings, you're stuck 'cause the save and close button doesn't work (it actually throws a JS error).

Weirdly, apparently if you delete all of the contents of the Pen you're then able to save 'successfully' (you'll get a "Pen Saved" message), but you don't actually save the Pen anywhere.

**Comment by chriscoyier** [comment]
I think we should save a brand new Pen in this (quite weird!) situation.

The theme being: never lose work.

**Comment by rachsmithcodes** [comment]
If you do this now your pen will save as a new pen with a new slug.

**Comment by alexzaworski** [comment]
Yay corner cases :star2: :star:
