### ISSUE TITLE
Data URI as iFrame source causes strange displays in Pen grids

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#128]
For whatever reason, when I use a data URI as an iFrame source (http://codepen.io/alexzaworski/pen/PNYdzE) the grid preview duplicates the non-iFrame content. Note the two vertical bars in the screenshot, despite there being only one in the Pen:

<img width="392" alt="screen shot 2016-02-26 at 9 43 46 am" src="https://cloud.githubusercontent.com/assets/8040471/13360315/78ceb9a0-dc6d-11e5-9466-f3c23ae39ec1.png">

Here's the same Pen just with an empty src attribute:

<img width="391" alt="screen shot 2016-02-26 at 9 37 08 am" src="https://cloud.githubusercontent.com/assets/8040471/13360224/10050802-dc6d-11e5-82be-216516794076.png">

As I understand it there are a bunch of things that are finicky/broken in grid views, not sure if this is one of them so I wanted to mention it.

**Comment by mariemosley** [comment]
We strip iframes from the grid view (docs: http://blog.codepen.io/documentation/editor/things-we-strip/). We know that can make affected Pens look strange in the grid, but iframes can be real troublemakers when people are browsing through Pens :)

**Comment by alexzaworski** [comment]
Hi Marie,

Appreciate the quick response :) I realize you guys don't display iFrame content, the confusion comes from the duplicated content that *is* displayed. Here's a reduced test case:

http://codepen.io/alexzaworski/pen/xVxGmj

**Comment by chriscoyier** [comment]
This is weird.

I think the trick is going to be not doing

```
<iframe src="#removed_by_codepen">
```

But doing like

<iframe src="/removed_by_codepen.html">

which is just white/nothing.

http://d.pr/i/1ekwZ/4g9Zs0JU

**Comment by alexzaworski** [comment]
@chriscoyier I didn't realize you guys were replacing the source with a fragment identifier, that kind of makes sense that it would then display itself right? If you actually have an element with that ID the frame will scroll to that point which is kind of funny:

<img width="392" alt="screen shot 2016-02-29 at 11 44 38 am" src="https://cloud.githubusercontent.com/assets/8040471/13406747/fe18ddac-ded9-11e5-8722-4e3142fc5879.png">

I'm not sure if there are browser compatibility issues with missing iFrame sources but stripping the src attribute completely seems to solve the issue (and the HTML validates, `src=""` does not):

![screen shot 2016-02-29 at 11 48 35 am](https://cloud.githubusercontent.com/assets/8040471/13406842/75fe35e2-deda-11e5-9ee3-034a7201fae2.png)

**Comment by quezo** [comment]
We're replacing the iframe with a full url to a blank page now to avoid this error.
