### ISSUE TITLE
CSS increase/decrease number Windows shortcuts

### ISSUE THREAD

**Issue by chickenroyal** [CodePen/CodePen-Bug-Reporting-Only#131]
Using Windows 10, the shortcuts cheat sheet shows the OS X key bindings for increasing and decreasing CSS numbers (Opt ↑ and Opt ↓). The Windows bindings should be Ctrl Alt ↑ and Ctrl Alt ↓

Not a big issue by any means, but it's something. Thanks!

**Comment by chriscoyier** [comment]
This is the keymap in Emmet

```
	"Ctrl-Up": "emmet.increment_number_by_1",
	"Ctrl-Down": "emmet.decrement_number_by_1",
	"Ctrl-Alt-Up": "emmet.increment_number_by_01",
	"Ctrl-Alt-Down": "emmet.decrement_number_by_01",
	"Shift-Ctrl-Up": "emmet.increment_number_by_10",
	"Shift-Ctrl-Down": "emmet.decrement_number_by_10",
```

There is a bunch of options actually. Ctrl-↑ didn't work for me either, because I had something else on my system. Maybe that's the case for you too?

Our popup is wrong about what the default keys do though, so I can update that.

**Comment by chickenroyal** [comment]
All those bindings are working fine here, it was just "Opt" appearing on Windows that I'd noticed needed updating. Thanks again :)

**Comment by chriscoyier** [comment]
Ah I see the WORD "Opt" doesn't meaning anything on Windows keyboards, it should SAY "Alt" instead.
