### ISSUE TITLE
inception pens

### ISSUE THREAD

**Issue by tomByrer** [CodePen/CodePen-Bug-Reporting-Only#132]
http://codepen.io/stephenjbell/pen/zGqbOb
Click on "My New Pen"

**Comment by mariemosley** [comment]
We know that can be surprising, but it's not a bug :) Adding target="_blank" to your links is one workaround. 

More details here: http://blog.codepen.io/2016/01/29/codepen-ception-explained/

There are a few other ideas for workarounds in the comments on that post.
