### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by AustinPaquette** [CodePen/CodePen-Bug-Reporting-Only#135]
+1 for using nginx

On the URL http://codepen.io/assets/ it shows a 403 rather than perhaps where a 404 could be?

**Comment by chriscoyier** [comment]
That's weird. Def should be 404.

**Comment by AustinPaquette** [comment]
Could just be something a little to ambiguous regarding the assets key word? I have no idea how y'all handle routing or setup your web server but that would be my personal first get :stuck_out_tongue:

**Comment by chriscoyier** [comment]
Sounds like we need to deal with this in a unique way. It's part of our asset pipeline. We'll have to drop in a raw HTML file into our nginx config and stuff. Probably just gonna not fix this for now since URL hacking is probably the only way to get here.
