### ISSUE TITLE
Console scales erratically while resizing other editor windows 

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#136]
Sometimes it feels intentional, other times it just behaves strangely. Weirdest is when you have the console mostly minimized and drag the other editors toward it, causing it to jump up to meet the other windows. Sorry for the choppy gifs, hope it illustrates what I'm talking about well enough.

<hr>
<hr>

![yj9ig0j5pm](https://cloud.githubusercontent.com/assets/8040471/13514596/1ab832c8-e15f-11e5-987b-67846ccd033f.gif)

<hr>
<hr>

![dwolvjkz2k](https://cloud.githubusercontent.com/assets/8040471/13514598/1cb2caf2-e15f-11e5-96fa-3416b8228d8c.gif)

**Comment by chriscoyier** [comment]
It's a thing. @desandro has a fix - coming soon I think!

**Comment by chriscoyier** [comment]
Erp, it's this one https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/105

**Comment by alexzaworski** [comment]
Oh sweet, didn't realize this was caused by the same thing. Glad that's all getting sorted soon :)
