### ISSUE TITLE
Prefill API POST doesn't respect "editors" option

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#14]
Originally opened by @MichelSimonot here: https://github.com/CodePen/redesign/issues/178

> my Prefill Requests have not been using the "editors" option and opening with the panes I want. All the panes are opened when loaded as if there was no option supplied. I was hoping https://github.com/CodePen/redesign/issues/112 would help shed some light, but that was fixed.

> Is the POST to Prefill API the same as before the redesign, or is the documentation still being updated?

> Here's what I'm trying to do:

``` javascript
{
    'title': 'Pen Title',
    'html': '<!-- Pane is open. -->',
    'css': '/* Pane is closed. */',
    'js': '/** Pane is open. */',
    'editors': '101'
}
```

**Comment by chriscoyier** [comment]
Quick fix: POSTING to ?editors=101 (for example) works.

Marc-Andre Lafortune in Support 3858 mentioned this too, update him when fixed.

**Comment by MichelSimonot** [comment]
Noticed that using the `editors` option seems to be fixed now (thanks!).
It's working with the console pane as the fourth digit as well.

**Comment by chriscoyier** [comment]
Wonderful! Yeah I think @quezo fixed this up. I'll close.
