### ISSUE TITLE
Been getting quite a few 'aw snap' errors in Chrome lately.

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#141]
These dudes:

![screen shot 2016-03-08 at 5 03 56 pm](https://cloud.githubusercontent.com/assets/8040471/13621913/c681631a-e54f-11e5-8deb-f9926c3515a7.png)

For the most part they're pretty random. The closest I've found to something 'reproducible' is going absolutely *insane* with the Pen embed controls on the new post page (usually after about 20-60s of fiddling), but I definitely do get them when using CodePen as a (mostly) sane person, most frequently when using pagination links:

![hha5fvzg5q](https://cloud.githubusercontent.com/assets/8040471/13621873/a7398046-e54f-11e5-86a2-93f8aacb7a7f.gif)

edit: I swear it happens more often with dev tools enabled, too... I had them open when recording that gif, and then couldn't reproduce afterward with them closed. Totally weird.

**Comment by mariemosley** [comment]
Sorry about that! The "Aw, Snap" crash is a memory thing, and we know that lots of Pens are memory hogs. We work to mitigate that, but some of the more boundary-pushing stuff can really tax the browser even with our safeguards in place. 

With that said, there are a couple of things you can do if this is becoming a frequent nuisance for you:

- If you're browsing CodePen with the "12 Pens at a time" view, try switching to 6 with the view switcher (screenshot here: http://d.pr/i/1hMpM/5xxDEGqe )
- Switch your Browsing preference from iframes to images in https://codepen.io/you/settings/customize

There are also some more general suggestions in the [Chrome docs](https://support.google.com/chrome/answer/95669?hl=en).

**Comment by alexzaworski** [comment]
Hi Marie,

That makes a loooot of sense— thanks!
