### ISSUE TITLE
Make raw url useable as external resource?

### ISSUE THREAD

**Issue by jaminroe** [CodePen/CodePen-Bug-Reporting-Only#143]
I have a bitbucket repo, with some CSS files. It's similar to Github, and I'm using git as well. There a way to convert the raw url, so that it's useable in a pen?

For example, I have this file: https://bitbucket.org/jaminroe/code-playgrounds/raw/9edb225d7550ab89ab9c109c8131e4687fd8ab7e/Icons/icomoon/icomoon.css

Thanks!

**Comment by chriscoyier** [comment]
That URL 404's for me, so it would 404 for CodePen trying to access it. Probably requires Auth? 

For any resource like that you wanna try, try opening it in an Incognito (or "Private") window and see if it loads. If it does load, just dropping that URL in here should work:

![img](http://d.pr/i/1gZkx/2lFKbHvK+)

Or drop a copy of the file in our own Asset Hosting: https://blog.codepen.io/documentation/pro-features/asset-hosting/

**Comment by jaminroe** [comment]
I ended up just using Github to host some of my files :) Works perfectly now. Thanks for the suggestion though!


-- 
Reony Tonneyck
Sent with Airmail 

On March 9, 2016 at 9:29:01 AM, Chris Coyier (notifications@github.com) wrote:

That URL 404's for me, so it would 404 for CodePen trying to access it. Probably requires Auth?

For any resource like that you wanna try, try opening it in an Incognito (or "Private") window and see if it loads. If it does load, just dropping that URL in here should work:



Or drop a copy of the file in our own Asset Hosting: https://blog.codepen.io/documentation/pro-features/asset-hosting/
