### ISSUE TITLE
Tidy jsx code

### ISSUE THREAD

**Issue by fibo** [CodePen/CodePen-Bug-Reporting-Only#144]
Clicking on the "Tidy" button when using Babel preprocessor gives a result like this

<img width="702" alt="screen shot 2016-03-09 at 10 02 02" src="https://cloud.githubusercontent.com/assets/176730/13630161/100fec5c-e5de-11e5-83dd-e214daecb5c0.png">

**Comment by chriscoyier** [comment]
We're going to have to shut off the Tidy function for Babel probably. It's kinda sad, because it's really JSX that's failing to be Tidy'd here, not Babel. And I think the Tidy function works OK with ES2015 stuff. And we have no idea if you're going to use JSX or not when you select Babel. But.... just the way she goes. (It does this on JSFiddle as well). 

Someday we'll find really good Tidy functions that work for all scenarios. Even if we gotta go server side. I know I'd like one that works with SCSS.

**Comment by chriscoyier** [comment]
Possibility for SCSS/LESS: http://www.dirtystylesheet.com/

Possibility for JSX: http://prettydiff.com/guide/react_jsx.xhtml

Haml / Jade / Slim / Sass / CoffeeScript == whitespace dependant so probably don't need one.

**Comment by fibo** [comment]
Yep, it is a cross problem it will be solved probably in the near future.
I just wanted to contribute back, since your product is really great.

**Comment by chriscoyier** [comment]
A fix for this will go up today. Not really a fix actually, but turning off that button for Babel until we can do more robust/better Tidy stuff.

**Comment by fibo** [comment]
Mmh, it could be better.
Babel from version 6 is modular, you can distinguish from babel with ES2015 and babel react (with jsx).
The issued case is the latest, so there should be two Babel, one for each preset. Only Babel with jsx should disable indentation.

See as a reference: https://babeljs.io/docs/plugins/#presets

**Comment by chriscoyier** [comment]
That sounds pretty smart. We'll consider it for sure. Maintaining two separately configured Babel's though (forever) is uncharted territory for us though and doesn't sound super appealing. I'd rather have a perfect Tidy function, and we have some leads on that.

**Comment by volv** [comment]
Would love to have the tidy button back.  At the moment I am disabling Babel, tidying and re-enabling which is not ideal.

**Comment by yukulele** [comment]
since v1.4.0 js-beautify have a `e4x` option for that
https://github.com/beautify-web/js-beautify#options
https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md#v140

**Comment by chriscoyier** [comment]
Reopening as it looks like the lib we use can support it ^^^

**Comment by chriscoyier** [comment]
JSX tidy going out in next deploy!
