### ISSUE TITLE
cssnext package

### ISSUE THREAD

**Issue by TrySound** [CodePen/CodePen-Bug-Reporting-Only#146]
cssnext package was deprecated in favour of [postcss-cssnext](https://github.com/MoOx/postcss-cssnext). postcss-cssnext does not include postcss-import and postcss-url. Also name changing will prevent confusion between cssnext and postcss-cssnext names.

/cc @MoOx

**Comment by MoOx** [comment]
Everything you need to know is here http://cssnext.io/postcss/

**Comment by chriscoyier** [comment]
We have some Pens using

```
@use cssnext;
```

Example: http://codepen.io/anthonydugois/pen/mewdyZ

Which would be good to not break. Can we / should we alias that to `postcss-next`?

**Comment by TrySound** [comment]
@chriscoyier Yeah. That's good. But can you show in plugins list only `postcss-cssnext`?

**Comment by MoOx** [comment]
@chriscoyier I guess some features that have been removed from cssnext where not enabled:

- import (for security reason if my memory is correct, and anyway make no sense in a playground)
- url (related to import)
- compress (disabled by default and make no sense in a playground)

The only thing you are going to loose are "messages" that were shown in the view via html::before hack, but this one can be replaced by postcss-browser-reporter.

So I think it's totally safe to alias cssnext as postcss-cssnext.

And about messages, I think you should display them as a native thing in your UI, like your probably does for Sass error and things like that

**Comment by MoOx** [comment]
(And for the record no breaking changes in features (output) if my memory is correct (or mabye just one or two minor things but not even sure, just changes in the API, see http://cssnext.io/postcss/).

**Comment by chriscoyier** [comment]
We're having some problems with cssnext timing out. 

Sometimes happens on this file: https://codepen.io/chriscoyier/pen/QEWjMz (fork)

![img](http://d.pr/i/18G01/39fqem5N+)

@tim probably a good time to get this lib swapped out for the newer version.

**Comment by mariemosley** [comment]
We've moved this to our [Known Issues trello board](https://trello.com/c/JNhKzSBm/6-cssnext-deprecated-in-favor-of-postcss-cssnext) Thanks very much for bringing this to our attention!
