### ISSUE TITLE
False positive detection of circular reference in a console

### ISSUE THREAD

**Issue by zubko** [CodePen/CodePen-Bug-Reporting-Only#147]
This code
```
var o = {};
o.a = [1,2,3,4];
o.b = o.a;
console.log(o);
```
will make such output in the console:
<img width="294" alt="screen shot 2016-03-11 at 2 24 55 pm" src="https://cloud.githubusercontent.com/assets/16039/13702129/0fed905e-e795-11e5-8848-52c1173bc5ba.png">

**Comment by chriscoyier** [comment]
This is on our side. 

<img width="447" alt="screen shot 2016-03-21 at 3 33 56 pm" src="https://cloud.githubusercontent.com/assets/69156/13931583/64f0228c-ef7a-11e5-9529-a7b0cdeac58e.png">

**Comment by mariemosley** [comment]
We've moved this to our [Known Issues trello board](https://trello.com/c/pQU7UE2j/16-false-positive-detection-of-circular-reference-in-a-console). Thanks very much for bringing it to our attention!
