### ISSUE TITLE
The Future of CSS "Resets" on CodePen

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#149]
There has been some demand for adding [Sanitize.css](https://github.com/10up/sanitize.css) to our list of resets. I personally like it, if for nothing else, it includes `box-sizing: border-box` as a default which I almost always use and no other "reset" sets.

The seemingly-obvious place to put it is here:
<img width="436" alt="screen shot 2016-03-13 at 1 33 13 pm" src="https://cloud.githubusercontent.com/assets/69156/13730543/2fe0e000-e920-11e5-87a7-004d7e55c7f6.png">

But... We've been moving away from adding assets through UI like that.

For example, it wasn't too long ago when we did away with the dropdown menu for selecting a JavaScript library. Before that, you could, for example, pick "jQuery" from a dropdown menu and it would automatically be included in the preview before your authored JS. There were many problems with that, over time:

1. It was on us to keep the versions there updated
1. When we updated, it updated the version for everything using it (potential breaking changes)
1. It was weird you could only pick one

Instead, we moved to using a feature we already offered more heavily: **External Resources.**

You can still pick "jQuery" from a dropdown, but all it does is insert a link to a CDN-hosted version of jQuery. You can pick multiple libs, rearrange them, whatever, and they'll stay exactly as you leave them.

We should probably start doing this with CSS "resets" as well. We should keep the ones we have:

- Meyer Reset
- Normalize.css

But add:

- Santize.css
- Other popular ones???
- http://milligram.github.io/index.html ?

And also break into sections... Perhaps like this?

<img width="325" alt="screen shot 2016-03-13 at 1 48 57 pm" src="https://cloud.githubusercontent.com/assets/69156/13730637/5d33b0f8-e922-11e5-91f1-8c60156447b1.png">

**Comment by alexzaworski** [comment]
Not sure if this is open to user feedback but I'd like to see something similar to what Ninite does where you can tick a bunch of boxes and then click "add" and get 'em all at once. They also break things into categories.

It isn't as compact as what you've proposed but to me this feels like totally the wrong use for a `<select>`; which makes me assume I only get one. Here's what I'm talking about:

<img width="1218" alt="screen shot 2016-03-15 at 9 45 59 am" src="https://cloud.githubusercontent.com/assets/8040471/13785966/f0416252-ea92-11e5-89b0-036d08897f5e.png">

This also makes it super easy to add/remove stuff on the fly. Obviously dropping a metric boat load of check boxes into the current UI isn't going to work but I'd guess there's something that could be worked out there... Maybe a toggle button for each category? eg (world's quickest mockup, please no judgment <3 ):

![screen shot 2016-03-15 at 9 51 30 am](https://cloud.githubusercontent.com/assets/8040471/13786125/87101db8-ea93-11e5-967c-7a64a82013c7.png)

Each section could even fit the width of the rest of the buttons when open, allowing multiple columns. 

The other thing I like about what I suggested is that it allows you to use radio buttons for options that ought not be used together.

**Comment by jonathantneal** [comment]
I like where this is going with the drop-downs. Thanks for creating this issue.

I think CSS bases like normalize, sanitize, bootstrap, of foundation are really intended to work underneath my own css, so I’d expect to choose just one of them from a list. I think companion libraries like animate and others like this are meant to run on top or alongside other libraries, so I’d expect to be able to choose one or more of these.

I think it would be pretty cool if I could search these drop-downs for the curated options. Even more extra special would be if I could use this same text field to add my own URL to something custom. So, in a sense, the whole thing would be like the current **Add External CSS** section integrated with the **Quick-add** dropdown.

![example-1](https://cloud.githubusercontent.com/assets/188426/13827429/ce979710-eb92-11e5-8a82-21084e4f5a31.png)

![example-2](https://cloud.githubusercontent.com/assets/188426/13827432/d5509160-eb92-11e5-873a-855f6363dfda.png)

I didn’t realize you’re using CDN to link things like jQuery. Would you plan to do the same with CSS libraries? Does the extra DNS lookup slow things down a lot more perceivably when it’s for stuff like CSS?

Okay, now I’m probably thinking out of scope, but another consideration is whether it would be helpful to have a “discoverable” feature where I’m typing in jQuery 2 and seeing a quick add for a locked (v2) version of jQuery.

FWIW, I think whatever approaches are taken for this could also be applied to pre-processors and PostCSS plugins.

I wish I had more time to prototype some of these options. I hope this helps!

**Comment by alexzaworski** [comment]
So I messed around a bit trying to stay within the confines of already-established CodePen UI patterns and came up with this:

![screen shot 2016-03-18 at 3 16 51 pm](https://cloud.githubusercontent.com/assets/8040471/13893549/7862ab2e-ed1c-11e5-9777-591c1d3fa71b.png)

["Live" (non-functional) version available here.](http://codepen.io/alexzaworski/pen/JXEgEj)

For what it's worth, I think if you added a "My Pens" tab to pull from and populated it with a (searchable?) list of Pens to add as assets I think it'd be sweet.

**Comment by andyhullinger** [comment]
Love the idea of adding them in similar to JS panel, but...

> I believe it's very important to retain/highlight **reset** as a key option because it's really the only one that tries to "zero-out" everything!

As a teacher of graphic designers (and also in my agency workflow for online advertising banners) it's important to have an option to literally start-from-scratch without having to work around opinionated styling that you don't realize is side effecting your intent.

**Comment by mariemosley** [comment]
We've moved this to our [Known Issues trello board](https://trello.com/c/TdPeZbdf/8-css-resets), and we'll use this discussion to inform our choices for the future. I want to thank everyone in this thread for taking the time to share your feedback!
