### ISSUE TITLE
Back Button from Post Preview = A Bad Time

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#15]
Here's a movie that shows off the problem:

http://d.pr/v/BhQ9/4KffS0e2

Originally reported here: https://github.com/CodePen/redesign/issues/286

I have no idea what the solution here is. I presume it's the browser trying to be helpful but actually hurting somehow. Like perhaps...

1. the page loads with the proper text in the `<textarea>` from the database
2. browser replaces the text in the `<textarea>` to try and "save" what was there from before the back button press
3. Race condition! 
4. CodeMirror doesn't get around to building itself from the textarea until the browser has interfered.

If this theory is true, we shouldn't build from a textarea, we should make it a DIV or something so the browser doesn't interfere.

**Comment by tholman** [comment]
Fixed! Merging now.

This was a fun one, thats for sure.
