### ISSUE TITLE
Case-sensitive search

### ISSUE THREAD

**Issue by dangodev** [CodePen/CodePen-Bug-Reporting-Only#150]
Example: in the case of this pen: http://codepen.io/mullany/pen/sJopz

If I search `photoshop dropshadows` it returns 0 results.

If I search `PhotoShop DropShadows` it’s able to find this pen.

**Comment by andrewnite** [comment]
This has been fixed since search was upgraded.
http://codepen.io/search/pens?q=photoshop+dropshadows&limit=all&type=type-pens
and 
http://codepen.io/search/pens?q=PhotoShop+DropShadows&limit=all&type=type-pens
both return the correct result.
