### ISSUE TITLE
HTTPS & CSS Preprocessor throws insecure XMLHttpRequest endpoint error

### ISSUE THREAD

**Issue by Mestika** [CodePen/CodePen-Bug-Reporting-Only#152]
When running my codepen in `https` and using a CSS Preprocessor (does matter which, they all fail - except none) the console throws the error:  
```Mixed Content: The page at 'https://codepen.io/Mestika/pen/QNGRyL' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://codepen.io/editor/constants/addons/less'. This request has been blocked; the content must be served over HTTPS.````

It kills everything and all other actions cannot be applied (save, add to collection, etc.)

If I change codepen to run on insecure `http` everything works perfect.

**Browser**
`Google Chrome  48.0.2564.116 (64-bit)`

**OS**
`OS X El Capitan 10.11.3`

**Comment by DonKarlssonSan** [comment]
Another use case is getUserMedia() for accessing the mic or web cam, which now a days has to be done over [HTTPS when using Chrome](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins). 

`Mixed Content: The page at 'https://codepen.io/DonKarlssonSan/pen/mVoyVb' was loaded over HTTPS, but requested an insecure image 'http://assets.codepen.io/assets/buttons/arrow-tiny-down-white.png'. This content should also be served over HTTPS.`

My particular Pen still works, I'm just arguing for HTTPS support.

Google Chrome Version 49.0.2623.87 (64-bit), OS X 10.11.3

**Comment by jakealbaugh** [comment]
it appears that save does work, but it is definitely janky. needs fixing.

[!image](http://d.pr/i/1iPCO/3CiG5SkF.png)

http://codepen.io/jakealbaugh/pen/c95c632b72420c623b2225591e461146

**Comment by quezo** [comment]
These errors are fixed now. HTTPS should work without errors now! Thanks for the report.
