### ISSUE TITLE
Add Pens, Collections and Posts to homepage navigation.

### ISSUE THREAD

**Issue by cranesandcaff** [CodePen/CodePen-Bug-Reporting-Only#153]
They are currently hidden underneath a dropdown menu. I come to codepen for the pens not for jobs or other stuff. Those are super nifty additions and I might use codepen to hire someone some day, but I wanna see cool stuff.

**Comment by chriscoyier** [comment]
?

![img](http://d.pr/i/12Yt3/2UAXPKCh+)

**Comment by cranesandcaff** [comment]
I swear...I don't...it's not that...I'm sorry.
