### ISSUE TITLE
Fixed header issue with codepen example

### ISSUE THREAD

**Issue by bhavikyshah** [CodePen/CodePen-Bug-Reporting-Only#154]
http://codepen.io/anon/pen/JGEKMO

I am using above example for fixed header issue
It is working fine with all browser but not working in **Chrome browser** with **iOS** (iPad) OS

However it is working fine with chrome browser of windows os

Any one find any specific reason why it is not working with that specific browser

**Comment by chriscoyier** [comment]
Here's the (sucky) short answer.

There is a bug (I consider it a bug) on iOS browsers where you can't set the height of `<iframe>`s, they expand to the height of what they contain. That's not good for our UI, we want to fix a height and allow you to scroll your preview. So, we wrap the iframe in a div and that div scrolls (if the iframe is taller than the div area we set).

So it's not that fixed positioning is broken, it's that the iframe itself isn't scrolling, so fixed positioning isn't coming into play. 

Totally annoying and hopefully someday we can fix when iOS fixes (if they also consider it a bug).
