### ISSUE TITLE
First page of search results occasionally displays incorrect number of Pens

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#155]
I feeeel like this came up before back when the redesign bug reporting repo was still around but I can't look up old issues from that (I don't think?). Some searches only display 10 (or fewer?) Pens on the first page, even when there are more than that:

![6rrotzwmx5](https://cloud.githubusercontent.com/assets/8040471/13857657/0f91107a-ec38-11e5-80bc-7def9994618e.gif)

**Comment by mariemosley** [comment]
That can happen when a Pen that was in the search was recently deleted. It doesn't last long :)

**Comment by alexzaworski** [comment]
Hi Marie :) What is considered not lasting long? It's still happening on the same search query from 4 days ago.

**Comment by chriscoyier** [comment]
Or Pens that have been tagged as removed from search from us, or Pens that are tagged as spam at the moment, or a few other things. Ideally we'd adjust other Pens to move forward, but that's tricker than it's worth.
