### ISSUE TITLE
Autocomplete suggestions in Pen Settings modal forces scrollbars which causes a distracting text shift

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#156]
Hardly a 'bug' but it's pretty annoying. I also think it's sort of weird that the scrollbar on the suggestions doesn't match the one on the modal itself.

![mkac1yu9v0](https://cloud.githubusercontent.com/assets/8040471/13886518/79b8535c-ecf4-11e5-9372-9c133afeadd0.gif)

Suggestions for possible fixes:

- Have the modal's scrollbar on all the time
- Just add some padding as a placeholder for the scrollbar (I think I like this one best)
- Ignore this 'cause it basically doesn't matter :ok_hand:

**Comment by chriscoyier** [comment]
We can/should make those styles match. I can do this today.

**Comment by alexzaworski** [comment]
Sweet, thanks Chris

**Comment by alexzaworski** [comment]
Hey so I was looking at this again today 'cause that text shift still bugs the heck out of me... Would you guys consider `overflow-y:scroll` instead of `auto` on that container? It stops the shift from occurring:

![kjkqapaaep](https://cloud.githubusercontent.com/assets/8040471/15342742/a54e31e4-1c4c-11e6-8b62-7d7507c2e7d8.gif)

Granted the spacing gets a bit goofier; maybe if it only had 10px of padding on the right side it'd be fine though?

Also, it's a little weird that the scroll bar from the suggestions ends up clipped by the modal:

![vja6pbe7kt](https://cloud.githubusercontent.com/assets/8040471/15342778/d5d2d540-1c4c-11e6-873a-19e633a4c249.gif)

But that seems _really_ hard to fix and doesn't really matter all that much.
