### ISSUE TITLE
Sorting Collections by popularity does not work

### ISSUE THREAD

**Issue by DonKarlssonSan** [CodePen/CodePen-Bug-Reporting-Only#158]
When I list my collections by popularity they come in random order.
This is true for both [grid view](http://codepen.io/DonKarlssonSan/collections/popular/) and [list](
http://codepen.io/DonKarlssonSan/collections/popular/?grid_type=list).

A server side problem I would guess but here is my client info: Google Chrome Version 49.0.2623.87 (64-bit), OS X 10.11.3

Maybe you can implement client side sorting to avoid post backs whenever clicking a column header like `Title` and `Last Updated` when in list mode?

**Comment by mariemosley** [comment]
This is related to this bug: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/16 We're working to fix it :)
