### ISSUE TITLE
Rachel Smith's Hack Physics Post is Gettin' Glitchy Wit It

### ISSUE THREAD

**Issue by sdras** [CodePen/CodePen-Bug-Reporting-Only#159]
Hey Ya'll, 
I was going through some Rachel Smith posts trying to get my Canvas learn on, and came across some bits of weirdness in the embedded pens in the post (but the actual pens are fine).

I'm on a Mac and using Chrome (not Canary).

<img width="885" alt="screen shot 2016-03-19 at 4 19 52 pm" src="https://cloud.githubusercontent.com/assets/2281088/13901857/fbc4c72c-edee-11e5-9a63-8e5a26c1a869.png">
<img width="810" alt="screen shot 2016-03-19 at 4 19 07 pm" src="https://cloud.githubusercontent.com/assets/2281088/13901858/fbc52906-edee-11e5-8c4e-e44336cd88f4.png">
<img width="828" alt="screen shot 2016-03-19 at 4 19 01 pm" src="https://cloud.githubusercontent.com/assets/2281088/13901859/fbc6034e-edee-11e5-974d-e7dc753fccc4.png">

**Comment by rachsmithcodes** [comment]
thats so weird (and kinda cool looking)! I can't make it happen on my Chrome for this post. But I've totally seen this visual artifacting happen in Chrome on other sites before. We'll keep an eye on the embeds for this. Thanks Sarah!
