### ISSUE TITLE
Grid View of collections repeats some collections, omits others

### ISSUE THREAD

**Issue by mariemosley** [CodePen/CodePen-Bug-Reporting-Only#16]
Reported on Twitter: https://twitter.com/michaelgearon/status/668864821132206080

Both list view and grid view of a member's collections show the same amount of collections, but only the list view shows all of the collections. The grid view omits two collections and instead repeats two of the collections that were on the first page. 

Video demonstrating this:
http://d.pr/v/1dmL2/2bjuZBxU

**Comment by chriscoyier** [comment]
![problem with popular](http://d.pr/i/16bz0/4RBg0QGp+)

This has to do with POPULAR collections only.
