### ISSUE TITLE
Using super() in class constructor.

### ISSUE THREAD

**Issue by Haktrum** [CodePen/CodePen-Bug-Reporting-Only#160]
Using ```super();``` inside a class constructor throws **Unknown expression type: Super** in the editor.
[Test case](http://codepen.io/Haktrum/pen/NNprWq?editors=0012)

**Comment by alexzaworski** [comment]
Doesn't ES6 need Babel to work?

**Comment by Haktrum** [comment]
Babel translates ES6 to ES5, but ES6 support in browsers is pretty good nowadays. My code runs fine if I open it in Debug Mode.
I see allowing ES6 classes but not ES6 `super()` as a bug.

**Comment by alexzaworski** [comment]
Oh neat, learned something today :)

**Comment by pixelass** [comment]
@Haktrum your testcase does not use Babel.  Here's a fork with babel activated. 

http://codepen.io/pixelass/pen/greVoG?editors=0012

Anyways this would be a babel issue  and not related to codepen.

**Comment by Haktrum** [comment]
@pixelass why should the testcase use Babel?
This is a bug in CodePen's modified version of Esprima, it's not related in any way to Babel.

**Comment by pixelass** [comment]
@Haktrum my bad. I guess I misunderstood your second comment. You are talking about the error the coderunner returns? so you are suggesting that the coderunner supports ES2015?

+1 on that, though I always use babel

I think it would be nice to have a settings.json per user which would allow setting plugins/presets etc.

**Comment by rajatsehgal** [comment]
I also ran into this:
<img width="244" alt="screen shot 2016-05-03 at 12 49 54 am" src="https://cloud.githubusercontent.com/assets/1487343/14974907/05e15d9a-10c9-11e6-9f89-2cb93a2a2d7c.png">
I expect to be able to use ES6 without Babel in CodePen if the browser I'm running it on supports those ES6 features.

**Comment by quezo** [comment]
We just released a fix for this bug. Thanks for the bug report.
