### ISSUE TITLE
Lower portion of the screen remains inaccessible. 

### ISSUE THREAD

**Issue by NijilNair7** [CodePen/CodePen-Bug-Reporting-Only#161]
![image](https://cloud.githubusercontent.com/assets/17722277/13944777/088a2bc8-f02e-11e5-93a2-61e7198c6426.png)
Does anyone know how to remove it ?

**Comment by tholman** [comment]
Hmmm, I can't seem to replicate this one :/

Do you think you could send over a pen with it? Or if all new pens look like this (smaller iframe), shoot over the browser/OS

Cheers!

**Comment by NijilNair7** [comment]
I am using Google Chrome in Windows 10. And I don't think it has anything
to do with the pen. Once I reload the page, the pen can be viewed in full
screen. But after some time the lower portion becomes dark again. Any
suggestions, please ?

**Comment by mariemosley** [comment]
I'm sorry but we're still not able to reproduce this. Perhaps a browser extension is interfering with your view of CodePen? If you have any extensions enabled, try visiting the page in an incognito window, or with your extensions disabled. If this keeps happening even with extensions off, please email us at support@codepen.io and do some more troubleshooting :)
