### ISSUE TITLE
Preview Re-run via cmd-shift-5 triggers "remember to save your work" reminder

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#162]
Continuously re-running a Pen via the keyboard shortcut apparently counts as making a savable change:

![spvv2z503w](https://cloud.githubusercontent.com/assets/8040471/13961802/5d1c6308-f01b-11e5-895f-8ad6f46943d2.gif)

**Comment by chriscoyier** [comment]
Counting refreshes is the easiest way for us to track that kinda thing. I think we'll leave this alone to encourage saving. And remember it only bugs you until you save once, then autosave is on.

**Comment by alexzaworski** [comment]
Makes sense, appreciate the reply— thanks!
