### ISSUE TITLE
Line wrapping not working

### ISSUE THREAD

**Issue by 3WhiteWolfWizard** [CodePen/CodePen-Bug-Reporting-Only#164]
Line wrapping isn't working even though it's checked in my settings.

Thanks for everything. Keep it up. :+1:

**Comment by chriscoyier** [comment]
Seems to be fixed! Tested as you:

![screen shot 2016-03-29 at 1 37 53 pm](https://cloud.githubusercontent.com/assets/69156/14119376/7d0c6788-f5b3-11e5-867f-34fbddbe8bb2.png)

If still having trouble, shoot over any pertinent info/screenshots.
