### ISSUE TITLE
Share via SMS breaks when handling invalid phone numbers

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#165]
It does this:

![mzozcq2b1r](https://cloud.githubusercontent.com/assets/8040471/13991155/491add62-f0d4-11e5-9663-a62e3ecbb546.gif)

**Comment by chriscoyier** [comment]
Will get fix up today:

![screen shot 2016-03-29 at 1 46 07 pm](https://cloud.githubusercontent.com/assets/69156/14119641/c2a8270e-f5b4-11e5-8f95-33877ac436ca.png)

**Comment by alexzaworski** [comment]
Y'all are on a roll today :)
