### ISSUE TITLE
"Free" text in new signup modal is barely a different green from "Sign Up"/"Log In

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#166]
Was this intentional? #3D7D47 vs #2BA753

**Comment by rachsmithcodes** [comment]
hi, yes this was intentional :)

**Comment by alexzaworski** [comment]
Hi Rachel,

... Actually not sure how this issue was submitted, meant to close the tab ¯\_(ツ)_/¯ such is life. Thanks for the response anyways :)
