### ISSUE TITLE
Editor settings disappear on Pens created from a template until first save

### ISSUE THREAD

**Issue by RavingAPD** [CodePen/CodePen-Bug-Reporting-Only#167]
Hey guys!

Recently my line numbers has disappeared in the editor, I've tried to disable any css templates injected  for the editor with no luck and also tried saving my settings again n' such. Still no luck.

**Comment by mariemosley** [comment]
We're trying to reproduce this but haven't been able to so far. Can you let us know your browser type and version, and which syntax highlighting theme and font you're using in your editor settings (you can check that at https://codepen.io/you/settings/editor)? That info can help us narrow down the problem.

**Comment by RavingAPD** [comment]
I've digged some more into the issue and it seems like it's when I use a template to create a new pen. The template itself has the line numbers, but when I use it to create a new pen it's like the line number div gets delete. Template here: https://codepen.io/R4ver/pen/gPWgYx

I use Chrome Canary with the latest update, but the same thing happens in regular Chrome on latest update. (FireFox is affected by this too.)

Editor settings:
- Syntax Highlighting:
    - Twillight
- Fonts:
    - Source Code Pro, 14px
- Key Bindings
    - Sublime Text
- Code Indentation
    - Spaces, 4
- Preprocessor
    - HTML: Normal
    - CSS: Sass
    - CSS Reset: Normalize
    - Prefixing: Autoprefixer
    - JS: Babel
    - Auto Update: true
- Editor Options
    - Everything is ticked

**Comment by mariemosley** [comment]
We'll dig into this, thanks for the details :) I've retitled this issue since it seems to be isolated to Pens created from templates.

**Comment by RavingAPD** [comment]
Thanks, and that title fits better, yes ;)

I just wanted to test something and apparently I can't even create a new template, to just have a standard template with no preprocessors or such for testing. Amazing! :D
When I tick the pen to be template and save, it just goes to be a normal pen.

**Comment by mariemosley** [comment]
That sounds like this issue: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/61

Sorry you're hitting all the template bugs! Thanks for taking the time to report it

**Comment by RavingAPD** [comment]
No problem! :D

**Comment by jasesmith** [comment]
I've noticed this as well: missing line numbers with pens spawned from a template. There are more issues than missing line numbers. The code folding is gone (which I'm guessing is tied to the line numbers container) and the bracket matching function of the editor is not employed.

Seems like the editor options (from Edit Profile) are not getting used or respected, or over-written.

**Comment by jasesmith** [comment]
Bit of additional info: I did notice that once you save a pen, it reloads the editor, removes the `?template=whatever` flag, and editor settings are displaying as expected.

**Comment by jakealbaugh** [comment]
@jasesmith yeah, thats definitely what that is. new pens from template are inheriting the preprocessor settings of the template instead of the user and are skipping the other user settings along the way. we're on it. thanks.

**Comment by jakealbaugh** [comment]
renamed this to be more overarching as `vim` and `sublime` keymapping/shortcuts dont work either until first save.

**Comment by jakealbaugh** [comment]
most of these fixes just went out. we're still watching some other edge cases in our private repo, but everything addressed here should be squared away. thanks for the heads up everyone!
