### ISSUE TITLE
Bootstrap affix not working

### ISSUE THREAD

**Issue by jasper-ballantyne** [CodePen/CodePen-Bug-Reporting-Only#168]
Bootstrap affix doesn't seem to be working inside codepen.
I've copied and pasted <a href="http://www.w3schools.com/bootstrap/bootstrap_affix.asp">this</a> w3schools code for bootstrap affix into <a href="http://codepen.io/jasper-ballantyne/pen/yOXomx">this</a> codepen and it is not working the same way. The navbar should stick like it does on the w3schools example. 
Keep up the good work :)

**Comment by mariemosley** [comment]
Affix is a jQuery plugin for Bootstrap, so you'll need to add both jQuery and bootstrap.js to your Pen to get it working. You can add them both from the quick-add menu in your Pen's JavaScript settings. 

We have some more info on how external resources work on CodePen in our docs at: https://blog.codepen.io/documentation/editor/adding-external-resources/
