### ISSUE TITLE
Mobile (small) issues

### ISSUE THREAD

**Issue by Mamboleoo** [CodePen/CodePen-Bug-Reporting-Only#169]
Hey,

I was really bored today so I tried the website on my phone. I noticed a few things that may be broken, or at least I found weird.

## 1. Extra navigation panel
I can't close it by touching anywhere on the page. The only way to hide it is by clicking again on the little arrow.
<img src="https://cloud.githubusercontent.com/assets/6048794/14081900/465f507a-f50d-11e5-9c8b-cc336d739bc4.png" width="200"  />

## 2.  Gradient on search tab
The gradient is a bit too small and the input radio are not very visible when the keyboard is open. When the keyboard is closed the gradient is ok.
<img src="https://cloud.githubusercontent.com/assets/6048794/14082058/317e400c-f50e-11e5-9d17-f4e9316298a9.png" width="200"  /> <img src="https://cloud.githubusercontent.com/assets/6048794/14082062/328f077e-f50e-11e5-9005-a27b7bb63640.png" width="200"  />

## 3. Details tab on a pen
When clicking on **Lovers** or **Forks** nothing happens. I can only see the **Stats**
<img src="https://cloud.githubusercontent.com/assets/6048794/14082131/a0387256-f50e-11e5-9f9f-2f66f979b42d.png" width="200"  />

## 4. GitHub icons
The icons of GitHub seems a bit displaced compared to Facebook and Twitter.
<img src="https://cloud.githubusercontent.com/assets/6048794/14082190/eccf5634-f50e-11e5-9ce0-c1970e09f30c.png" width="200"  /> <img src="https://cloud.githubusercontent.com/assets/6048794/14082191/ecd20dca-f50e-11e5-83a4-1a00c7bec090.png" width="200"  />

For the specifications : 
I'm using Chrome 49.0.2623.91 on Android 6.0.0.

I hope this could help you !
Mamboleoo

**Comment by chriscoyier** [comment]
Hey @Mamboleoo - 

This is so awesome. Thanks so much. I've address all of these and all the fixes should be out later today.
