### ISSUE TITLE
Quick-add for jQuery doesn't use HTTPS link

### ISSUE THREAD

**Issue by CharmedSatyr** [CodePen/CodePen-Bug-Reporting-Only#170]
Quick-add for jQuery adds this link to the page's code:

http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js

Please update this link to use HTTPS instead of HTTP! I.e.,

https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js

This simple edit would be really helpful for folks trying to keep secure sites with jQuery.

**Comment by chriscoyier** [comment]
The quick add is adding:

```
//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js
```

which should work both ways.

**Comment by CharmedSatyr** [comment]
When the pen is exported via .zip, this line appears as 

`<script` src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js'></script>

This results in a mixed content warning on multiple browsers. It should read https.
