### ISSUE TITLE
Some buttons don't work on the style guide page

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#172]
http://codepen.io/guide/

You can't access your account/view notifications/search/a few other things. The New Pen/New Post buttons work though :ok_hand: (but not the New Pen dropdown) 

![hzndnv5j2a](https://cloud.githubusercontent.com/assets/8040471/14085700/268d7af6-f4d6-11e5-9619-34f85b9326ae.gif)

Also, the GitHub button is wonky, no clue if that's related to the issues in #169 :

<img width="211" alt="screen shot 2016-03-28 at 11 13 16 am" src="https://cloud.githubusercontent.com/assets/8040471/14085693/2081b64a-f4d6-11e5-8e16-52cf1ce794f5.png">

**Comment by chriscoyier** [comment]
Good catches! Will get this fix out today.
