### ISSUE TITLE
pen previews with web animation API never stop

### ISSUE THREAD

**Issue by pixelass** [CodePen/CodePen-Bug-Reporting-Only#173]
I created this collection to showcase this issue: http://codepen.io/collection/DgPrpK/

The pens using the new web animation API never stop running. Since the API does not offer pause/stop etc unless you create a player it might be hard to control.

I think a pretty safe change is to generally replace `Infinity` with an integer.

**Comment by chriscoyier** [comment]
Ah yes. This is a bit problematic.

```js
// can stop, because we have access to player
var player = ball_1.animate(scene_1, animationOptions);

// can't stop, no player TO stop
ball_1.animate(scene_1, animationOptions);
```

@quezo We may need to use esprima and whatnot to instrument the JS to force all .animate() calls to create a player that we can then stop. Replacing `Infinity` seems a bit heavy handed and error prone (there is also duration and delay that play a part here). 

We ARE able to find and stop `requestAnimationFrame` with a little trickery without resorting to instrumenting, so I wonder if that'll be possible here too??

**Comment by pixelass** [comment]
As stated [here](https://w3c.github.io/web-animations/) we are supposed to get animations assigned to an element via `el.getAnimations()`. 

The function below will actually work in Chrome Canary (51)

```js
setTimeout(()=>{
  if (typeof el.getAnimations === 'function')
    el.getAnimations().map(animation=>animation.pause());
},5000);
```

**Comment by pixelass** [comment]
Here's an idea. Force load the polyfill to access the new features. 

The 'next'  version includes `getAnimations`  
https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.1.4/web-animations-next.min.js


I updated the example: http://codepen.io/pixelass/pen/b01ee82fa9e880643233d0f1e8e7a21c

The polyfill will give you access to all animations and stop them (works in Chrome Canary without the polyfill too)

```js
setTimeout(()=>{
  if (typeof document.timeline.getAnimations === 'function')
    document.timeline.getAnimations().map(animation=>animation.pause());
},5000);
```

This will actually allow some pens to run cross-browser in preview but not in normal views, so I'm not sure if that's what you want.

**Comment by mariemosley** [comment]
We've moved this to our new [Known Issues trello board](https://trello.com/b/TJZXJa3G/known-issues) Thanks very much for letting us know, and thank you for the suggestions @pixelass 👍
