### ISSUE TITLE
Quick-Add for jQuery, when exported via .zip, does not use HTTPS

### ISSUE THREAD

**Issue by CharmedSatyr** [CodePen/CodePen-Bug-Reporting-Only#174]
I've tried these pages when uploaded to sites with SSL certificates. When quick-add for jQuery is used, it adds this link to the page's code when the pen is exported via .zip:

`<script` src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js'>

Please update this link to use HTTPS instead of HTTP. I.e.,

`<script` src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js'>

The current add results in a mixed content warning on multiple browsers when the site has an SSL certificate. It should read https.

**Comment by chriscoyier** [comment]
Verified. 

![img](http://d.pr/i/n0DR/29pBR9yu+)

**Comment by CharmedSatyr** [comment]
Thanks!

**Comment by quezo** [comment]
Just released a fix for this. HTTPS everything!
