### ISSUE TITLE
Opening a link with mousewheel

### ISSUE THREAD

**Issue by Mamboleoo** [CodePen/CodePen-Bug-Reporting-Only#177]
Hi,
I'm a huge fan of opening all my links with my mousewheel (to open them in new tabs).

But on the details view of a pen, I can't do that if I click on the name of user that commented the pen. The page redirects itself instead of opening a tab :(

![errormousewheel](https://cloud.githubusercontent.com/assets/6048794/14203372/e4f5c91a-f7fd-11e5-9ea5-7951f786fa8b.jpg)

Btw, this issue appears only when clicking on the name, not the picture.

**Comment by alexzaworski** [comment]
+1, I've hit this as well. I'm guessing it's because of the double-click-to-add-to-comment dealio.

**Comment by yukulele** [comment]
+1

**Comment by chriscoyier** [comment]
Changing this up! After our next deploy, your mousewheel should be happy again. The @usernames will have a different functionality. SINGLE clicks on those will insert their username into the comment area (can't be used to get to their profile at all). If that ends up annoying, we can go back to double clicks there , and this issue will still be fixed.

**Comment by alexzaworski** [comment]
I obviously don't speak for everyone but that seems like a weird solution to me. The problem with the mousewheel thing is that it broke default browser functionality— doesn't this break it even further? 

What if it were left generally as-is but only functioned while the comment box was focused? I suppose that causes issues if you want to *begin* a comment by adding someone's username though (scroll all the way down to the comment box, focus it, scroll up, click name... gross). Reply button, maybe? 

Definitely a tough one to crack but I would guess that for most people when clicking text styled like a link the expectation is that it behaves like one.

**Comment by chriscoyier** [comment]
the "styled like a link" part behaves exactly like a link. It's just the gray @username part that has the click-to-add functionality.

**Comment by alexzaworski** [comment]
Gotcha-- makes sense. Appreciate the clarification.
