### ISSUE TITLE
When searching someone else's Pens, searching again searches all of CodePen

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#178]
Like so:

![hhbmdtznsn](https://cloud.githubusercontent.com/assets/8040471/14212113/3699ecd2-f7e6-11e5-8cd9-4450ce772478.gif)

This *used* to be an issue when searching your own Pens, but that got fixed a few months ago:

![dwx0lrlhvl](https://cloud.githubusercontent.com/assets/8040471/14212135/4407d2c6-f7e6-11e5-8622-1432e0217044.gif)

**Comment by mariemosley** [comment]
We've moved this to our [Known Issues trello board](https://trello.com/c/0P6c0RO3/15-search-within-a-member-s-profile-only-works-once-a-second-search-will-search-all-of-codepen). Thanks for taking the time to report it!
