### ISSUE TITLE
Debug pens can almost validate

### ISSUE THREAD

**Issue by jonathantneal** [CodePen/CodePen-Bug-Reporting-Only#179]
CodePen pens in [debug view](https://blog.codepen.io/documentation/views/debug-view/) are nearly perfect for use with an HTML validator. There are 2 minor errors preventing the validation of a page. Example:

https://validator.w3.org/nu/?doc=http://s.codepen.io/chriscoyier/debug/eGcLw

I looked into it so that I could also propose a few solutions.

1. Might the older `<meta name="google" value="notranslate">` tag be retired for the HTML5 [`[translate]` attribute](https://www.w3.org/International/questions/qa-translate-flag.en) or the [`X-Robots-Tag` HTTP header](https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag#valid-indexing--serving-directives)?
2. Might the `X-UA-Compatible` HTTP header be updated to the value `IE=edge` from `IE=Edge,chrome=1`, as Chrome Frame was retired in February of 2014 and is discouraged from use?

> If you have Chrome Frame installed, please uninstall it. It is no longer supported or updated.
> — [Google](https://www.chromium.org/developers/how-tos/chrome-frame-getting-started)

**Comment by quezo** [comment]
Made a tiny big of headway here. Added the new notranslate tag to the HTML instead of in a meta tag. Header fix to come.

**Comment by mariemosley** [comment]
We're still working on this one! We've moved it to our [Known Issues trello board](https://trello.com/c/odQ5d46W/13-debug-view-validation). Thanks for letting us know 😄
