### ISSUE TITLE
Ads sometimes display as first Pen in showcase

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#18]
Totally not sure what causes it, but I was able to reproduce *sometimes* (30%?) by doing the following:

1. Go to CodePen home
2. Go to my profile
3. Go to showcase
4. Click organize showcase
5. Go back

![capture](https://cloud.githubusercontent.com/assets/8040471/11356855/7e1494a8-9216-11e5-984b-2699fe48e6d6.PNG)

I'm 99.999% sure this is the same bug you guys have been seeing with iframes in general but in case it helps at all I figured I'd submit.

**Comment by alexzaworski** [comment]
I had some more time to poke around with this today, if I recall correctly (can't find the old issue since the repo isn't available) your fix was to add a title attribute to all iframes. The large one at the top of the showcase uses data-title instead of title— is that causing the issue?

**Comment by chriscoyier** [comment]
The attempted fix was to apply a unique `name` attribute to all iframes, but we did that and it still happens a little bit. It seems like less often, but still sometimes. Good catch on the feature pen in the showcase missing that! I can fix that.

Such a sucky weird Chrome bug. It even happens on our support (Wufoo) form sometimes.

![screen shot 2015-11-26 at 8 33 35 am](https://cloud.githubusercontent.com/assets/69156/11460707/be78ab3a-96bf-11e5-8d0d-d98a43def870.png)
