### ISSUE TITLE
Account settings won't save

### ISSUE THREAD

**Issue by SWBennett06** [CodePen/CodePen-Bug-Reporting-Only#180]
At https://codepen.io/[USERNAME]/settings/, hitting 'Save All Settings' triggers a refresh but does not save any changed settings. This problem recurs in each settings tab.

Possibly unrelated, but the console shows: 
`GET https://d3ivh7uhyefd94.cloudfront.net/assets/settings/save/pages/editor_index-c4aa39329383806441e93f7917bdb9d3.js 503 (Service Unavailable)`

**Comment by quezo** [comment]
We caused some problems moving to a CDN over the weekend. You'll be able to edit and save your settings again. Thanks for reporting.
