### ISSUE TITLE
Job Markdown Preview Broken

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#182]
We're replacing this soon-ish I hope, but it should be fixed in the meantime:

![screen shot 2016-04-03 at 10 44 26 am](https://cloud.githubusercontent.com/assets/69156/14236261/72d99066-f9c7-11e5-98d1-44c4d77d11ec.png)

**Comment by rachsmithcodes** [comment]
preview works on live site - I get https related cross origin errors on local dev. Is that where you're seeing the error @chriscoyier, on your local?

**Comment by rachsmithcodes** [comment]
the local fix for this is to visit the boomerang url it is trying to load in URL and "advance to site" despite busted certificate. Then the preview will load.
