### ISSUE TITLE
postcss-transform-shortcut addon for postcss is broken

### ISSUE THREAD

**Issue by OttoRobotto** [CodePen/CodePen-Bug-Reporting-Only#183]
I am receiving an error when I try to import the postcss-transform-shortcut addon to an empty css pen file. The other settings I have set in css settings are `CSS Base: NORMALIZE` and `Vendor Prefixing: AUTOPREFIXER`

![screenshot from 2016-04-05 12 13 35](https://cloud.githubusercontent.com/assets/4759404/14278432/fc0d0c1c-fb27-11e5-95f4-eb5ab3d42229.png)

**Comment by chriscoyier** [comment]
Reduced test case on this seems worrking:

http://codepen.io/chriscoyier/pen/a372a4946a57753548db10ad42e05c8f

That error you are seeing is a bummer it's showing on line 1 instead of where the real error is, but looks like it's probably unrelated to this plugin specifically.
