### ISSUE TITLE
`Save` button on the Post editor is on a mission to break out of its container

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#185]
And it's doing a decent job:

![screen shot 2016-04-08 at 10 59 06 am](https://cloud.githubusercontent.com/assets/8040471/14392943/fd394cf6-fd78-11e5-8bab-740a4684fad4.png)

**Comment by chriscoyier** [comment]
Good catch! Some styles leaking from higher up were hurting us there.
