### ISSUE TITLE
Question mark tool tips not working on iPad

### ISSUE THREAD

**Issue by zastrow** [CodePen/CodePen-Bug-Reporting-Only#187]
I was working on a Pen on my iPad and opened the settings. I was curious what the question marks icons said, assuming they would display a tools tip with instructions. Instead nothing happened or the touch was captured by the nearby `label`, triggering a drop down instead.

To replicate:
1. Open a Pen on an iPad (9.7 inch iPad Air was used to discover this issue)
2. Select Settings
3. Press any of the question mark icons, e.g. the on next to "HTML Preprocessor"

![image](https://cloud.githubusercontent.com/assets/1128391/14406745/5360085c-fe7f-11e5-9208-9006f45ce072.png)

**Comment by chriscoyier** [comment]
Good catch! I'm not even 100% sure what the problem was, but messing with the event delegation a bit I was able to get it working. Will be out in next deploy.
