### ISSUE TITLE
->NEWBIE<-Can I swap between editing 2 html files?

### ISSUE THREAD

**Issue by Orange8ruce** [CodePen/CodePen-Bug-Reporting-Only#188]
I checked documentation, but I also overlook stuff.  Experimented around for half hour, no luck.

I have my index html in the editor and my css in its editor.  I uploaded two additional html files into the other section of assets and even clicked to get their new hosted links and updated that in my index.html.  

BUT, I would like to switch from editing my index.html to another of my other html files.  I am not using the JS editor, and I thought I could edit within that space but haven't figured it out.

please help the clueless.

http://codepen.io/Orange8ruce/pen/grvOQx

**Comment by mariemosley** [comment]
You can edit any of your text-based asset files in your Asset manager at: http://codepen.io/you/assets/
Thanks for going PRO!
