### ISSUE TITLE
Forcing https on a pen

### ISSUE THREAD

**Issue by positlabs** [CodePen/CodePen-Bug-Reporting-Only#189]
Some pens use features like `getUserMedia` that require https in order to run. Linking directly to the https pen works fine, but the site defaults to http. Adding an https checkbox to the pen settings would be one possible solution. What do you think?

http://codepen.io/positlabs/pen/bpLYjY
https://codepen.io/positlabs/pen/bpLYjY

**Comment by chriscoyier** [comment]
Moving this here: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/32#issuecomment-212108846
