### ISSUE TITLE
CodePen doesn't see images from Facebook

### ISSUE THREAD

**Issue by wolosowski** [CodePen/CodePen-Bug-Reporting-Only#190]
![screenshot_2](https://cloud.githubusercontent.com/assets/18266862/14441908/d4cd71c4-003f-11e6-9e14-8123fc68ea14.png)

**Comment by mariemosley** [comment]
We've seen this happen with ad/content-blocking browser extensions. If you have something like that on your browser, please give it a try in an incognito window and see if that helps. If it doesn't, can you check your browser's console for errors, and send us a screenshot to support@codepen.io? That can help us track down the problem for you :)
