### ISSUE TITLE
Typescript not checking for types

### ISSUE THREAD

**Issue by RavingAPD** [CodePen/CodePen-Bug-Reporting-Only#191]
I just tried out typescript, and it's not checking the types.
This code:
```javascript
function greeter(person: string) {
    return "Hello, " + person;
}

var user = [0, 1, 2];

document.body.innerHTML = greeter(user); 
```
Does not throw an error. And I think we can all agree that an array of numbers is not a string :P

**Comment by chriscoyier** [comment]
This is the same as what the Typescript playground does:

![screen shot 2016-04-19 at 4 58 49 pm](https://cloud.githubusercontent.com/assets/69156/14656921/08f76188-0650-11e6-94cc-ba37d34ba5e6.png)

I'm sure there is a lot more we can do eventually with Typescript, but for now we just do totally default behavior.
