### ISSUE TITLE
URL of the "Check out Popular Pens" link on the "Hello" page is incorrect

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#192]
http://codepen.io/hello

Currently goes to `http://codepen.io/popular` which directs back to the home page.

**Comment by mariemosley** [comment]
correction going up shortly

**Comment by alexzaworski** [comment]
Looks like it's already fixed up :smile: 

Semi-related, have you guys considered dropping a link to the editor tour on that page?

**Comment by chriscoyier** [comment]
Good idea, I'll look at doing that with a minor refresh of that page.
