### ISSUE TITLE
Nothing is displayed if a request for a Collection 404s

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#193]
Preeeetty spooooky 👻

![screen shot 2016-04-12 at 4 46 48 pm](https://cloud.githubusercontent.com/assets/8040471/14478951/f2a5608c-00ce-11e6-83fd-2d94e90d5521.png)

edit: title isn't *quite* accurate since requesting a literal collection (eg `codepen.io/collection/asdasdasd`) that 404s is fine— it's making a request to the collection**s** url that's goofy.

**Comment by quezo** [comment]
Thanks for the heads up here. It's fixed!
