### ISSUE TITLE
It says 'You forked ...' instead of 'You created ...' in recent activity page

### ISSUE THREAD

**Issue by scriptype** [CodePen/CodePen-Bug-Reporting-Only#195]
After creating a new pen, I'm seeing `You forked the [pen-name]` in the recent activity page. This was rightly `You created the [pen-name]` not so long ago, as far as I remember.

![screen shot 2016-04-14 at 16 10 26](https://cloud.githubusercontent.com/assets/5516876/14529157/e5ccbb92-025b-11e6-97ba-fcb9a842d393.png)

For example I've recently created the [pen](http://codepen.io/pavlovsk/pen/XdEgYy) in this screenshot. I didn't fork it and it's not on my forked pens list.

**Comment by quezo** [comment]
@scriptype Thanks for reporting this bug. We just released a fix for it.
