### ISSUE TITLE
URLs are syntax highlighted incorrectly all over the blog

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#196]
Not sure if there's an easy way to fix this on your end but it's fairly distracting:

<img width="756" alt="screen shot 2016-04-14 at 10 24 17 am" src="https://cloud.githubusercontent.com/assets/8040471/14537277/20d196c6-022b-11e6-8fd0-c5b7d2bf6a95.png">

**Comment by chriscoyier** [comment]
Fixed!

**Comment by alexzaworski** [comment]
Thanks for the quick fix :+1:
