### ISSUE TITLE
popular pens sorting wrong

### ISSUE THREAD

**Issue by pixelass** [CodePen/CodePen-Bug-Reporting-Only#197]
My most popular pen (Marvel logo) does not show up under "popular".

I noticed this about a week ago but it I' m not sure since when this changed.
Look at the screenshots to compare the stats of  page 1. (my "now" most popular pen is not really popular)

Screenshots:   
1. Page 1 of my popular pens
2. stats for the marvel pen

<img width="1281" alt="screen shot 2016-04-15 at 12 50 29 pm" src="https://cloud.githubusercontent.com/assets/1148334/14559437/fca4c884-0308-11e6-8c8c-83bd8afb1003.png">

<img width="1228" alt="screen shot 2016-04-15 at 12 50 59 pm" src="https://cloud.githubusercontent.com/assets/1148334/14559439/0265fdc4-0309-11e6-9491-431d50ecb70a.png">

**Comment by chriscoyier** [comment]
We made some changes to the popularity algorithm this week. The intention was to fix the Popular Tab, but it had futher-reaching implications. There will still be changes to your profile page as well, but probably not as drastic. @tsabat might have more details.

**Comment by tsabat** [comment]
hi gregor.  We shifted the way we calculate popularity and it is different for your profile vs the home page.  A popularity recalculation happens when your pen gets a view from someone else.  So, if you were to view your marvel pen in incognito, it'd probably jump into the correct ranking for popularity on your home page.

**Comment by rachsmithcodes** [comment]
closing this as we've resolved the profile popularity algorithm (and Gregor's Marvel logo is back at no. 1)

**Comment by pixelass** [comment]
I noticed... YAY.. 

@tsabat sorry I missed that message
