### ISSUE TITLE
duplicates in followers

### ISSUE THREAD

**Issue by pixelass** [CodePen/CodePen-Bug-Reporting-Only#198]
I have noticed this for a while and it became very obvious when playing with the CP-API.

On every other page a duplicate follower appears.

See screenshots (page 1 & 2): Sam Eureka (column 2 - middle & last)

<img width="1248" alt="screen shot 2016-04-15 at 12 57 20 pm" src="https://cloud.githubusercontent.com/assets/1148334/14559573/fb991b24-0309-11e6-9c23-756a74b11ff4.png">

<img width="1229" alt="screen shot 2016-04-15 at 12 57 26 pm" src="https://cloud.githubusercontent.com/assets/1148334/14559577/06c51836-030a-11e6-9f00-269813a25100.png">

**Comment by quezo** [comment]
@pixelass I'm having a tough time recreating the bug. What API are you referring to? That may help me test it. Thanks!

**Comment by pixelass** [comment]
@quezo I played around with Nate Wiley's "unofficial" Codepen API. I noticed it back then because it got very obvious when comparing multiple pages. At first I thought it was a bug in the API but when I compared the results to codepen I saw that every `nth` follower was a duplicate (see images in OP: page,1 & page 2)

 That is when I first noticed it. But this happens in codepen itself.
It is very hard to track because you have to rely on you eyesight and memory to spot those duplicates. I think looking at the data (AJAX response) will help a lot. just spit out a few pages and look for the duplicates.  Ping me back if you need more info/help on this.

The position changes with every new follower: currently spotted this one:  
![duplicates](https://cloud.githubusercontent.com/assets/1148334/15034678/49fea59a-1278-11e6-9b52-d65eb58bc255.gif)

**Comment by mariemosley** [comment]
Still digging into this one. We've moved it to our [Known Issues trello board](https://trello.com/c/0mE4VgnF/12-duplicated-followers). Thanks for reporting & documenting it so well for us!
