### ISSUE TITLE
Pressing backspace in the editors on Edge Mobile does not delete chars

### ISSUE THREAD

**Issue by peebeebee** [CodePen/CodePen-Bug-Reporting-Only#199]
When I press delete in one of the editors (js/css/html) on Edge Mobile (Lumia 930) it does not delete a character, but puts a bullet point in place.

**Comment by chriscoyier** [comment]
Can you try this out on the editor at http://codemirror.net/ and let us know if it happens there too? If it does, it's a CodeMirror thing. If not, it's us, and I can re-open.

**Comment by peebeebee** [comment]
Yups, codemirror thing it is.
