### ISSUE TITLE
Source code wiped out twice

### ISSUE THREAD

**Issue by thegleb** [CodePen/CodePen-Bug-Reporting-Only#201]
Codepen noob here. I was collaborating on a codepen with someone and in the blink of an eye the code disappeared (HTML, CSS, and JS at the same time). URL stayed the same, so it wasn't someone hitting Command-P accidentally. There was no way to recover. This happened twice this week for me, on separate occasions.

Is there a shortcut that nukes the codepen when pressed, but keeps the URL the same? Else this feels like a bug.

**Comment by chriscoyier** [comment]
Uh oh, sorry you were having trouble!

There definitely isn't a "a shortcut that nukes the codepen when pressed". 

So it sounds like you were using Collab Mode? And it happened more than once? Where they different Pens or the same one? Were you the owner of the Pen, or were they? If you were the owner, and it ever happens again, I'd suggest leaving Collab Mode as a precaution, so the Pen doesn't accidently get saved with no code, as that really would destroy the code. 

This doesn't seem to be a widespread issue, or one that I've ever heard reported before, so it's worth figuring out the exact specifics of what is going on here. Those questions above are a good start.

**Comment by chriscoyier** [comment]
Hit me up with details and I can re-open as needed.

**Comment by thegleb** [comment]
@chriscoyier just saw this - this was Collab Mode. I was one of the collaborators. They were different Pens, on different days.
