### ISSUE TITLE
When landing on blog post page scroll position is set to comment box

### ISSUE THREAD

**Issue by Imagine-Programming** [CodePen/CodePen-Bug-Reporting-Only#202]
When you load a blog post page, any post page, CodePen scrolls the view to the comment box. You then have to scroll back up to start reading the content of the post.

I would love to add a screenshot, but I think it would be redundant. 

My apologies if this is a known issue, however I could not find an issue in here regarding this topic.

**Comment by jakealbaugh** [comment]
thanks, @Imagine-Programming
