### ISSUE TITLE
Spacing issue on Professor Mode Footer

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#203]
https://twitter.com/MateiCopot/status/721840399967469570/photo/1

**Comment by towc** [comment]
Not sure if this should change depending on user agent and viewports, but all you need is ~~love~~ this apparently

`#student-count-text {
  padding: 6px 0 6px 0;
}`

**Comment by chriscoyier** [comment]
Will be fixed in next deploy, thanks!
