### ISSUE TITLE
Profile Background Pens use HTTP, so break on HTTPS

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#204]
https://twitter.com/tjramage/status/722499046863187969

**Comment by tjramage** [comment]
@chriscoyier Awesome – didn't realise you guys had a GitHub issue tracker! 👍

**Comment by jakealbaugh** [comment]
going out in next deployment

**Comment by jakealbaugh** [comment]
thanks, @tjramage

**Comment by tjramage** [comment]
@jakealbaugh – no problem! Just tested and it's all working fine 👍
