### ISSUE TITLE
Prefill Editors - Adding Tags array returns 500-ISE

### ISSUE THREAD

**Issue by TheBrenny** [CodePen/CodePen-Bug-Reporting-Only#205]
When submitting data to prefill the editors of CodePen, submitting a JSON Stringified of the "All the JSON Options" ([from the documentation](https://blog.codepen.io/documentation/api/prefill/)) you are returned with a *500 Internal Server Error*.

After fiddling around with which options I use, it seems to be that the tags array doesn't get stringified by the `JSON.stringify` method.

This breaks the POST received by CodePen.

**Comment by quezo** [comment]
Bug fix released.
