### ISSUE TITLE
Podcast player invisible in its own window

### ISSUE THREAD

**Issue by jasesmith** [CodePen/CodePen-Bug-Reporting-Only#207]
Hi there,

Not sure if this is the right place to post this issue, but the Codepen Radio audio player which opens when clicking "Play in new window" is not visible without altering the element.style property for visibility.

![image](https://cloud.githubusercontent.com/assets/1619521/14755672/3b50c158-08a1-11e6-81b5-7884da4dd788.png)

![image](https://cloud.githubusercontent.com/assets/1619521/14755598/b97caa84-08a0-11e6-817d-1903be76dcd0.png)

![image](https://cloud.githubusercontent.com/assets/1619521/14755650/182dd35a-08a1-11e6-8b6a-92aaa9b7a1e2.png)

**Comment by chriscoyier** [comment]
Good catch!

I got this one fixed. 

I had to fix it in kind of a crappy way by altering a plugin though. The Blubrry WordPress plugin we use to do postcasting doesn't really have a "just use normal HTML5 audio element" player option, so we just block the loading of the MediaElements.js loader and make CSS adjustments. 

This particular adjustment had to be done in the plugin code itself, so it's prone to breakage. If it breaks again, we'll look for a nicer and more permanent way to display the shows.
