### ISSUE TITLE
m3u8 Streaming

### ISSUE THREAD

**Issue by rickymartinss** [CodePen/CodePen-Bug-Reporting-Only#208]
here i found ur test url http://codepen.io/Viblast/pen/vLvraj

I am editing it current source //cdn3.viblast.com/streams/hls/airshow/playlist.m3u8 replaced with mine http://cbcsportshd1-f.akamaihd.net/i/cbcsports_3@31222/master.m3u8 but when i opened it on my website it didnot function properly and the stream didnot start. please help as i want to embed m3u8 stream on my website

thnks

**Comment by mariemosley** [comment]
Hi! This repo is for reporting bugs in [CodePen](http://www.codepen.io). I'm sorry, but we're not able to help you with your website. If you're having trouble with using CodePen, please contact our support at support@codepen.io
