### ISSUE TITLE
CSS class "alert" doesn't appear in CodePen screenshots

### ISSUE THREAD

**Issue by jakedeichert** [CodePen/CodePen-Bug-Reporting-Only#209]
When using a css class called `alert`, elements using that class do not appear in the generated screenshot.

Here's a simple demo that shows this: http://codepen.io/jakedeichert/pen/MyBZbE?editors=1100

## This is what the demo looks like
![screen shot 2016-04-23 at 4 38 50 pm](https://cloud.githubusercontent.com/assets/1631044/14763877/e48ae2fa-0971-11e6-9587-d13ce70d465f.png)

## And here's the improperly generated screenshot
![screen shot 2016-04-23 at 4 39 15 pm](https://cloud.githubusercontent.com/assets/1631044/14763880/f23ea0b2-0971-11e6-8d93-af8880a84c75.png)

It took me about an hour to figure out why 6 of my pens had screenshots with no css at all. I finally determined it was the `alert` class (I was playing around making notice/alert styled boxes and `alert` was the only class I had which was the reason there was no css in the screenshot).

## Possible reasons

1. According to your docs, you [strip certain strings](https://blog.codepen.io/documentation/editor/things-we-strip/) and this could be the reason?

2. PhantomJS may have an issue with that class name?

## Possible solution

I understand if you must strip `alert` from all code, however, you could improve the docs page regarding this to be a little more clear.

> ALERT(), CONFIRM(), AND PROMPT() DIALOGS
> These create popups, so we block them from the grid view.

Maybe instead specify that you remove all string instances of `alert`?

Unless this really just is a bug and not intended behaviour.

**Comment by tholman** [comment]
Ahh, this makes sense. Yeah, the string alert is fully cut out when taking screenshots (can't leave it in html, incase someone puts it in a script tag or something) ... I'll update the docs!

Sorry about the confusion!

**Comment by jakedeichert** [comment]
No problem, thanks! I'll let you close this whenever you want.
