### ISSUE TITLE
Blog posts: syntax highlighting not working

### ISSUE THREAD

**Issue by rzahniser** [CodePen/CodePen-Bug-Reporting-Only#211]
According to [this page](http://codepen.io/blogging/), blog posts ought to support syntax highlighting. But when I look at one (either [my own post](http://codepen.io/rzahniser/post/maze3) or [an example post](http://codepen.io/chriscoyier/post/some-mini-sass-mixins-i-like)), I see uncolored text and an extra tab at the start of the code block. Looking at the HTML, I see just `<pre><code class="javascript">`, but no highlighting spans.

I thought this might just mean my syntax highlighting user preferences weren't set up right (since it sounds like the same highlighting is supposed to be applied to everything? Not sure if that's just pens). But changing and saving my settings didn't fix the problem.

Pages in the official CodePen blog [highlight properly](https://blog.codepen.io/documentation/editor/code-commenting/), but this seems to be done by an extra script "blog.codepen.io/wp-content/themes/codepen3/js/blog-ck.js" that isn't present in user blog posts.

**Comment by mariemosley** [comment]
Can you share a screenshot of what you see, and let us know your browser type & version?

**Comment by rzahniser** [comment]
Here's a screenshot and a view-source. I'm was using Chrome
50.0.2661.86, which is the current version, but I checked and the same
problem appears in Safari and Firefox, so I'm guessing the problem is
in what is being served up rather than in my browser. I'm on a Retina
Macbook, Mac OS 10.11, in case that helps.

-Russell

**Comment by rachsmithcodes** [comment]
fix for this going out this morning!
