### ISSUE TITLE
Incorrect Pen count in New Follower emails

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#212]
I just got a new follower email and it said that the user had created 187 Pens when in reality they had 0 <a href="http://codepen.io/johngrpads/">(this dude).</a>

Not sure if it's counting private Pens in that total (though that would be a bug in and of itself, I think?).

I can provide screenshots of the email if that's helpful.

**Comment by mariemosley** [comment]
That tally includes all of the members' Pens, including forks.

**Comment by alexzaworski** [comment]
Didn't even consider forks, thanks Marie! 👍
