### ISSUE TITLE
Authentication Required popup when browsing search results

### ISSUE THREAD

**Issue by racedale** [CodePen/CodePen-Bug-Reporting-Only#213]
When browsing [search results](http://codepen.io/search/pens/?limit=all&page=4&q=multi+select) I am getting an Authentication Required popup that I have to cancel out of twice to be able to continue browsing.  
I think at least one of the pens on that page is doing something weird

**Comment by tholman** [comment]
There's really not much we can do about this... a pen is referencing an asset (could be a script, could be an image) that is protected on another server. Super annoying :/

We're keeping an eye on potential solutions though... will get there!
