### ISSUE TITLE
Viewport height of the pen iframe overflows and creates scrolling on mobile (< 400px)

### ISSUE THREAD

**Issue by marcofugaro** [CodePen/CodePen-Bug-Reporting-Only#214]
Happens when you set something 100% the height of the window, either with vh or %. [Here is a pen for reference](http://codepen.io/marco_fugaro/pen/reqOmV).

I found the css rule which breaks it, disabling this fixes it. 

![Media query](http://i.imgur.com/UPkxCBY.png)

The original value is `calc(100% - 69px)`, the 7px are what makes the difference.

**Comment by chriscoyier** [comment]
So this is on Full Page View? like http://codepen.io/marco_fugaro/full/reqOmV/ ?

**Comment by marcofugaro** [comment]
Full Page view and Editor view, below 400px.

Tested in Chrome and Chrome for Android.

**Comment by chriscoyier** [comment]
Nice catch! There was some a `min-height` problem preventing the header from going down to that desired 62px. Will be fixed in next deploy.
