### ISSUE TITLE
Previewer for pens breaks the image

### ISSUE THREAD

**Issue by cassidoo** [CodePen/CodePen-Bug-Reporting-Only#216]
I noticed that my pen here: http://codepen.io/cassidoo/pen/eZPmMe

Was being rendered like this in the preview:
![image](https://cloud.githubusercontent.com/assets/1454517/14903131/10383372-0d6d-11e6-86ba-f74cc1908a1b.png)

My project doesn't ever actually look like that (I tried many screens and browsers).  Does the action that renders pens not support some things, like flexbox or something, when it's being produced?  Not sure what else it might be.

Thanks!

**Comment by chriscoyier** [comment]
URL to image for this pen:
http://codepen.io/cassidoo/pen/eZPmMe/image/large.png

Which at the moment resolves to:
http://s3-us-west-2.amazonaws.com/i.cdpn.io/242759.eZPmMe.f7072318-71d8-4f7d-900c-52cf6f23bfe2.png

![242759 ezpmme f7072318-71d8-4f7d-900c-52cf6f23bfe2](https://cloud.githubusercontent.com/assets/69156/14922265/437e58a8-0dfc-11e6-990f-60ed8e198d1a.png)

It does kinda look like a Flexbox problem. I'd recommend turning on Autoprefixer in that Pen's setting and re-saving it. That'll get you deeper browser support for the flexbox you are using AND probably make the screenshot better.

Reduced test case for prefixed flexbox: 
http://codepen.io/chriscoyier/pen/77b22b4e2e8d3cbce1b2fe63545b7d7a
http://codepen.io/chriscoyier/pen/77b22b4e2e8d3cbce1b2fe63545b7d7a/image/large.png

Seems to work fine.

**Comment by cassidoo** [comment]
@chriscoyier That didn't work, unfortunately.  Unless it takes a little bit for a new screenshot to load?

**Comment by rachsmithcodes** [comment]
hey @cassidoo screenshot updates go in to a queue after the pen is saved, so it can take a little while for the image to update.

**Comment by chriscoyier** [comment]
Looks fixed ;)

**Comment by cassidoo** [comment]
Thank you both. <3
