### ISSUE TITLE
Oceanic Dark: Line Numbers

### ISSUE THREAD

**Issue by zslabs** [CodePen/CodePen-Bug-Reporting-Only#218]
Hey all!

Just wanted to pass along a bit of a color issue I noted with the line numbers using the "Oceanic Dark" theme:

![codepen-line-numbers](https://cloud.githubusercontent.com/assets/1018402/14929624/71213e94-0e2c-11e6-8180-ff5cd766dd15.png)

They're pretty hard to make out and think they'd be better off being a slightly opaque white color. Thanks!

**Comment by chriscoyier** [comment]
oo yeah that's far too dark. We'll lighten that up in the next deploy.

**Comment by zslabs** [comment]
Appreciate it Chris! As always, thanks for CodePen!
