### ISSUE TITLE
:not() issue

### ISSUE THREAD

**Issue by julmot** [CodePen/CodePen-Bug-Reporting-Only#219]
Having the following CSS:
```
.context :not(p) {
  background: #f1c40f;
}
```

And then clicking the "Tidy" button will generate

```
.context:not(p) {
  background: #f1c40f;
}
```

(removing the blank between `.context` and `:not()`). 
This will cause a different behavior, which is not as expected.

**Comment by chriscoyier** [comment]
Looks like this is [a bug in the library](https://github.com/beautify-web/js-beautify/issues/883) so we can track it there. 

The workaround would be to make it:

```
.context *:not(p) {
  background: #f1c40f;
}
```

... which is exactly the same and the library seems to maintain OK.
