### ISSUE TITLE
syntax highlight: global variable

### ISSUE THREAD

**Issue by yukulele** [CodePen/CodePen-Bug-Reporting-Only#22]
Glabal variables are displayed like undefined variables

In this example, `globaVariable` should be blue on line 4 and 11 (like `localVariable` on line 10):
![capture d ecran 2015-11-29 a 01 09 42](https://cloud.githubusercontent.com/assets/347244/11454679/e6145638-9635-11e5-8728-a3c6f7d7eaa8.png)

http://codepen.io/anon/pen/epqJVX?editors=001

**Comment by chriscoyier** [comment]
Moving this over to the CodeMirror repo: https://github.com/codemirror/CodeMirror/issues/3674
