### ISSUE TITLE
codepen scrolls way to the right after hitting enter

### ISSUE THREAD

**Issue by cjjugarap** [CodePen/CodePen-Bug-Reporting-Only#220]
I seem to be having a bug on codepen.  I'm trying to add my last `</div>` to complete my code but now it's scrolling wayyy to the right.

Here is the link:

[https://codepen.io/cjjugarap/pen/JXmQrK](url)

**Comment by mariemosley** [comment]
Can you let us know what is scrolling? Is it the whole page, the preview, or the editor panels? Screenshots or a screencast can really help, too.

**Comment by mariemosley** [comment]
If you're still having trouble with your Pen please email us at support@codepen.io and we'll help!
