### ISSUE TITLE
"Double-click names to add to comment" text is now outdated

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#221]
Since you guys updated the way click-to-add works in comments (great job by the way, much prefer the way things work now), the instruction text above the comment box is outdated:

<img width="830" alt="screen shot 2016-05-02 at 8 34 46 am" src="https://cloud.githubusercontent.com/assets/8040471/14958702/cb0ee774-1040-11e6-962e-abe4de2127b3.png">

**Comment by mariemosley** [comment]
fix going up shortly

**Comment by alexzaworski** [comment]
Thanks Marie!
