### ISSUE TITLE
[typescript] Type casting causes compile error

### ISSUE THREAD

**Issue by serkanyersen** [CodePen/CodePen-Bug-Reporting-Only#225]
Following code fails to compile

```typescript
document.addEventListener('click', (e: MouseEvent) => {
  let target = <HTMLElement>e.target;
  if (target.id === 'myButton') {
    alert('clicked');
  }
});
```

if you remove ` <HTMLElement>` it works fine, however if you copy paste this code in other TypeScript editors without type casting, you receive a warning because event target is not an HTML Element on TypeScript and you need to cast it to specific element type you need.

----

Error you receive is not a typescript error, it's a syntax error
![screen shot 2016-05-06 at 16 59 34](https://cloud.githubusercontent.com/assets/30582/15088672/f1c25072-13ab-11e6-9b54-47d531838308.PNG)

So preprocessor is probably altering the code before compile, most possibly poor escaping.

**Comment by chriscoyier** [comment]
Seems like definitely a bug on our end. Typescript playground compiles it fine:

![screen shot 2016-05-14 at 8 11 19 pm](https://cloud.githubusercontent.com/assets/69156/15271458/11c36856-1a10-11e6-9852-7ee885e31a69.png)

**Comment by aaronbeall** [comment]
I'm not sure how CodePen compiles behind the scenes but in case it helps: when you are in JSX context you have to use `as` syntax to do a type assertion, since `<...>` syntax is ambiguous with element declarations.

**Comment by mariemosley** [comment]
We're moving this issue to our Known Issues trello board: https://trello.com/c/FpntmCwP/4-typescript Thank you for taking the time to report it!
