### ISSUE TITLE
.svg File Extension forces `viewBox` to `viewbox`

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#227]
.svg is broken:
http://codepen.io/chriscoyier/pen/95cdd9702bb868d88d3390e9b8a3ff0a.svg

.html is fine:
http://codepen.io/chriscoyier/pen/95cdd9702bb868d88d3390e9b8a3ff0a.html

**Comment by SaraSoueidan** [comment]
👍🏻

**Comment by chriscoyier** [comment]
Fixed this.

**Comment by chriscoyier** [comment]
(will go out later today in next deploy)

**Comment by SaraSoueidan** [comment]
Thank you!!
