### ISSUE TITLE
instanceof not working for prototypal or class inheritance

### ISSUE THREAD

**Issue by DotFreelance** [CodePen/CodePen-Bug-Reporting-Only#23]
I seem to have come across an issue where the JS editor, while using Babel, will not recognize something of the form:
```javascript
class GameConsole {
	constructor() {}
	turnOn() {}
}

class PS4 extends GameConsole {
	turnOn() {
		super.turnOn();
		console.log('On');
	}
}

console.log( PS4 instanceof GameConsole );       // false, should be true
```

and also seems to fail on:
```javascript
var GameConsole = function GameConsole() {};

GameConsole.prototype.turnOn = function turnOnGameConsole() {};

var PS4 = function PS4() {};

PS4.prototype = Object.create(GameConsole.prototype);

PS4.prototype.turnOn = function turnOnPS4() {
	GameConsole.turnOn.call(this);
	PS4.playSound('beep');
}

console.log( PS4 instanceof GameConsole );      // false, should be true
```

The only way to get the console to report `true` is to use `PS4.prototype instanceof GameConsole` for either example.

I don't think this is intentional, or to spec. I suspect it's a minor issue, either way. Thanks for your time!

**Comment by chriscoyier** [comment]
Does this seem like an error in Babel or an error in how CodePen is processing Babel. Like if you run Babel locally, is it correct? Can you share how you have Babel configured locally so it works?

I can re-open this if it seems like a CodePen-specific thing we could fix.
