### ISSUE TITLE
The "N" from "No File Chosen" is visible on the "Select Files" button on the asset uploader

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#230]
Only happens at some window widths. Using latest chrome on a mac.

![screen shot 2016-05-10 at 3 42 59 pm](https://cloud.githubusercontent.com/assets/8040471/15164801/fe573592-16c5-11e6-9fcb-eda74598b99e.png)

**Comment by mariemosley** [comment]
Can you let us know which window widths? Screencast of what I see (also latest Chrome/Mac): http://d.pr/v/13YrY

**Comment by alexzaworski** [comment]
So... this is super weird. Here's a gif of everything working *totally* fine when resizing with Chrome's device emulator thing:

![nv8ycppi9y](https://cloud.githubusercontent.com/assets/8040471/15186549/4b404b6e-1752-11e6-956a-8a31adf3b277.gif)

But here's a gif of it breaking when scaling the window normally:

![pcsvlxtjoj](https://cloud.githubusercontent.com/assets/8040471/15186615/9ae19178-1752-11e6-96a1-42c818232813.gif)

Here's a screenshot; it appears to break at 550px:

<img width="810" alt="screen shot 2016-05-11 at 8 27 09 am" src="https://cloud.githubusercontent.com/assets/8040471/15186639/ac068030-1752-11e6-93e7-f48ee79301cc.png">

All of these were in incognito windows with all plugins disabled.

**Comment by tholman** [comment]
Ok, should be fixed. Please open up again if its still there :)
