### ISSUE TITLE
Checkmark alignment on PRO features page

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#231]
<img width="1014" alt="screen shot 2016-05-11 at 8 38 20 am" src="https://cloud.githubusercontent.com/assets/8040471/15187022/3e3d9550-1754-11e6-8ce5-50704b2b8682.png">

Intentional? The indented ones have the same `sub-feature` wrapper as their titles to the left but I think the padding just makes them look off. Same with the sub-feature description text being slightly off-center:

<img width="931" alt="screen shot 2016-05-11 at 8 45 06 am" src="https://cloud.githubusercontent.com/assets/8040471/15187121/b69316a6-1754-11e6-88f1-1417b6ea6758.png">

**Comment by chriscoyier** [comment]
New branch dropping soon where this is fixed

**Comment by alexzaworski** [comment]
Hey was this ever actually resolved? Ended up on this page again today and noticed the checkmarks are still misaligned.

**Comment by chriscoyier** [comment]
It's on a branch that's slow to go out, but hopefully by the end of this week or early next
