### ISSUE TITLE
Wordpress Split View between HTML and Result doesn't work

### ISSUE THREAD

**Issue by StfBauer** [CodePen/CodePen-Bug-Reporting-Only#232]
I have the lastest wordpress plugin installed but somehow the rendering in mixed view doesn't work.
When I switch to html only it works.
When I switch to result view it wooks too but not both together.

**Comment by chriscoyier** [comment]
We're gonna need a little bit more information to diagnose this. Got a live URL or screenshot or something? I can re-open once it's a confirmed bug.
