### ISSUE TITLE
unconsistent email title-content and general email concerns

### ISSUE THREAD

**Issue by towc** [CodePen/CodePen-Bug-Reporting-Only#237]
Currently, when a user hearts a pen and the email notifications are turned on, the owner of the pen receives an email with a title of:
`<user> **loved** your **P**en <pen-name>`
and a body of
`<user> **hearted** your **p**en <pen-name>...`

I think it would also be more sensible to send emails concerning a pen as responses to previous emails sent on that pen, this way the user still gets all the notifications needed just by looking at the email list with the email preview, and their list doesn't get flooded.
I mean, I always love it when my email is flooded with love from the community, but ya know :)

Another thing is also that it could be sometimes easier if you were able to see other statistics, such as how many comments are there on a pen when a new comment comes, or the amount of views when it got hearted, or how many followers you now have when someone follows you. Shouldn't require too much processing power for your servers

Have a good day :D

**Comment by mariemosley** [comment]
Email copy correction going up shortly. I've also made a note of your ideas, thanks :)
