### ISSUE TITLE
Page wrapper on style guide no longer constrains width

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#238]
Screenshot as of today:

![capture](https://cloud.githubusercontent.com/assets/8040471/15276199/f5f74d96-1a95-11e6-83f1-f0e36ffb5ab1.PNG)

Archive.org screenshot from a while back:

![capture1](https://cloud.githubusercontent.com/assets/8040471/15276205/1554acb0-1a96-11e6-80c1-3aef05672eb0.PNG)

**Comment by rachsmithcodes** [comment]
added the new width wrapping class to the styleguide
