### ISSUE TITLE
Profiles are erroring out

### ISSUE THREAD

**Issue by artemist** [CodePen/CodePen-Bug-Reporting-Only#24]
Hi All! Hope you're having a nice Sunday. Just to let you know in case it's not on your radar: profiles are erroring out on at least chrome and firefox on Mac. Not just mine, I've checked several profiles for the past hour or so and the problem is persisting. I haven't upgraded my OS to El Capitan yet, though. Thanks!

<img width="1364" alt="screen shot 2015-11-29 at 5 05 13 pm" src="https://cloud.githubusercontent.com/assets/2281088/11461604/68b1db08-96bb-11e5-9726-77206b888c85.png">

**Comment by artemist** [comment]
nevermind, fixed!

**Comment by mariemosley** [comment]
Thanks Sarah :)
