### ISSUE TITLE
blog.copepen.io site width bug (Chrome 50, Android 6)

### ISSUE THREAD

**Issue by Crysinyan** [CodePen/CodePen-Bug-Reporting-Only#241]
I am having an issue with the site width on my phone.
Some specifics:

-  only concerns pages on blog.codepen.io
-  phone model: Sony Xperia Z5 Premium, it has a 4k screen if that's helpful to you.
-  os: Android 6.0, Marshmallow
-  browser 1: Chrome 50.0.2661.89
-  browser 2: Firefox 46.0.1
-  rotation : portrait
-  [link to video of bug](https://youtu.be/Dju7W-3tpxw)

In chrome the site extends to the right width only background as you can see in the video I linked.
Occationally after scrolling it will flicker and extend to the full with, but quickly return to it's former width again.

Same thing in Firefox.

after running the remote debugger I found that the problem is caused by this element.
`<nav class="header-chunk primary-nav fill-space priority-nav" id="secondary-primary-nav" style="overflow: visible;">`

switching style between {overflow: visible}, and {overflow: hidden},
which changes the width of the site momentarily, causing the browser to use this extended width even after the flicker occurs.

Now, I am not searching through millions of lines of javascript to try to find what changes this.
I did however get you guys a place to start, good luck :)

/Crysin out.

**Comment by chriscoyier** [comment]
Thanks! Hiding the ol' overflow seems to be doing the trick.
