### ISSUE TITLE
false alert for dead loop prediction

### ISSUE THREAD

**Issue by impfromliga** [CodePen/CodePen-Bug-Reporting-Only#242]
trying to pen Bresenham's Line algorithm, and see dead loop alert - false alert!
it happend when the line near to orthogonal

showcase: codepen.io/impfromliga/pen/PNvvpQ?editors=0010
!!! This code work fine when it run in native JS

I am guessing:
the codepen has false alarm on it's heuristic dead loop prediction!
though it comment that it report is aproximation...
but not everyone will introspect what's the matter =(

**Comment by chriscoyier** [comment]
Doesn't seem to be detecting any infinite loops for me. Perhaps you got it sorted out?

**Comment by impfromliga** [comment]
Nope. The bug still detect, when you try draw a vertical or horizontal line.

**Comment by chriscoyier** [comment]
You can peak at our script that works with this here: http://assets.codepen.io/assets/common/stopExecutionOnTimeout.js

The default values are:

```
START_MONITORING_AFTER:2e3,
STOP_ALL_MONITORING_TIMEOUT:5e3,
MAX_TIME_IN_LOOP_WO_EXIT:2200
```

You can adjust them (like at the top of your authored JavaScript), like:

```
window.CP.PenTimer.MAX_TIME_IN_LOOP_WO_EXIT = 10000;
```

This all works with the fact that we inject watcher functions into all your loops, which you can peak at by inspecting the JavaScript that goes into the demo itself:

![img](http://d.pr/i/18V9H/4hKPxuj2+)
