### ISSUE TITLE
Canvas tag suddenly stopped working

### ISSUE THREAD

**Issue by kirkeeide** [CodePen/CodePen-Bug-Reporting-Only#243]
Please take a look at this pen: http://codepen.io/kirkeeide/pen/wGLvBZ

It has two identical canvas tags in the HTML body, but only one of them works.

While renaming my canvas id it suddenly stopped working. I couldn't figure out what was wrong. Then I copy pasted the exact same tag from a local file om my computer and it somehow worked. The old tag still doesn't work however. 

You can try this out for yourself by commenting/uncommenting the tags.

**Comment by kirkeeide** [comment]
I think I found the issue. By copy pasting the broken canvas tag into notepad, I discovered a weird character had snuck inside the id. This character does not show up in the codepen editor. I have no idea how it got there. 

![canvas](https://cloud.githubusercontent.com/assets/9215052/15385916/0c811a3a-1da5-11e6-906c-4346c9564fff.PNG)

Could it be caused by different language keyboards? I have been using a Norwegian keyboard and a German keyboard. I think the issue started when I used the German keyboard.

**Comment by tholman** [comment]
Ahh, strange. Its definitely a fragment or corrupt character from the original copy paste, which probably doesn't have an html representation. Feel confident to say its not a keyboard thing though... its weird, but I'd say the editor is behaving correctly here, so going to close.

In the future though, I think this kind of thing would best be debugged by emailing support@codepen.io :)
