### ISSUE TITLE
CSS Position:absolute not working

### ISSUE THREAD

**Issue by billyhalim** [CodePen/CodePen-Bug-Reporting-Only#244]
Hello, 

I want to make a live preview of my code on Codepen. So, I copied all the code from Notepad++ to Codepen excluding the <html>, <body>, and <head> tags. I have set Bootstrap CSS & JS, jQuery. However, I found a bug. The properties of position:absolute such as top, left, bottom, right are not working so I get a different result.

Are there any solution for that ?

Thanks

Billy

**Comment by tholman** [comment]
Hey billy, this sounds more like an issue for support, rather than a bug ... please email support@codepen.io 💃
