### ISSUE TITLE
Anon signup modal busted on small screens

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#245]
From Beverleyh [in the CSS-Tricks Forums](https://css-tricks.com/forums/topic/codepen-obervations-and-experiences-on-mobile/).

The anon signup modal is busted on mobile:

![img](http://fofwebdesign.co.uk/template/_testing/test/images/codepen/IMG_0462.PNG)

She got it when trying to fork a Pen as anon, and completely couldn't use it to either log in or sign up, then lost work because of it.

**Comment by rachsmithcodes** [comment]
hmmm I think we made the decision not to even show this modal on the mobile editor. It must have slipped in.

**Comment by chriscoyier** [comment]
It's not just forking, the modal comes up even just creating a brand new Pen and doing Actions > Save. 

I wonder if it's actually easier to just RWD the thing rather than carve out a saving path that avoids this modal.

**Comment by chriscoyier** [comment]
Just making it sorta responsive for now.

![Uploading Screen Shot 2016-05-24 at 2.21.51 PM.png…]()
