### ISSUE TITLE
Cannot action Actions from within the Twitter app on iPhone 6+

### ISSUE THREAD

**Issue by jonrandahl** [CodePen/CodePen-Bug-Reporting-Only#247]
Right, this is probably not CodePens issue but I'd like to report it nonetheless as I'm sure you'd like to know when your product is compromised!

When I opened a pen from the native iOS Twitter app I tried to leave a heart and fork a pen this morning it was extremely difficult for me to do so as the actions don't show in the portrait view and you can't scroll down to get to them:

![image](https://cloud.githubusercontent.com/assets/39102/15431244/d1070f30-1ea0-11e6-9533-4de52c181854.png)

I found the only way to do anything was to rotate my phone to landscape and even then not all of the actions were visible:

![image](https://cloud.githubusercontent.com/assets/39102/15431245/d111c9b6-1ea0-11e6-8e63-ca924660d06f.png)

If you need anything else please let me know, thanks for a brilliant workplace to test out and garner new ideas!!! 😀

**Comment by chriscoyier** [comment]
Yeah that's totally obnoxious. Happens all the time. Long overdue change: I think we'll move the actions "drawer" up to the top where it's more visually connected to the button anyway.

<img width="432" alt="screen shot 2016-05-24 at 1 40 40 pm" src="https://cloud.githubusercontent.com/assets/69156/15515738/35d90212-21b5-11e6-93bd-c8f8dc3c9772.png">

**Comment by jonrandahl** [comment]
Chris, 
Glad I could give a small return in thanks for all your help over theses years! 
Let me know if you need testing, happy to try things out and report back! 
Jon
