### ISSUE TITLE
SVG animations aren't paused in thumbnails

### ISSUE THREAD

**Issue by Jameskmonger** [CodePen/CodePen-Bug-Reporting-Only#248]
If you look at the thumbnail for this pen (go to Carlos' profile and take a look at the thumbnail), when the animations pause, the SVG eyebrows don't stop being animated.

http://codepen.io/medinnna/pen/vGPZgB

**Comment by chriscoyier** [comment]
So it looks like this Pen is using SMIL. I didn't even know there was a programmatic way to pause SMIL animations, but this very Pen has the code to do so inside it. 

Basically:

```
[].forEach.call(document.querySelectorAll('svg'), function(svg) {
  svg.pauseAnimations();
});
```

The catch? It doesn't seem to work in Chrome or Firefox (that's all I tested so far). With those missing though, combined with the fact that Blink is deprecating SMIL, I don't think I'll put this into our animation-stopping script. We'll just let 'em roll for now ;)
