### ISSUE TITLE
tags page

### ISSUE THREAD

**Issue by yukulele** [CodePen/CodePen-Bug-Reporting-Only#25]
Tags page (http://codepen.io/tags) no more works and redirect to home page

**Comment by chriscoyier** [comment]
I think we used to have a /tags/ page at one point, and all it did was list the 100 most popular tags. Wasn't particularly useful I didn't think. 

Maybe you could help us brainstorm what would be useful on a page like that? 

Tags are a bit under-exposed on CodePen, and I'm not opposed to surfacing them more, I just think we need a good vision for it.
