### ISSUE TITLE
Presentation Mode Access Bug

### ISSUE THREAD

**Issue by bertanyaman** [CodePen/CodePen-Bug-Reporting-Only#252]
Hi guys,

Presentation Mode is a feature for PRO users we all know that.

But if you open that link on  on new tab or new window you can easily access.

1. Simply go to someones profile who has a PRO account.
2. Open one of projects.
3. Change the preview mode to Presentation Mode on new tab or new window.

I just wanted to let you know if you don't.

Thanks :)

**Comment by mariemosley** [comment]
It's a feature :) Presentation mode is enabled on Pens that are owned by PRO members. This makes it easier to present from any computer — for example, you can present your Pens on a shared computer at a meetup without having to log into your own account.

**Comment by chriscoyier** [comment]
It's even slightly more complicated! If YOU'RE PRO, you can open anyone else's Pen in Presentation Mode too. You only can't use it when a non-PRO user opens non-PRO-owned Pen. In which case, redirection and modal happens:

![screen shot 2016-05-24 at 9 32 50 am](https://cloud.githubusercontent.com/assets/69156/15507791/9d483468-2192-11e6-9300-8c47c4d96f05.png)

**Comment by bertanyaman** [comment]
http://codepen.io/MAW/pen/RaXRdE

I see but there is a problem with flow order. If you left-click presentation mode you see modal popup as chris mentioned. But when you right-click and open in new tab you will access the presentation view.

If that's okay, allright then :)

Thanks

**Comment by chriscoyier** [comment]
That Pen is owned by a PRO user.
