### ISSUE TITLE
jQuery no longer working on my codepen

### ISSUE THREAD

**Issue by kimberlythegeek** [CodePen/CodePen-Bug-Reporting-Only#253]
I finished a codepen recently, and everything was working fine. I checked it today and the jQuery is no longer working, even though I haven't changed anything. I copied all of the files to my local server and it works fine, suggesting it's a codepen issue.

The external script I'm using is a text rotator. There is also jQuery that I have written, and none of it is working. I double-checked the source links and even tried using google's hosted library for jQuery.

My external sources are:
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>`
`<script src="http://www.thepetedesign.com/demos/jquery.simple-text-rotator.js"></script>`

link to pen
https://codepen.io/kimberlythegeek/pen/GZbamE

when the scripts are working properly, the header displays "Quotes for" with text rotating between "Atheists" "Skeptics", etc., and the body displays a random quote instead of the text "Generate a Quote"

**Comment by chriscoyier** [comment]
Make sure you're loading jQuery first (drag and drop it to be loading first in Settings). Looks like in that Pen it's second.

**Comment by kimberlythegeek** [comment]
Hm. I moved it, but it's still not working.

**Comment by quezo** [comment]
@kimberlythegeek The problem is you're loading the Pen over https which is possible but all assets you link to must also be loaded over https. If you visit the http URL of the Pen it works. 
http://codepen.io/kimberlythegeek/pen/GZbamE

If you could load this link over https you could view the Pen over https.
```http://www.thepetedesign.com/demos/jquery.simple-text-rotator.js```

We should warn you when this is the case.

**Comment by kimberlythegeek** [comment]
@chriscoyier @quezo 

Thanks, it may have been a combination of the two!
