### ISSUE TITLE
There are something wrong in the list of forked pens

### ISSUE THREAD

**Issue by Rplus** [CodePen/CodePen-Bug-Reporting-Only#254]
1.  
I sort the list in **DESC** order with [Last Updated] column,
but it render pens from 2015 to 2016 in the page.
The direction of table is wrong.
http://codepen.io/Rplus/pens/forked/?grid_type=list
![image](https://cloud.githubusercontent.com/assets/1808835/15564331/bb7b4e18-2343-11e6-88e8-40007cb5d05b.png)

2.  
I forked a pen, but I can't see it in my ["Forked"](http://codepen.io/Rplus/pens/forked/?grid_type=list) page.
http://codepen.io/Rplus/details/vKBppP/#forks

**Comment by quezo** [comment]
We just released a fix for this error.
