### ISSUE TITLE
Getting scroll bars in the preview area, in IE10 and IE11

### ISSUE THREAD

**Issue by tobireif** [CodePen/CodePen-Bug-Reporting-Only#255]
Normally I don't get scroll bars in the preview area of
https://codepen.io/TobiReif/pen/Kdzaxg ,
but in IE10 and IE11 there are scroll bars.

Works in Edge, so it's Microsoft's fault, but (because they don't update IE) perhaps there's something you can do.

**Comment by chriscoyier** [comment]
Feel free to put in conditional CSS or whatever you need to do in the code itself. I don't think we want to be in the marketing of changing default browser behavior in the preview directly.

**Comment by tobireif** [comment]
Thanks for your reply!

It works in Edge, so Microsoft seems to think that there should be no scrollbars. The wrong behaviour of IE10 and IE11 should get fixed - since MS doesn't seem to do it, it is something that needs to be dealt with on the page side.

It's related to Codepen's iframes, so it wouldn't be wrong to make the iframes work correctly in the latest IEs (== making them work as they do in Edge and all other modern browsers).

I googled a bit, others see the ~same issue:
https://www.google.de/search?q=iframe+scrollbars+in+ie

If the solution is to add scrolling related attributes (or apply style properties) to the iframe element, I couldn't implement the fix (or better "IE-bug workaround") from my pen.

**Comment by tobireif** [comment]
(P.S. If you do implement a fix for IE, you'd have to make sure that no content is hidden.)
