### ISSUE TITLE
Dolphin

### ISSUE THREAD

**Issue by tobireif** [CodePen/CodePen-Bug-Reporting-Only#256]
On crossbrowsertesting.com on eg Nexus 5 in eg Dolphin 11.2 the editor areas and the preview area are empty. (eg https://codepen.io/TobiReif/pen/Kdzaxg )

Is it possible to support Dolphin? Incl older versions?

**Comment by chriscoyier** [comment]
Not sure what's up with Nexus 5, but Nexus 9 works. 

![screen shot 2016-05-27 at 9 43 00 am](https://cloud.githubusercontent.com/assets/69156/15611316/71ffd248-23ef-11e6-82cf-63c62b26c7d1.png)

If you can figure out some console message or something that shows what is erroring, it might be possible to fix, but I'm afraid I don't wanna spin my wheels too much on it. It's not even loading the mobile version of the site, which is a simple JavaScript test and cookie setting, so it might just be how Dolphin is set up on CBT.

**Comment by tobireif** [comment]
I understand that supporting old Dolphin versions might not be feasible.

Perhaps you want to display eg the same message that gets shown in older IEs:

https://app.crossbrowsertesting.com/public/ib8393c20a124bac/livetests/5153213/snapshots/z1db4d9c410e7e78df6b
