### ISSUE TITLE
Strange layout in Mobile IE

### ISSUE THREAD

**Issue by tobireif** [CodePen/CodePen-Bug-Reporting-Only#257]
The layout doesn't seem to be right in Mobile IE:

https://app.crossbrowsertesting.com/public/ib8393c20a124bac/livetests/5145896/snapshots/zedaf6c2bc368f31073f

(The pen is https://codepen.io/TobiReif/pen/Kdzaxg .)

**Comment by chriscoyier** [comment]
Probably something with cookies not being allowed in that simulator.

**Comment by tobireif** [comment]
I talked to CrossBrowserTesting, they say that cookies are enabled on that simulator.

I just tested it again, the editor area doesn't seem right (second editor cut off, etc), and the preview area isn't shown as intended:

https://app.crossbrowsertesting.com/public/ib8393c20a124bac/livetests/5207984/snapshots/z0b952e4cefacf8af363

I think the GitHib ticket should be re-opened.

I think the page should look like this instead:

https://app.crossbrowsertesting.com/public/ib8393c20a124bac/livetests/5208014/snapshots/z252d18c2cfc7715eca4

(Or you could eg display the page where you instruct users to use a supported browser.)

**Comment by chriscoyier** [comment]
This is the entire mobile testing code:

```
if (navigator.cookieEnabled && document.documentElement.classList.contains("cookie_used_false")) {

  // set cookie, 3 days
  var date = new Date();
  date.setTime(date.getTime() + (3 * 24 * 60 * 60 * 1000));
  var expires = "; expires=" + date.toGMTString();
  document.cookie = "screen_width=" + screen.width + expires + "; path=/";

  // under 700 is considered mobile
  if (screen.width < 700) {
    window.stop();
    location.reload(true);
  }

}
```

So either 

1) browser doesn't do cookies (I see they say they do)
2) browser doesn't support classList
3) browser doesn't support `screen.width`
4) browser reports `screen.width` incorrectly
5) browser does it all right, but doesn't reload, so next refresh will be OK

If there is some minor alteration to this code that would fix it, I'd do it, but I can't see what that is.

**Comment by tobireif** [comment]
If Codepen can support Mobile IE - great. Otherwise perhaps you want to display the page where the supported browsers are listed.

**Comment by tobireif** [comment]
I often get different results (regarding the page & pen layout), with this and other pens. eg on first load the whole page and pen is borked. I think it would be better if Codepen wouldn't use cookies for detecting/remembering screen width, and instead detect it afresh each time.

screen.width seemed to look sensible in Mobile IE when I tried it.

**Comment by tobireif** [comment]
For two pens I tested this is true:

On first load, the whole layout and pen is kaputt, then after a manual reload, the page layout (incl the editors) and the pen / preview area is fine.

Perhaps this could help:
http://stackoverflow.com/questions/5721704/window-location-reload-with-clear-cache
(several of the replies)
