### ISSUE TITLE
No name shown on Galaxy S6 in Chrome

### ISSUE THREAD

**Issue by tobireif** [CodePen/CodePen-Bug-Reporting-Only#258]
There's no name shown on Galaxy S6 in Chrome:

https://app.crossbrowsertesting.com/public/ib8393c20a124bac/livetests/5145920/snapshots/zcfc82f5c839e1d8c6d7

(The pen: https://codepen.io/TobiReif/pen/Kdzaxg .)

**Comment by chriscoyier** [comment]
On the upper left? We don't show the Pen name/owner up there on the mobile version of the editor.

**Comment by tobireif** [comment]
Then that would be my wish :)
