### ISSUE TITLE
Error using ES6 generator.

### ISSUE THREAD

**Issue by zackharley** [CodePen/CodePen-Bug-Reporting-Only#259]
I'm trying to test out some ES6 functionalities in CodePen and ran into an issue when I tried to use a generator. I put the following code into the editor, using Babel as the JavaScript preprocessor: 
```
function* idMaker() {
  var index = 0;
  while (index < 11)
    yield index += 2;
}

var gen = idMaker();

console.log(gen.next().value);
console.log(gen.next().value);
console.log(gen.next().value);
console.log(gen.next().value);
console.log(gen.next().value);
```

And I get the following error:
```
pen.js:9 Uncaught ReferenceError: regeneratorRuntime is not defined
```

Here is the link to my pen: http://codepen.io/zharley18/pen/ezOBBL

**Comment by chriscoyier** [comment]
This might have some leads for you: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/118

**Comment by zackharley** [comment]
Thanks!

**Comment by senocular** [comment]
This should be inherent in the babel preprocessor configuration
