### ISSUE TITLE
Collections: Multipage collections remove pens - collection is empty ... NOT

### ISSUE THREAD

**Issue by escapedcat** [CodePen/CodePen-Bug-Reporting-Only#26]
- I create a new collection with several pens which creates two pages, 6 pens each
- I go to the second page
- I remove all pens from that collection on that page
- Just keep on removing till the last one is left and keep on removing that one
- It says: 'No Pens exist for this collection. Yet!'

It still has the 6 pens from the first page. Duh! :P

**Comment by tholman** [comment]
Ahh! This is the same problem as #9 ... will close this ticket, and keep using #9 as the point of reference.

Thanks for reporting!

**Comment by escapedcat** [comment]
@tholman ah, nice. I searched the issues but didn't see #9 
thanks!

**Comment by jakealbaugh** [comment]
fixed in the next deploy
