### ISSUE TITLE
ondevicemotion on iPhone

### ISSUE THREAD

**Issue by hansvana** [CodePen/CodePen-Bug-Reporting-Only#260]
Not sure if this is a bug or a feature.

I've made a simple JS ondevicemotion example to show the event to my students. It works great on Android, but not at all on iPhone. No devicemotion or deviceorientation events seem to work from inside CodePen on iPhone (Safari or Chrome). The same code works just fine if served from a different webserver.

[http://codepen.io/hlarken/pen/oLvJwM](http://codepen.io/hlarken/pen/oLvJwM) doesn't work on iPhone
[http://hlarken.acue.webpages.avans.nl/webtech2_1516/ei.html](http://hlarken.acue.webpages.avans.nl/webtech2_1516/ei.html) same code, works on iPhone

**Comment by chriscoyier** [comment]
Best bet, use Debug View so the demo isn't in an iframe and has no other CodePen UI or other interference: http://s.codepen.io/hlarken/debug/oLvJwM
