### ISSUE TITLE
Views/comments icons in the Comments modal are the wrong color

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#262]
![capture](https://cloud.githubusercontent.com/assets/8040471/15616054/568160a2-23f6-11e6-84a1-6858865573f8.PNG)

**Comment by chriscoyier** [comment]
Fun one! We had it fixed, but some updates in our assets compilation stuff and how we were loading that particular asset prevented the new CSS from going out properly. Fixed now.
