### ISSUE TITLE
Created private pen w/o PRO

### ISSUE THREAD

**Issue by vwochnik** [CodePen/CodePen-Bug-Reporting-Only#263]
I believe I have created a private pen without having PRO. I do not want it to be private BTW. Before I had an account, I saved a pen as an anonymous user. Then, using my newly created account, I [forked this anonymously created pen][1]. Unexpectedly, it does not appear in my [profile][2].

[1]: http://codepen.io/vwochnik/pen/dXbMrp
[2]: https://codepen.io/vwochnik/

**Comment by mariemosley** [comment]
I'm sorry you're having trouble finding your Pen! Your forked Pens are in a separate section of your profile at: http://codepen.io/you/pens/forked/
