### ISSUE TITLE
Forked pen not visible

### ISSUE THREAD

**Issue by schoenwaldnils** [CodePen/CodePen-Bug-Reporting-Only#264]
Hi there, 

my pen:
http://codepen.io/schoenwaldnils/pen/wMRgNo
which is public, doesn't appear on my profile, even if I search for it.

![](http://puu.sh/p7T6w/0e14521035.png)

Do you have an idea why this happens?

**Comment by mariemosley** [comment]
This is related to issues with forked Pens described in: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/254 

We're worked to get this fixed!
