### ISSUE TITLE
There is a too wide min-width of `.pen-settings-modal-half`

### ISSUE THREAD

**Issue by Rplus** [CodePen/CodePen-Bug-Reporting-Only#266]
In mobile view(`<400px`), there is a strange black bar in the righe side of details page.

As issue #4 said, we can't open settings dialog in mobile view.
Could we just set a `display: none` style with `@media (max-width: 400px)` on `.pen-settings-modal-half`?

Thanks~

![image](https://cloud.githubusercontent.com/assets/1808835/15705955/ea19e772-2823-11e6-875e-9df907fea3d0.png)

**Comment by chriscoyier** [comment]
Display: none isn't compatible with the opening/closing technique thingy we use, but maybe that would be smart one day. I've fixed this up, which now allows for opening that dialog and changing title/description and stuff on mobile, which I think is a first!
