### ISSUE TITLE
Post editor is really buggy on mobile. 

### ISSUE THREAD

**Issue by allanpope** [CodePen/CodePen-Bug-Reporting-Only#267]
I am currently writing a post on my mobile phone. It's a Nexus 6p, android, using latest version of chrome. I've noticed two bugs with the text Editor.

The very first line you type, the letters stack vertically . When you push enter the word goes to horizontal.

 After using backspace and deleting some text, the cursor acts weirdly. Eg you type and it puts the text behind the cursor or adds weird spacing. Generally bugs out a bit.

**Comment by chriscoyier** [comment]
Tried doing a little testing on Nexus 6p + Chrome and it seems OK: 
https://app.crossbrowsertesting.com/public/i37824dc068c97b3/livetests/5179973/videos/zb405d5342699ba29b1f

(Other than the little weird layout things below I can fix up!)

**Comment by allanpope** [comment]
Thanks for looking at it, weird how it didn't show up in your video. Here's a screenshot of how it appeared OK n mine when you start typing. Maybe its just my phone being weird.

![screenshot_20160602-073648](https://cloud.githubusercontent.com/assets/2561365/15726622/3d56913a-2895-11e6-88d1-95fd752ddca1.png)

**Comment by chriscoyier** [comment]
You have the real phone and I was just using an emulator, so you're probably right, I'm just afraid there isn't much I know how to do.
