### ISSUE TITLE
jade - inadvertent line break before some inline elements

### ISSUE THREAD

**Issue by chharvey** [CodePen/CodePen-Bug-Reporting-Only#268]
CodePen automatically inserts a line break before tag-interpolated `u` elements in the compiled output of Jade source. Normally this wouldn't be a problem because white-space in HTML isn't preserved, **except inside `pre` elements**.

# Input
(using the `u` element to highlight a feature in code)

```jade
p Use the #[code lang] attribute like this:
pre.
  &lt;i #[u lang="fr"]&gt;c'est la vie&lt;/i&gt;
```

### Source
```html
<p>Use the <code>lang</code> attribute like this:</p>
<pre>&lt;i <u>lang="fr"</u>&gt;c'est la vie&lt;/i&gt;</pre>
```
### Rendered
<figure>
<p>Use the <code>lang</code> attribute like this:</p>
<pre>&lt;i <u>lang="fr"</u>&gt;c'est la vie&lt;/i&gt;</pre>
</figure>

### Source
```html
<p>Use the <code>lang</code> attribute like this:</p>
<pre>&lt;i 
  <u>lang="fr"</u>&gt;c'est la vie&lt;/i&gt;</pre>
```
### Rendered
<figure>
<p>Use the <code>lang</code> attribute like this:</p>
<pre>&lt;i 
  <u>lang="fr"</u>&gt;c'est la vie&lt;/i&gt;</pre>
</figure>

# Others
I've tested some other inline elements, and here are the results.

The line break also occurs with these:
- mark
- s
- ins
- dfn
- var
- q
- cite
- data
- time

These elements work as expected (no line break):
- b
- i
- strong
- em
- a
- small
- del
- abbr
- sup
- sub
- code
- kbd
- samp

PS: [Jade is being renamed to “Pug”](https://github.com/pugjs/pug/issues/2184).

**Comment by chriscoyier** [comment]
Pug just went to beta. It was in alpha for quite a while. When it's stable, we plan to switch over. Maybe that'll help here? We just process the code written and return it. There are configurations for processing Jade, but I'm afraid we don't expose them for you to change, and it has too wide of implications for us to change them at the processor level for all Pens using Jade. 

There might be a way to WRITE jade in such a way that it helps with this. There is some trick with a period talked about here: http://stackoverflow.com/questions/8232770/extra-whitespace-in-html-values-rendered-with-jade
