### ISSUE TITLE
NULL value in search window alert

### ISSUE THREAD

**Issue by Mamboleoo** [CodePen/CodePen-Bug-Reporting-Only#269]
I discovered this minor issue (and very specific) while editing a post.

Here are the steps to reproduce the issue : 

1. Open search tool (cmd/ctrl + f)
2. Make a search
3. Reopen the search tool (cmd/ctrl + f)
4. Close the alert window (exit key or cancel button) without doing a research
5. You get a _null_ value in the input

![image](https://cloud.githubusercontent.com/assets/6048794/15819423/5525949a-2be3-11e6-8de4-47f76c20fc3d.png)

I know this issue is ridiculous but I think it can be fixed easily :)

Have a great day !
Mamboleoo

**Comment by chriscoyier** [comment]
Fixing this with some proper search UI
