### ISSUE TITLE
404 pen in my privates pens

### ISSUE THREAD

**Issue by Mamboleoo** [CodePen/CodePen-Bug-Reporting-Only#270]
Hi,

I'm having a 404 pen when I'm checking my private pens.
![image](https://cloud.githubusercontent.com/assets/6048794/15819492/be55d830-2be3-11e6-9ac4-59ed997c0e95.png)

If I try to delete the pen, it always comes back after reloading the page.
It's not really annoying but weird :)

Thanks,
Mamboleoo

**Comment by alexzaworski** [comment]
I'm also having this issue, for what it's worth.

![capture](https://cloud.githubusercontent.com/assets/8040471/15954695/dd9d27fe-2e8e-11e6-91dc-64da83a7a1aa.PNG)

**Comment by mariemosley** [comment]
Thanks for taking the time to report this, we've reproduced it and we're working to fix it. We're moving this issue to our Known Issues trello board: https://trello.com/c/DNOzoHoY/2-undelete-of-private-pens-will-fail-adds-404-pen-to-grid
