### ISSUE TITLE
"double-clicking" team assets creates broken links?

### ISSUE THREAD

**Issue by andyhullinger** [CodePen/CodePen-Bug-Reporting-Only#271]
BUG: in "Team Context" A double-click on an asset rewrites the URI improperly causing broken links.

EXPECTED BEHAVIOR: A "single click" from the team's **t-200** account allows copy/pasting of URI
(`https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-200/ADV-logo.svg`)

BUG: A "double click" inserts the users personal ID **407642** into that URL invalidating the link.
`https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-407642/ADV-logo.svg
`

To replicate: 
1.) Log in as a team member and switch to "team context"
2.) Open "Assets" panel
3.) Single Click into a field to select/copy & paste the proper URL
4.) Any "Double Click" seems to rewrite the text of the field with the _user's_ ID instead of the _team_ ID resulting in a broken link.  (unless by some odd coincidence a team number actually exists that matches an individual? which would possibly make the "t-" prefix a valid link but pointing to a stranger's assets?)

VIDEO HERE: https://www.youtube.com/watch?v=8FqrcfjSaP4

**Comment by chriscoyier** [comment]
good catch! I believe I've found the cause of the bug and I'll be deploying a fix later today.
