### ISSUE TITLE
There aren't any popular posts

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#272]
Is this a bug or are there actually just no posts to display?

![capture](https://cloud.githubusercontent.com/assets/8040471/15982831/be0b0de8-2f47-11e6-82a6-48047a96cf36.PNG)

**Comment by chriscoyier** [comment]
Confirmed broken! We'll take a look and get that back to normal as soon as possible.

**Comment by mariemosley** [comment]
fixed
