### ISSUE TITLE
Off-center warning icon

### ISSUE THREAD

**Issue by acshef** [CodePen/CodePen-Bug-Reporting-Only#28]
Looks like someone left off `text-align:center`:
![image](https://cloud.githubusercontent.com/assets/9013284/11610950/cfe6655e-9b71-11e5-8aa4-a4c714e7a39c.png)
Is this the intended design?

**Comment by chriscoyier** [comment]
That one's my bad. Will fix soon.

**Comment by chriscoyier** [comment]
fixed
