### ISSUE TITLE
imgur images not loading

### ISSUE THREAD

**Issue by brianminsk** [CodePen/CodePen-Bug-Reporting-Only#29]
see this pen for an example: [http://codepen.io/brian_minsk/pen/jWOXKw](http://codepen.io/brian_minsk/pen/jWOXKw)

**Comment by chriscoyier** [comment]
They block us, I'm afraid. A bummer, but nothing we can do about it. Maybe try a proxy? http://blog.codepen.io/2015/07/10/crossorigin-me/

The only hosting we can directly support is (... tap dances and twirls cane ...) our own ;) http://blog.codepen.io/documentation/pro-features/asset-hosting/
