### ISSUE TITLE
tidy button + es7

### ISSUE THREAD

**Issue by yukulele** [CodePen/CodePen-Bug-Reporting-Only#30]
tidy button dont support es7 exponentiation operator (`**`) and add space between `*`s

**Comment by chriscoyier** [comment]
We use this library for this https://github.com/beautify-web/js-beautify

I see we were a little behind on versions, so I'm updating them. 

We use them 100% wholesale, so if you can confirm the bug on their [live site](http://jsbeautifier.org/), [report there](https://github.com/beautify-web/js-beautify/issues). 

Thank you!

**Comment by yukulele** [comment]
thank you
https://github.com/beautify-web/js-beautify/issues/825
