### ISSUE TITLE
Adsense causing embeded pens not to load

### ISSUE THREAD

**Issue by ciar4n** [CodePen/CodePen-Bug-Reporting-Only#31]
Hello

I am having an issue when loading adsense ads with embeded pens. Without the ads the pens load fine. As soon as I enable the ads the pens stop loading and the site hangs trying to load the ad ('Waiting for googleads.g.doubleclick.net'). Without the pens the ads are loading without issue.

Thanks in advance.

Ciarán

**Comment by chriscoyier** [comment]
Can you provide a reduced test case URL for us on this? 

I'll reopen once we can verify the bug.
