### ISSUE TITLE
The HTTPS Plan

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#32]
### The Goal

We'd love to make CodePen an all HTTPS site if we could. The web is **definitely** moving in that direction, for good reason.

### The Problem

**Pens** in general are not HTTPS. Two reasons:

- People are free to link to whatever resources they want. If they link to anything non-secure, there is **mixed-content warnings**. Those can look kinda bad/scary to people. 
- If someone links to a non-secure **JavaScript file** on an HTTPS Pen, the JavaScript **straight up won't run** breaking the Pen.

So any page that shows a Pen, we generally make HTTP (sometimes force, sometimes not). That's **a lot** of CodePen. Homepage, Editor, Search, Profiles, Collab/Professor/Details/Full Page....  so many.

### Current Support

The most important pages already are: login, signup, payment, etc.

We allow you to load most Pages over HTTPS if you want (if stuff breaks, it's on you to fix).

Anywhere we help you add a link to a Pen, it's HTTPS or protocol relative already.

### Current Issues

- Some routes don't work for stuff. Like hearting a Pen, [for example](https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/19).

### Potential Plan

Grandfathering and slow change over.

NEW Pens are forced HTTPS. Anywhere we offer to link something up for you, it's HTTPS (done). If you TRY to add a non-secure link to a Pen (anywhere) we offer a stern warning. Ultimately we can make more and more pages HTTPS only.

OLD Pens we allow to be HTTP. "Old" meaning older than a cut-off date we haven't picked yet.

**Comment by AustinPaquette** [comment]
What about a relay through an SSL connection?

`http://domain.com/script.js`

1. Check for an HTTPS alternative
2. If not found then that file is taken in and cached(?)
3. Injected to the pen as `https://imports.codepen.io/domain.com/script.js`

It has it's potential perks regarding resources that have no intention of moving into SSL but may cause issues regarding cache invalidation.

Just a thought.

**Comment by chriscoyier** [comment]
@AustinPaquette I like it. Clever. It does require an awful lot of grepping through code to get it done though, which makes me a little nervous. e.g. search your external resources, search your HTML for script tags, search your JS for anywhere you request another script. And even with all that probably wouldn't be fool proof. And also feels a little heavy handed if there is no opt-out. Food for thought indeed.

**Comment by AustinPaquette** [comment]
What about if this were a pro feature and what it actually did was add it to the asset manager, the behind-the-scenes stuff will still need a bit of consideration and a lot is definitely going on but if someone puts in an HTTP link, perhaps a modal that - effectively - says pro users can import non-SSL assets for use in their pen. A quick-accept option that adds the asset and creates the import, or they can find an HTTPS served file instead.

**Comment by chriscoyier** [comment]
Idea from @positlabs:

> Some pens use features like `getUserMedia` that require https in order to run. Linking directly to the https pen works fine, but the site defaults to http. Adding an https checkbox to the pen settings would be one possible solution. What do you think?

> http://codepen.io/positlabs/pen/bpLYjY
> https://codepen.io/positlabs/pen/bpLYjY

https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/189

**Comment by mariemosley** [comment]
Moved to our Known Issues trello board: https://trello.com/c/KrXfRthX/9-https
