### ISSUE TITLE
Language autodetect feature

### ISSUE THREAD

**Issue by php5engineer** [CodePen/CodePen-Bug-Reporting-Only#33]
Sometimes I use codepen to refactor snippets I found on the internet. These snippets are almost always written in basic languages - HTML or JS. But I strongly prefer preprocessors. It's one of the reasons I've chosen CodePen. To use those shippets with CodePen I now should go to separate websites like js2.coffee or html2jade.org
Please add a possibility to convert shippets directly on CodePen.

**Comment by chriscoyier** [comment]
Interesting! So these compilers move from the raw language into the preprocessor language. I imagine they do the best they can but have to make guesses at a lot of stuff. 

We can note this down as an idea. I'm closing this thread for now though, as we intend to use this repo as a "bug reporting only" area.
