### ISSUE TITLE
Recover code on tab stuck in infinite loop

### ISSUE THREAD

**Issue by Gregoor** [CodePen/CodePen-Bug-Reporting-Only#34]
So I managed to build an infinite loop (which was of course auto-run). I managed to freeze the script execution via DevTools, but of course I did not save my work. Is there any way to recover the code? Maybe some global JS objects where my code is contained (getting it from the HTML would probably me more work than rewriting).

**Comment by chriscoyier** [comment]
If you've left the page and it didn't save, I'm afraid it's gone :(

If you saved it at least once, autosave may have been kicked on and you probably didn't lose EVERYTHING, but just the last minute or so.

Note that if you manage to SAVE a Pen with an infinite loop, you can turn off JavaScript in the preview with a URL Param: http://blog.codepen.io/documentation/features/turn-off-javascript-in-previews/  

We do try and stop infinite loops ourselves though... so if you manage to get past our detection, let us know, we should note that bug.

**Comment by Gregoor** [comment]
Sadly, I did not save (shame on me >.>).

Rewrite it is then!  Luckily I found the compiled source (I used Babel) in the Dev Tools, so that helps.

Thanks for the quick response!

**Comment by chriscoyier** [comment]
Ahhhhhh that's useful for us to know too - if you can get into DevTools still you can view the network request and dig the returned result out of that. Cool Cool.

**Comment by Gregoor** [comment]
Perfect, the babel version was of course in the request to the
preprocessor. Thanks a lot!

Chris Coyier <notifications@github.com> schrieb am Mi., 9. Dez. 2015 um
16:06 Uhr:
