### ISSUE TITLE
Custom avatar is not working

### ISSUE THREAD

**Issue by vforge** [CodePen/CodePen-Bug-Reporting-Only#36]
After uploading custom avatar to my account it's URL was changed to `https://s3-us-west-2.amazonaws.com/s.cdpn.io/131135/profile/profile-80_1.jpg`, but it's not working - DevTools debugging is showing me following output:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F519AD75959E9880</RequestId>
<HostId>MlzjW0TcBB59AZpnKLOJctPpMhcOkmsT5jqrtNaLgtlZ/q6WWtnODotiv5Qp209Xl5jJvDmNQwY=</HostId>
</Error>
```

**Comment by tholman** [comment]
Hey there!

I'm seeing the avatar here - http://codepen.io/vforge/ ... You still have the problem?

I wonder if it was a slow processing/resizing thing.

**Comment by jakealbaugh** [comment]
hey @vforge so it looks like that url is for the "default" profile image that you were replacing. your new one is `/131135/profile/profile-80_2.jpg` not `/131135/profile/profile-80_1.jpg`. the last integer is the image version and previous versions get removed. did a refresh fix it or did it persist for awhile?

**Comment by jakealbaugh** [comment]
it's still something we need to fix if the url wasnt updated on whatever page you were viewing.

**Comment by vforge** [comment]
@tholman @jakealbaugh I've re-uploaded image and it appeared - but before that I've waited for few (2-3) days.

I'm closing this ticket as it's no longer valid. Cheers for the input :)
