### ISSUE TITLE
Inconsistency bug with tidy button and tab width of indent

### ISSUE THREAD

**Issue by caeldom** [CodePen/CodePen-Bug-Reporting-Only#37]
I'm running Windows 7, Chrome 49.0.2587.3 dev-m (64-bit).

In settings, Behaviour, Code Indentation, if you select Tabs and then adjust the Width of Indent setting, the tidy button does not reflect the change as expected.

When Width of Indent is adjusted to anything greater than the lowest, the tidy button will treat each tab like a single space, ie. when width of tabs are 3 spaces, it will add 3 tabs. This behaviour is inconsistent with what is expected; shift-tab performs the correct behaviour, using just one tab with the right width.

![image](https://cloud.githubusercontent.com/assets/6067646/11758907/381f0628-a0c5-11e5-9702-575b3b5b8774.png)

Expected behaviour (tab width of 3 spaces), occurs when using shift-tab, or auto-indent upon new line.
![image](https://cloud.githubusercontent.com/assets/6067646/11758976/29fc89c0-a0c6-11e5-8917-4d92e99bdc1c.png)

After clicking Tidy button (every tab converted to 3 of those tabs)
![image](https://cloud.githubusercontent.com/assets/6067646/11758981/332de962-a0c6-11e5-8044-edd1b0624afd.png)

**Comment by ge1doot** [comment]
Same here. This is a problem.

**Comment by tholman** [comment]
Let me see what I can do!

**Comment by tholman** [comment]
Fixed!

Deploying now.
