### ISSUE TITLE
CORS issue with hosted assets

### ISSUE THREAD

**Issue by lonekorean** [CodePen/CodePen-Bug-Reporting-Only#38]
Hosted assets are served from amazonaws.com, which can cause some CORS issues when consumed on s.codepen.io. For example, trying to write a pen that loads an image into a canvas and then does stuff on it.

I am putting `image.crossOrigin = 'Anonymous';` in my code. This is the error I get:

> Image from origin 'https://s3-us-west-2.amazonaws.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://s.codepen.io' is therefore not allowed access.

Thanks!

**Comment by chriscoyier** [comment]
One thing to try is proxying through here: http://blog.codepen.io/2015/07/10/crossorigin-me/

Example: http://codepen.io/thebabydino/pen/zGMpqq?editors=001

We do server CORS headers, but it's a weird complicated thing that we have had trouble with for a long time. Here's some of our recent research: https://gist.github.com/tsabat/51fce781c92f8b3bd16f
