### ISSUE TITLE
Codepen broken on 02 mobile networks

### ISSUE THREAD

**Issue by eighthday** [CodePen/CodePen-Bug-Reporting-Only#39]
Some UK mobile networks inline CSS & JavaScript into the head, this can stop the site functioning correctly. An easy fix is to set the http header cache control to no transform

**Comment by chriscoyier** [comment]
It's usually not my favorite kind of fight... the ones where like "third party messes with our site so we have to do weird stuff to fix it on our end" 

But it seems like this would be a fairly easy fix? And 02 is a fairly big provider I think?

**Comment by eighthday** [comment]
yes, 02 is top three in the UK and also supplies its network to smaller operators. 

Looks like codepen is using nginx, so you just need this rule:

     add_header "Cache-Control" "no-transform";

**Comment by chriscoyier** [comment]
This hasn't come up a single time again in a month and a half, so maybe fixed? Feel free to comment again if it's not.
