### ISSUE TITLE
`.pen-settings-modal` is too wide in mobile view

### ISSUE THREAD

**Issue by Rplus** [CodePen/CodePen-Bug-Reporting-Only#4]
It will be scrollable on mobile view. // under full page mode

Maybe add some `media-query` or just remove `min-width` of `.pen-settings-modal` 

![image](https://cloud.githubusercontent.com/assets/1808835/11322301/7f40b5ec-9120-11e5-80d1-1baade4cd49a.png)

**Comment by chriscoyier** [comment]
Thanks! Going to remove that from the page entirely, since you can't open settings at all on Full Page View anyway.

**Comment by Rplus** [comment]
Thanks a lot!
It looks great now!
