### ISSUE TITLE
"PointsMaterial" and "Point" for three.js give "TypeError: THREE.PointsMaterial "(or Point)" is not a constructor"

### ISSUE THREAD

**Issue by SephReed** [CodePen/CodePen-Bug-Reporting-Only#40]
Solution:  Importing "http://threejs.org/build/three.min.js" rather than using the quick import feature solves the problem.

Code pen showing the bug (in console):
http://codepen.io/SephReed/pen/PZZZGB?editors=001

Link to the docs for three.js:
http://threejs.org/docs/#Reference/Materials/PointsMaterial

Details:
The functions "new PointsMaterial()" and "new Point()" both result in a run time error: "TypeError: THREE.PointsMaterial "(or Point)" is not a constructor"

Code copied from source here:  http://threejs.org/examples/#webgl_points_random, with updated href's and src does not work.  The code does work if pasted directly to an html file.

**Comment by Mamboleoo** [comment]
This issue is not related to Codepen.
You are loading an old version of ThreeJs.
PointsMaterial doesn't exist on the version 70, you need to use PointCloudMaterial (or use the latest ThreeJs, which is a better solution ;) )
The method Point() is also wrong, it's Points() with an 's' ! :)

**Comment by mariemosley** [comment]
Thanks @Mamboleoo 😀
