### ISSUE TITLE
No notifications / emails when mentioned in a comment

### ISSUE THREAD

**Issue by Mamboleoo** [CodePen/CodePen-Bug-Reporting-Only#41]
I don't get emails nor a notifications on Codepen when someone mention me in a comment.
The option in my settings is checked (and any other notification works).

I got mentioned multiple time today for example : http://codepen.io/JeromeRenders/details/GopLrG

**Comment by mariemosley** [comment]
Hi @Mamboleoo, we're not able to reproduce this one, so I'm closing it for now. Please feel free to get in touch through support if the problem continues, support@codepen.io
