### ISSUE TITLE
Pen preview freezes browser on Profile

### ISSUE THREAD

**Issue by belohlavek** [CodePen/CodePen-Bug-Reporting-Only#42]
On my profile page http://codepen.io/belohlavek there's an unnamed Pen (the one before the last one) that freezes my browser preventing me from removing it.

Any ideas on how to solve this issue?

**Comment by chriscoyier** [comment]
Try using the JavaScript-turning-offing URL param we have available here: http://blog.codepen.io/documentation/features/turn-off-javascript-in-previews/

**Comment by belohlavek** [comment]
It worked, thanks :+1:
