### ISSUE TITLE
Console shows "incorrect" line number for an error

### ISSUE THREAD

**Issue by yukulele** [CodePen/CodePen-Bug-Reporting-Only#45]
because script is inlined in output code, lines numbers don't corresponding to editor line number.

exemple, my javascript code is:
```
var a;
a.b = 5;
```

their is an error on 2d line but codpen create this output code:

```html
<!DOCTYPE html><html class=''>
<head><meta charset='UTF-8'><meta name="robots" content="noindex"><link rel="canonical" href="http://codepen.io/pen/?editors=001" />


<style class="cp-pen-styles"></style></head><body>

<script src='//assets.codepen.io/assets/common/stopExecutionOnTimeout.js?t=1'></script>
<script>
var a;
a.b = 5;
//# sourceURL=pen.js
</script>
<script src='//codepen.io/assets/editor/live/css_live_reload_init.js'></script>
</body></html>
```

so the console indicated error at line 10, it's hard to debug.

**Comment by chriscoyier** [comment]
I think the `//# sourceURL=pen.js` line is SUPPOSED to help this, but I guess it doesn't?

One possibility is putting your processed JS into an external file and loading that with the template. 

That would probably solve it, but would bet yet-another HTTP request, probably significantly slowing down refreshes. 

We could use some more input here. Would be interesting to see what someone from a DevTools team would say.

**Comment by chriscoyier** [comment]
I think this is working better now. I made a few very small adjustments.

See screencast: http://d.pr/v/1bj2t/5XcuvvVQ
