### ISSUE TITLE
Comment Author Name In New Tab

### ISSUE THREAD

**Issue by jakealbaugh** [CodePen/CodePen-Bug-Reporting-Only#47]
`cmd + click` or center mouse click does not open comment author profiles in a new tab.

[Tweet](https://twitter.com/user/status/681744653759201280) from user @iremlopsum

This is probably due to the double click binding feature that injects the username into the comment box.

A better solution would be to double click the `@handle` to insert the username in a comment, and let the name be a vanilla link.

To do that, the handle will no longer be a child element of the link name and will be its own anchor.

**Comment by chriscoyier** [comment]
I believe @jakealbaugh tag teamed this and fixed it like last week.
