### ISSUE TITLE
iOS Safari & Firefox - scrolling the editor doesn't work from the left side

### ISSUE THREAD

**Issue by mariemosley** [CodePen/CodePen-Bug-Reporting-Only#48]
Scrolling a Pen  from the left side of the screen doesn't work on iOS Safari and iOS Firefox. Works properly in iOS Chrome. 

Scrolling from the right side of the screen works as expected.

**Comment by erwinw** [comment]
I'm the original reporter, @htwj. In trying this some more it seems like dragging does indeed not work on the left half of the screen, but it does work on the right half, irrespective of whether there's text there or not.

**Comment by chriscoyier** [comment]
I'm kinda thinking it might be a feature. Or kinda just how CodeMirror mobile works. Let's do a cursory investigation to make sure there isn't some weird DIV covering half the screen or something, and if not, we might have to just let it be.

**Comment by rachsmithcodes** [comment]
Due to a weird iOS Safari bug an element was blocking the left side of the scroll in the editor.
Should be fixed now! I can scroll on both sides

**Comment by erwinw** [comment]
Beautiful; thanks!
