### ISSUE TITLE
Slim output shouldn't be compressed. 

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#5]
http://codepen.io/team/codepen/pen/7da5cde3b2b47e8b4b30cbe52d5d8b04

All preprocessors should output in the most expanded possible setting.

A support ticket said it well:

>  I'm a newbie and It'd be so much easier to learn and debbug if the output code was nicely indented with newlines like Haml does.

**Comment by tsabat** [comment]
Fixed.
