### ISSUE TITLE
Image not showing when shared on fb

### ISSUE THREAD

**Issue by DjordjePetrovic** [CodePen/CodePen-Bug-Reporting-Only#51]
Hey guys, I want to share my latest pen on fb, and for thumbnail I'm getting blank white img, I pasted url in facebook url debugger and I get https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fcodepen.io%2Fpeky%2Fpen%2FLGyXLR  

fb:app_id hasn't been included in the meta tags. Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog. Otherwise, the default app id( 966242223397117 ) will be assigned. 

Is this known issue or I need to wait some time till the img will be displayed? Thanks!

**Comment by mariemosley** [comment]
The image preview for that Pen is working for me :)
<img width="493" alt="screenshot 2016-01-11 13 52 40" src="https://cloud.githubusercontent.com/assets/456844/12243102/b768671e-b86a-11e5-9b1d-68b83602db6e.png">

Facebook uses the screenshot of your Pen for the image preview. Screenshot generation can be slow sometimes, and that's something we're working to improve. It's likely that you were sharing the Pen before its screenshot was ready. Try it again now :)

I'm closing this issue as it's not quite a bug, but thanks for taking the time to let us know!
