### ISSUE TITLE
Add Vue.js on javascript libraries

### ISSUE THREAD

**Issue by matheuschimelli** [CodePen/CodePen-Bug-Reporting-Only#52]
You can add Vue.js on javascript libraries?

**Comment by chriscoyier** [comment]
Just start typing...

<img width="481" alt="screen shot 2016-01-09 at 5 50 59 pm" src="https://cloud.githubusercontent.com/assets/69156/12218851/92f0e568-b6f9-11e5-9255-b5a946cb57ea.png">
