### ISSUE TITLE
Followers & Following is broken

### ISSUE THREAD

**Issue by TimPietrusky** [CodePen/CodePen-Bug-Reporting-Only#53]
# Follower

The follower count is correct, but when I click on my follower, I get the message: `You don't have any followers yet.`

## Example

http://codepen.io/TimPietrusky/

---

# Following
It looks like no one is following anyone anymore. I just tried to follow "Gregor Adams" (and I followed him before) and now the following count is up to 1 (from 0). 

## Example 

http://codepen.io/TimPietrusky/

**Comment by nikazawila** [comment]
+1
same here!

**Comment by mariemosley** [comment]
Sorry about that! We're working to fix this today

**Comment by mariemosley** [comment]
Fixed! ⚡️ Thanks for reporting it!

**Comment by TimPietrusky** [comment]
Thanks for fixing it :heart:
