### ISSUE TITLE
Notifications show one incorrect timestamp

### ISSUE THREAD

**Issue by Imagine-Programming** [CodePen/CodePen-Bug-Reporting-Only#54]
Today i noticed a funky issue on CodePen, the timestamp next to notifications was the same for each and every notification. The first time it looked it said 11 months ago for every notification. It now states 1 month ago. 

![notifications-issue](https://cloud.githubusercontent.com/assets/489573/12229454/2bca3826-b848-11e5-9e4e-7e0d2bbda7f7.png)

![notifications-issue-2](https://cloud.githubusercontent.com/assets/489573/12229501/c07a2cc4-b848-11e5-8231-03861d4946be.png)

**Comment by mariemosley** [comment]
This is related to https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/53, which we're working to fix today. I'm closing this issue as a duplicate, but thanks very much for letting us know!
