### ISSUE TITLE
Arrow keys on mobile keyboards

### ISSUE THREAD

**Issue by ramtob** [CodePen/CodePen-Bug-Reporting-Only#55]
Hello. I happen to code quite a bit on my mobile phone. And one feature that is useful in that regard, are mobile keyboards that support arrow keys (up, down, right, left).

But as of now, the arrow keys generally do NOT work on the Codepen editor panels, in most mobile browsers. I checked it on the following:

Android
----------
Browsers: Android native, Chrome, Firefox
Keyboards: Smart Keyboard, Ai.type Keyboard

iOs
----------
Browsers: Safari, Chrome
Keyboard: Ai.type Keyboard

To avoid tediousness, I will avoid specifying all the ways in which the arrow keys malfunctioned. The net result was that the ONLY mobile browser in which the arrow keys worked well on the Codepen editor panels, was the (relatively backward) Android native browser.

Can this situation be improved?

TIA

**Comment by mariemosley** [comment]
I'm going to move this into our internal feature request tracker as it's more of a feature request than a bug report. Thanks for taking the time to write this up, we'll see what we can do! 😀

**Comment by chriscoyier** [comment]
Also, the best bet here is to get it working in CodeMirror (open source project) http://codemirror.net/ as that's what our editors use - and we stay up to date on it. =)

**Comment by ramtob** [comment]
Thanks for the replies. I now see that, at least part of the issue seems to have been recently treated in codeMirror (https://github.com/codemirror/CodeMirror/pull/3673). I'll be expecting it on codepen sometime soon then ;)
