### ISSUE TITLE
[Markdown] Javascript code

### ISSUE THREAD

**Issue by Mamboleoo** [CodePen/CodePen-Bug-Reporting-Only#56]
I'm trying to insert a block of code as a comment but I only get a one long line of code.

![image](https://cloud.githubusercontent.com/assets/6048794/12258808/bc2ba4f8-b911-11e5-996c-512bbe25e404.png)

Here is the code I write on my comment :

\```js
/*Define the size of my canvas*/
canvas.width = png.width;
canvas.height = png.height;

/*Draw my image on my scene*/
ctx.drawImage(png, 0, 0); 

/*Get the data of my canvas (See here for more info https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas)*/
var data = ctx.getImageData(0, 0, png.width, png.height);

/*Reset my scene to remove the image*/
ctx.clearRect(0,0,canvas.width, canvas.height);
\```

You can see it live here : http://codepen.io/Mamboleoo/post/how-to-convert-an-image-into-particles

Am I doing something wrong in my code? 
Thanks !
Louis

**Comment by chriscoyier** [comment]
You're not doing anything wrong, it's on us.

I found the bug and wrote the fix, but I need to double check it and run it past people to make sure it doesn't wreck anything else.

**Comment by chriscoyier** [comment]
oops this was fixed quite a while ago. closssssingngngggg.
