### ISSUE TITLE
Text flicker in Safari 9.0.1 OS X 10.10.5

### ISSUE THREAD

**Issue by theruther4d** [CodePen/CodePen-Bug-Reporting-Only#57]
I've noticed flickering in the header that happens a lot when interacting with pens. Attaching a [video](https://s3-us-west-2.amazonaws.com/s.cdpn.io/25381/text-flicker.mp4) of this in action. Adding `-webkit-font-smoothing: antialiased` seems to fix.

**Comment by chriscoyier** [comment]
Someone else mentioned that here and suggested the same fix. https://twitter.com/CodePen/status/686642019771498499

Your video is Safari, yeah?

**Comment by theruther4d** [comment]
Oops sorry to duplicate, yeah it's Safari.

**Comment by chriscoyier** [comment]
Here's my Safari video: http://d.pr/v/1dO88/3yH7elul

Just can't seem to replicate it. I very much don't doubt it though, I've seen that text-thinning thing many-a-time in my day. I'm just hesitant to use fancy (I'd call it hacky) font rendering CSS stuff to fix it when I don't know the other implications of that, and it's not super widespread, and might be a browser bug that gets fixed.
