### ISSUE TITLE
Navigating to home page via browser back button causes animated scroll to "Picked Pens" header

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#58]
Confirmed on Chrome and Firefox. Is this intentional? It definitely feels weird/not on purpose. 

Steps to reproduce:
* Start on home page
* Scroll down
* Go anywhere
* Go back

**Comment by chriscoyier** [comment]
Good catch! I believe I've found the fix and can get out today.
