### ISSUE TITLE
Unable to save pen with large array: SyntaxError: JSON.parse error

### ISSUE THREAD

**Issue by blikblum** [CodePen/CodePen-Bug-Reporting-Only#59]
In pen http://codepen.io/blikblum/pen/mVBvpv i'm trying to do some performance test with a large array (3000 items).

When i try to save the pen i get the following error in console consecutively:
 
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
 everypage-aa58b57fc51a6ac3b496749a8f19ed43.js:3:5309

Eventually, after some time clicking the save button, i can save.

Using Firefox 43.0.4 on windows

**Comment by blikblum** [comment]
Seems that it is only saved by the autosave. Clicking on save does not works

**Comment by chriscoyier** [comment]
I'm afraid CodePen is just gonna be slow and kinda sucky with 15,000 lines of code in the JavaScript editor. 

Better to make than an external asset or host it as an asset on CodePen http://blog.codepen.io/documentation/editor/adding-external-resources/

Should speed up then.
