### ISSUE TITLE
'alert' is stripped entirely from a pen's HTML when displayed in grid view

### ISSUE THREAD

**Issue by nathanielw** [CodePen/CodePen-Bug-Reporting-Only#6]
Any instance of the string `alert` seems to be complete removed from a pen's HTML when the pen is rendered in a preview thumbnail iframe (e.g. on a profile or search results page), potentially causing the preview to rendered completely differently than intended.

I assume this is something to do with ensuring calls to `alert()` don't get triggered when browsing search results/profiles/etc, so I totally understand if it can't be changed (I think most people would rather have broken previews that annoying popups!). The '[Things We Strip](http://blog.codepen.io/documentation/editor/things-we-strip/)' page doesn't seem to mention it, so if it is something that can't be fixed, it'd be cool if it could be mentioned there.

Here's a quick demo of the problem: http://codepen.io/nw/pen/VvNJGe and a page where it appears as a thumbnail: http://codepen.io/search/pens?q=for-a-bug-report&limit=nw

![full-page](https://cloud.githubusercontent.com/assets/4693844/11332149/e88fcfc6-9227-11e5-9019-cdd29d640433.png)
![thumbnails](https://cloud.githubusercontent.com/assets/4693844/11332196/62b39026-9228-11e5-9857-6371f753e4a9.png)

(Firefox 43.0b1, Linux, also tested in Chrome 46.0.2490.80)

**Comment by mariemosley** [comment]
Thanks for taking the time to report this. It is intentional, and I'll update the docs to reflect that.
