### ISSUE TITLE
Uncaught TypeError: Cannot read property 'each' of undefined.

### ISSUE THREAD

**Issue by bkbartonDesign** [CodePen/CodePen-Bug-Reporting-Only#60]
On load of page, I receive this error in the Console window of Chrome  47.0.2526.111.
The error persists after saving Pen and refreshing.

![image](https://cloud.githubusercontent.com/assets/3650812/12466262/daf328c4-bf98-11e5-8716-77b1001bf09b.png)

Pen url: http://codepen.io/bkbartonDesign/pen/qbVgRj

**Comment by chriscoyier** [comment]
You're loading backbone as an external resource (Pen Settings > JavaScript) on this Pen. I'm not sure what exactly is causing the error, but it's coming from that.
