### ISSUE TITLE
[minor] forking causes editor window widths to reset

### ISSUE THREAD

**Issue by tomByrer** [CodePen/CodePen-Bug-Reporting-Only#62]
I had the HTML & CSS editor windows widened, forked, then they reset to equidistant widths.
reproducable

**Comment by mariemosley** [comment]
Can you let us know what browser you're using, and your editor layout (top, left, or right)?

**Comment by mariemosley** [comment]
Closing this because we can't reproduce it. But, if you can get back to us with more detail we'll look into it again :)
