### ISSUE TITLE
Embedded images not loading in full-view

### ISSUE THREAD

**Issue by Alhadis** [CodePen/CodePen-Bug-Reporting-Only#63]
I'm not sure if this is intentionally done out of security, but... well, [the images in my pen](http://codepen.io/Alhadis/pen/yevyXj) aren't displaying. They're [hosted publicly](http://imgur.com/a/6M1pr) on Imgur, which displays them fine when opened. Heck, the images seemed to be loading fine when displayed from the editor's preview pane.

When opened in [full](http://codepen.io/Alhadis/full/yevyXj) or [debug](http://codepen.io/Alhadis/debug/yevyXj/) mode, however, I'm treated to a console full of pure `403`:

<img width="1438" alt="403" src="https://cloud.githubusercontent.com/assets/2346707/12510472/34270e8a-c15e-11e5-99e2-0cc1fa6cf1c1.png">

Confused, I then found myself staring at the impossible, [which had to be recorded](https://youtu.be/Bp_OX9Z0m24). I'm at a loss to explain this one, seriously. No caching was active in my browser when I recorded that video.

(I feel like I've witnessed some supernatural phenomenon. Should a developer be consulted, or an exorcist? Please ignore the fact I was listening to a record called *Pulse Demon*).

**Comment by chriscoyier** [comment]
Sad story: Imgur blocks us. 

I'm afraid the only asset hosting we can support is [our own](http://blog.codepen.io/documentation/pro-features/asset-hosting/).

**Comment by Alhadis** [comment]
Why did they block you? You couldn't possibly have been pulling that much traffic from a site [that encourages shitposting](http://imgur.com/memegen).
