### ISSUE TITLE
Followers & Following is broken in profiles

### ISSUE THREAD

**Issue by mallendeo** [CodePen/CodePen-Bug-Reporting-Only#64]
I'm sure that I was following @chriscoyier before, but I visited his profile and found this:

![Chris's profile](http://imgur.com/CSUc3Rv.jpg)

So I checked my *following* list:
![Following list](http://imgur.com/iNmgclR.jpg)

Same happens with @tsabat profile.

**Comment by chriscoyier** [comment]
Do you happen to be on a Team? And in the Team context? 

If not, let us know your CodePen username

**Comment by mallendeo** [comment]
I've never been on a team.

My username is [mallendeo](codepen.io/mallendeo/).

**Comment by mallendeo** [comment]
It seems that it's solved now :)
