### ISSUE TITLE
Missing <!DOCTYPE html> in Editor

### ISSUE THREAD

**Issue by acshef** [CodePen/CodePen-Bug-Reporting-Only#65]
Despite the warning that a `DOCTYPE` is unnecessary, it does not get applied consistently in pens.

With a proper `<!DOCTYPE html>` the text in this pen should be 60px on Chrome, because the user agent stylesheet for the HTML5 doctype does not change the font of a table: http://codepen.io/acshef/pen/jWZBEw/
**But it's not 60px!**

By switching over to debug view: http://s.codepen.io/acshef/debug/jWZBEw
The doctype correctly is applied.

You can also click the button in the pen, which will display the `name` property of the `document.doctype` read-only property. In the editor view, `document.doctype` is undefined :-1:. In the debug view, the `document.doctype` *is* defined :+1:.

**Comment by chriscoyier** [comment]
This is definitely a bug that we just discovered ourselves today! We'll be fixing ASAP.

**Comment by mariemosley** [comment]
Fixed! Thanks for reporting this @acshef
