### ISSUE TITLE
Support CoffeeScript 1.10.0

### ISSUE THREAD

**Issue by CarlRosell** [CodePen/CodePen-Bug-Reporting-Only#67]
Just noticed that codepen did not compile object/array destruction with default values.

```coffeescript
frame = 
  width: 100
  height: 200
  
{ width, height, color = "should compile" } = frame
```
Saw it was a feature of [coffeescript 1.10.0](http://coffeescript.org/#changelog) and it would be great to have this package updated.

_note: Really love codepen and uses it almost every day. Thanks a lot :tada:_

**Comment by chriscoyier** [comment]
We can definitely get this updated. Kinda @tsabat territory who is out today. But I know we need a Stylus update as well, so perhaps we'll do a little update-palooza soon here.

**Comment by chriscoyier** [comment]
We have an interal open issue for this where we're planning to do a massive sweep of upgrades. I would think by Tuesday this'll be done. If we fail, poke us again.

**Comment by CarlRosell** [comment]
That's great! Hope all upgrades goes well :+1:
