### ISSUE TITLE
Infinite Loop detection code is unreachable after return

### ISSUE THREAD

**Issue by Em-Ant** [CodePen/CodePen-Bug-Reporting-Only#68]
My pen http://codepen.io/Em-Ant/pen/jWxVGK sometimes crashes reporting 'fake' infinite loops. 
The error `unreachable code after return statement` is reported on the JS Console (Firefox 43.0.4 on Ubuntu Linux 14.04 x64). Here is a screen-shot of the debugger.

![screenshot - 28012016 - 00 17 10](https://cloud.githubusercontent.com/assets/12955734/12631943/c3138cc8-c554-11e5-8d59-c1431a98c940.png)

I've solved my problem arranging the code in a slightly different way, but if you want I can provide the original problematic code for debugging purpose.

**Comment by chriscoyier** [comment]
The original code would be great!

That `window.CP.exitedLoop()` code you see is indeed CodePen inserting itself into your loop. That's how we stop infinite loops. It occasionally misses some, but overall CodePen is a much happier place with that =). 

In your case it's catching an infinite loop that isn't infinite?

I'm going to close pending more information. I can re-open if it's a replicable bug with a reduced test ase.
