### ISSUE TITLE
Unable to save Pen 

### ISSUE THREAD

**Issue by mmacedoeu** [CodePen/CodePen-Bug-Reporting-Only#69]
Save is irresponsible, console reports every while a Uncaught SyntaxError: Unexpected token u

![image](https://cloud.githubusercontent.com/assets/4959023/12646807/50ce638a-c5b9-11e5-9867-7231151394fb.png)

**Comment by mariemosley** [comment]
Based on the screenshot it looks like there was a blocked resource in your Pen. I checked out the Pen just now and it seems that you've resolved the errors, so I'm going to close this issue. 

If you're still having trouble with saving Pens, please contact us by email at support@codepen.io and we'll look into it for you :)
