### ISSUE TITLE
Names in the activity feed sometimes link to member's own profile instead

### ISSUE THREAD

**Issue by mariemosley** [CodePen/CodePen-Bug-Reporting-Only#7]
Reported on Twitter: https://twitter.com/michaelgearon/status/668715792830189568

Member-provided gif:

![b3dyh2k1hn](https://cloud.githubusercontent.com/assets/456844/11339088/c080632c-91c5-11e5-9b14-52c1aaf81a69.gif)

I was also able to reproduce this. Happens on the home page, profile page, and /activity

**Comment by jakealbaugh** [comment]
team pen links are also broken

**Comment by jakealbaugh** [comment]
fixed these specific concerns. still some related issues, but they will be addressed in activity refactor.
