### ISSUE TITLE
Chat Room chat messages can be submitted without content

### ISSUE THREAD

**Issue by jessekernaghan** [CodePen/CodePen-Bug-Reporting-Only#72]
![screen shot 2016-01-28 at 10 38 01 am](https://cloud.githubusercontent.com/assets/3515573/12653125/4c8b48fa-c5ab-11e5-9142-4a31177b4111.png)

Tested on: Chrome 47.0.2526.111 on Mac OSX
Recreation: press 'send' on chatbox without entering any content

Currently you can submit blank messages to the chatroom. Perhaps a disabled state could be toggled on the button based on user input?

**Comment by chriscoyier** [comment]
fixed! (or it will be in our next deploy)
