### ISSUE TITLE
PostCSS doesn't work in Details/Full Page View

### ISSUE THREAD

**Issue by giuseppeg** [CodePen/CodePen-Bug-Reporting-Only#74]
Example Pen: http://codepen.io/giuseppegurgone/pen/EPLBZP/
The code is not compiled: the links should be `green` on `hover`.

<img width="373" alt="screenshot 2016-01-29 09 17 06" src="https://cloud.githubusercontent.com/assets/711311/12682593/1c736bde-c669-11e5-857e-52e8ea44c8da.png">

#3 might be related.

**Comment by chriscoyier** [comment]
Ah yes, that's exactly what I was thinking... if the preprocessor ERRORS (and is saved that way) then it uses the code raw in Details View. 

Looks like you have it fixed for this Pen. I'll note this issue in that other issue.

**Comment by giuseppeg** [comment]
Ah sweet! Thanks for taking a look Chris.
