### ISSUE TITLE
Duplicate Line Shortcut

### ISSUE THREAD

**Issue by addui** [CodePen/CodePen-Bug-Reporting-Only#75]
I would use CodePen more often if it had a "duplicate line" shortcut like Notepad++ and Brackets. They both use the `CTRL+d` to duplicate the line that the cursor is currently on. Notepad++ keeps the cursor on the current line when you duplicate a line, and Brackets moves the cursor to the same position but on the new line. I prefer the cursor moving to the new line like in brackets.

Please add this duplicate line shortcut

**Comment by chriscoyier** [comment]
Try adding shift.

I'm on a mac and it's Cmd-shift-d. (i also have the Sublime Text Key Bindings on)

![duplicate](https://cloud.githubusercontent.com/assets/69156/12704080/508bdcac-c818-11e5-97c6-8b25e0d15062.gif)

**Comment by addui** [comment]
I noticed that there was key bindings to mimic Sublime Text and VIM after posting this comment. But I definitely like the key bindings of Brackets and Notepad++ the best. Perhaps I should create a new issue requesting those be added.
