### ISSUE TITLE
Pen stuck as anonymous

### ISSUE THREAD

**Issue by saracope** [CodePen/CodePen-Bug-Reporting-Only#76]
I created a Pen in anonymous mode, then saved it and logged in. I noticed when I went to update the details (description, title) of my saved Pen I wasn't getting those options. The Pen seems stuck in anonymous mode. I'm not seeing a save button anymore or getting the settings dialog and it's not showing in my Pens list.

What I see: http://d.pr/i/1eQhk/4VC0g7Ji

What I expected to see: http://d.pr/i/16YzF/28NwPYeM

I got this error after trying to edit my Pen: http://d.pr/i/1bV1V/4re1XJkw

Steps to recreate:
New Pen
Enter some junk
Save Pen
Login
Check settings -> Does not display the Title, Description, Tags window 

My system:
Mac 10.11.1
Chrome 48.0.2564.97 (64-bit)

Priority: low

**Comment by chriscoyier** [comment]
Looks like there is some bad UX stuff happening there that we should make more clear. 

It's kinda working as intended though. Once Pen is saved as anon, it's anon-owned forever. You can't like move it over to an owned-by-you Pen without forking it.

**Comment by saracope** [comment]
Ok, I remember us talking about that before now that you mention it. I guess it's still bothering me. :dart: 

I think that you should be able to start a Pen and then log in to your account and save it if you want. Right now if you start a pen and decide you want to save it, then you have to save before logging in, or you loose the work you've done so far. But then it's forever an anonymous Pen.

Right now the one I was trying to work with is just erroring so I have to create a new Pen anyway.

**Comment by chriscoyier** [comment]
So I think the solution to this is going to be what we're calling "Anon Saving" which is a bunch of new UI that makes clear what's happening when you save as anon and encourges you not to =)
