### ISSUE TITLE
Templates Should Honor Indentation Settings

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#77]
Templates (likely) already have some code in them. So it would be nice if, when a new one is invoked, it honored the settings from the Pen marked as a template. It's Pen-level data, so should be fairly easily doable.

https://twitter.com/user/status/692458771281494018

**Comment by coreymcollins** [comment]
Would absolutely love this!  Was able to get around this by changing my profile settings, but having different settings carrying over for different templates would be boss.

**Comment by quezo** [comment]
Sweet! This is fixed and in production.
