### ISSUE TITLE
Possible to get stuck in Editor tour by escaping out of "Settings" modal

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#78]
On step 8 of the Editor tour (as well as the later step that requires you to close the `Settings` modal), if you press escape rather than clicking `Save & Close` you become totally locked out of the tour and have to either a) exit the tour or b) refresh the page and start over (you can't even click Settings to try continuing the 'right' way).

![q2gf7shudi](https://cloud.githubusercontent.com/assets/8040471/12736184/f07a3214-c902-11e5-9cc5-6066a234c9cd.gif)

**Comment by rachsmithcodes** [comment]
thanks for letting us know! I've updated this so you can't close the settings dialogue with the esc key while the tour is running.
