### ISSUE TITLE
loose mode

### ISSUE THREAD

**Issue by yukulele** [CodePen/CodePen-Bug-Reporting-Only#79]
Babel seem to compile in lose mode on Codepen.io
https://babeljs.algolia.com/docs/advanced/loose/

this not always respect spec

example: http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&playground=true&code=let%20set%20%3D%20new%20Set%28[1%2C2%2C3]%29%3B%0A%0Alet%20arr%20%3D%20[0%2C%20...set]%3B%0A%0Aconsole.log%28arr%29%3B%20%2F%2F%20expected%3A%20[1%2C2%2C3%2C4]

**Comment by chriscoyier** [comment]
Unfortunately we don't allow for custom configurations of how Babel compiles right now. We have it set to be the most future-accepting stuff we can. And sadly it's not exactly our wheelhouse, understanding all this stuff. We get requests all the time to tweak this and that about Babel, and the requests are often at odds.

If you can help us understand this particular issue, and make a case that it's the way it should be changed for 100% of all Pens, we're open to hear that.
