### ISSUE TITLE
Request timed out. Check your babel. Try again or contact support@codepen.io.

### ISSUE THREAD

**Issue by bradjohnwoods** [CodePen/CodePen-Bug-Reporting-Only#82]
Getting the above error whenever trying to run Babel

**Comment by mariemosley** [comment]
Are you still seeing that error? We upgraded Babel on Friday and there were some initial hiccups with the upgrade. If it's still happening for you, please comment with a link to an example Pen, or email us at support@codepen.io. Thanks!

**Comment by bradjohnwoods** [comment]
all good now, thank you
