### ISSUE TITLE
Google Code Subversion Repository asking for authentication.

### ISSUE THREAD

**Issue by Vallevard** [CodePen/CodePen-Bug-Reporting-Only#83]
This happens when I try to search something like "roulette", I think the problem occurs when some pens has external  libraries.

![codepen](https://cloud.githubusercontent.com/assets/7267899/12867328/8ffeec90-ccb8-11e5-84cb-0cd43f4cb8c8.png)

**Comment by chriscoyier** [comment]
yahhhh that's a huge bummer and there is nothing we can do about it sadly. I've worked with browser makers here and there to see if our sandboxed iframes could block those requests, but no dice yet. Believe me, I want it fixed =)
