### ISSUE TITLE
Inconsistent window context between desktop and mobile sites.

### ISSUE THREAD

**Issue by uimanwashere** [CodePen/CodePen-Bug-Reporting-Only#84]
Here is a live example where I use window.scrollTo() to jump the iframe viewport to a desired position: 

http://codepen.io/uimanishere/pen/QyZxbL?editors=0010

It works fine on CodePen desktop, but not in CodePen mobile (both cases using Chrome/WebKit). There the window reference points directly to the main browser viewport. I'll update here if there's anything new.

Yours.

**Comment by chriscoyier** [comment]
I believe the reason for this is a super weird mobile webkit bug where iframes height grows to contain their entire contents. So you can't really "scroll" them. We fake the scrolling by putting the iframe in a parent container which does scroll. It's the lesser of two bad situations, for sure. It always comes up in situations like this where you're trying to force a scroll or measure a scroll, but in the iframe, no scrolling is actually happening. 

Not much we can do until the webkit bug (if they consider it one) is fixed sadly.
