### ISSUE TITLE
Pen already in collection

### ISSUE THREAD

**Issue by chasebank** [CodePen/CodePen-Bug-Reporting-Only#85]
When adding pens to a collection, it's not clear whether or not the pen is already in the collection.

Duplication isn't an issue, but it would be useful if there were some type of indicator, so that you can tell when what you're trying to do - has already been done.

A good solution would be to highlight the collection options in the drop down, for the ones that the pen is already included.

![example](https://s3-us-west-2.amazonaws.com/s.cdpn.io/106403/codepen-collection-dropdown.jpg)

Much less of an issue: The success message reads the same regardless. It should instead read `This pen is already in the '...' collection`. Otherwise it appears you can keep successfully adding a pen to the same collection, possibly duplicating the others. (I know that's not the case...)

**Comment by mariemosley** [comment]
You and I are the same wavelength Chase, I just added this exact same idea to our internal tracker yesterday :) I'm going to close this issue since it's not quite a bug, but this is definitely on our radar for improvement, thanks!
