### ISSUE TITLE
Username fails to display in chat

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#88]
<img width="604" alt="screen shot 2016-02-11 at 9 13 28 am" src="https://cloud.githubusercontent.com/assets/8040471/12983804/cb296cc4-d09f-11e5-9ded-afad540b6d19.png">

Below my comments; inspected source and it looks like it was straight up just missing the text in the anchor.

<img width="510" alt="screen shot 2016-02-11 at 9 14 16 am" src="https://cloud.githubusercontent.com/assets/8040471/12983820/dc79b2a4-d09f-11e5-9397-03a030982e99.png">

**Comment by alexzaworski** [comment]
Update; according to the user:

> I don't... probably because I sign in through GitHub
> and haven't ever edited my profile

**Comment by chriscoyier** [comment]
Yeah it's weird but not a bug. We may start forcing a name somehow in the future.
