### ISSUE TITLE
Expanding the textarea also expands the submit button in chat

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#89]
<img width="958" alt="screen shot 2016-02-11 at 9 52 17 am" src="https://cloud.githubusercontent.com/assets/8040471/12984985/41a33f10-d0a5-11e5-877d-274707e04a1c.png">

**Comment by chriscoyier** [comment]
Little weird, but just flexbox doing it's thing haha. I don't mind it that much for right now as Chat is this isolated thing to ShopTalk. We'll surely give chat a fresh coat of design paint if it grows up as a feature.
