### ISSUE TITLE
Exporting silently fails when using https

### ISSUE THREAD

**Issue by monfera** [CodePen/CodePen-Bug-Reporting-Only#90]
Prefixing the url with https is important if certain services such as mike access are needed. In this case, however, exporting pretends to work but silently fails. In the worst case it can lead to someone thinking that they have a github gist and delete or irrevocably modify the pen in that belief, and later it turns out there's no backup.

**Comment by chriscoyier** [comment]
There is a number of routes on our end that fail on HTTPS. I like the idea of fixing them as they come up like this, as we need to support HTTPS better anyway. We fixed the hearting one recently I think so that is probably a good guide to fixing this one.

**Comment by tsabat** [comment]
fix going live today.
