### ISSUE TITLE
IE8 not including External CSS files

### ISSUE THREAD

**Issue by NeilANand** [CodePen/CodePen-Bug-Reporting-Only#92]
I've attempted to use the Full page & Live views of a pen in IE8 using the "CrossBrowser Testing" service and my own VM but it appears that CSS files & pens that I've added as External CSS are not being included in this view.

**Comment by NeilANand** [comment]
Having had another look at it (without making changes to the pen) it appears that there were similar problems in Chrome, although not in the edit view.

I looked again about ten minutes later and both issues seemed to have resolved themselves. I'm not sure what could have caused it as at the time of noticing the problem in Chrome I opened the pen in Firefox, as I've never viewed it in that browser, to make sure it wasn't a caching issue and it it was the same.

**Comment by chriscoyier** [comment]
A URL would be good! Closing until we can get a reduce test case.

**Comment by NeilANand** [comment]
I'll see if I can recreate a test case & get back to this.
