### ISSUE TITLE
Mobile site design broken on iPhone 5

### ISSUE THREAD

**Issue by charlesr1971** [CodePen/CodePen-Bug-Reporting-Only#93]
I am using the iPhone 5 and your mobile phone site design is broken. The elements are minute with a massive 200px on the right hand side. None of my animations are working either on the iPhone.

**Comment by chriscoyier** [comment]
This is a little broad of a bug report. Can we get a screenshot? OS installed on that phone? What animations? In a particular Pen? URL? I can re-open once a bug is confirmed.

**Comment by charlesr1971** [comment]
![image](https://cloud.githubusercontent.com/assets/827046/13024586/78ba4576-d1ee-11e5-89ac-909d98e2d53a.jpeg)

**Comment by chriscoyier** [comment]
Looks kinda like a flexbox fail. Probably `flex-wrap`. I'll look into it a bit. But I'm afraid CodePen uses flexbox a TON and we might just have to draw the line on mobile browser support at the point where that property is supported.

**Comment by charlesr1971** [comment]
Hi Chris. So, is flexbox like Bootstrap? It looks like the parent container is not contraining the inline-block/float child elements. But it also looks like the viewport meta tag isn't kicking in for mobile format:

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes">

**Comment by charlesr1971** [comment]
&lt;meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes"&gt;

**Comment by charlesr1971** [comment]
Hi Chis

I know this maybe a little cheeky of me, because this is somewhat unrelated to the original issue. 

My main pen in my showcase, is behaving oddly. It works fine to start with, but after about 5 seconds, the animation loses it blue ring. When you click on the eye icon underneath, it works fine in isolation. It also works fine in edit mode. 

Is each showcase item's CSS/HTML sandboxed?

I am not using any JavaScript, by the way. 

Thanks

Charlie

**Comment by charlesr1971** [comment]
A few more details:

http://codepen.io/charles1971/pens/public/

It works on desktop platform but not on ipad/iphone...

**Comment by chriscoyier** [comment]
Fix for this should be going out today.

Before:

![screen shot 2016-02-22 at 11 29 11 am](https://cloud.githubusercontent.com/assets/69156/13225665/c8d299a4-d95b-11e5-9ecd-22f56a615076.png)

After:

![screen shot 2016-02-22 at 11 51 27 am](https://cloud.githubusercontent.com/assets/69156/13225673/d067ff24-d95b-11e5-8c04-fb6cca41f6fc.png)

**Comment by charlesr1971** [comment]
Good job. Thanks Chris...

**Comment by charlesr1971** [comment]
Just to let you know, that the layout is correct now on the iPhone, but:

1) animations don't work, until you click on the eye icon

2) after clicking on the eye icon, the full size version of the pen, does not scale properly. But it does animate correctly!

**Comment by chriscoyier** [comment]
On mobile we serve static images, not iframes, on pages like the homepage, for performance reasons.

If you could elaborate on "does not scale properly" I could look into that.

**Comment by charlesr1971** [comment]
OK. When I click on the eye icon on the iPhone 5. The content scale is about 3 times too large, causing 2/3 of the design to spill off the side of the screen. I will send along a screen shot...

**Comment by charlesr1971** [comment]
![image](https://cloud.githubusercontent.com/assets/827046/13233873/cea5c11a-d9ad-11e5-8b4c-377052ee22ce.jpeg)
