### ISSUE TITLE
CodePen WP shortcode intergration with Wordpress.com sites

### ISSUE THREAD

**Issue by danbauman77** [CodePen/CodePen-Bug-Reporting-Only#96]
Hola. I'm trying to embed a CodePen.io Wordpress shortcode into a Wordpress.com site. I see here that such an embed is possible: http://goo.gl/75eGyn. However, when I embed the shortcode (https://goo.gl/VD82hv), the text publishes rather than the Codepen embed (http://goo.gl/S2xcC9). I understand Codepen.io has a special embed option with Wordpress.com sites (https://goo.gl/Sx4ytR). However, height is kept at 300px. Height manipulation is the main reason I want to use the shortcode option. 

Has shortcode integration with Wordpress.com been discontinued? Is there something I can add to the CSS to allow for shortcode use? I hope you can help me out. Thanks for your time. 
Here is the pen in question I am trying to embed with the shortcode, though I've tried using other people's shortcodes to no avail: http://codepen.io/danbauman77/pen/gPzEQB

**Comment by alexzaworski** [comment]
Hey @danbauman77, it looks like the issue you're having is that your theme (or something else) is converting dumb quotes to typographer's quotes so the shortcode straight up isn't working. 

Eg:

`height=&ldquo;268&ldquo;` vs `height="268"`

`[codepen_embed height="268" theme_id="0" slug_hash="gPzEQB" default_tab="result" user="danbauman77"]See the Pen East Metro Homicide 2015 by Dan Bauman (@danbauman77) on CodePen.[/codepen_embed]`

**Comment by chriscoyier** [comment]
Does that seem to work? That WOULD be a problem.

Just in case though, I figured I'd try it, and it does seem broken:

![img](http://d.pr/i/1jGDl/1dEiFSk0+)

A workaround for right now is to just paste the link to the Pen in the text, as that still works:

https://chriscoyier.wordpress.com/

(The sucky part being no setting height or theme or anything like that)

**Comment by chriscoyier** [comment]
I emailed the WordPress.com team to see what's up.

**Comment by alexzaworski** [comment]
@chriscoyier, seems like it has to be a weird WordPress.com thing, here's that same shortcode on my (self-hosted) site (after fixing all of the quotes again). 
![screen shot 2016-02-19 at 8 32 36 am](https://cloud.githubusercontent.com/assets/8040471/13181745/62f1da3e-d6e3-11e5-9144-8f2d65943e96.png)

**Comment by chriscoyier** [comment]
I was also under the impression that WordPress.com supported the shortcode, but it does not and apparently never did. It does support oEmbed though.

Soooo it's complicated, but I updated our documentation to hopefully make it more clear:

http://blog.codepen.io/documentation/features/wordpress-plugin/

**Comment by danbauman77** [comment]
Darn. Well, thank you to you and your team, Mr. Coyier. I appreciate it a lot. It would be a great feature in any case. 

Again, thanks for the help. 

Dan

> On Feb 22, 2016, at 7:02 AM, Chris Coyier <notifications@github.com> wrote:
> 
> I was also under the impression that WordPress.com supported the shortcode, but it does not and apparently never did. It does support oEmbed though.
> 
> Soooo it's complicated, but I updated our documentation to hopefully make it more clear:
> 
> http://blog.codepen.io/documentation/features/wordpress-plugin/ <http://blog.codepen.io/documentation/features/wordpress-plugin/>
> —
> Reply to this email directly or view it on GitHub <https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/96#issuecomment-187161029>.
> 


_______________________________

Dan Bauman
Data Reporter, The St. Paul Pioneer Press <http://www.twincities.com/thedatamine>
345 Cedar Street
Saint Paul, MN 55101

651-492-8670 (cell)
651-228-5530 (office)
@danbauman77 <https://twitter.com/danbauman77>
