### ISSUE TITLE
data-height on embeds not respected

### ISSUE THREAD

**Issue by rcrooks** [CodePen/CodePen-Bug-Reporting-Only#97]
Something changed in the HTML embed code recently that causes the data-height attribute to be overridden. The problem I'm seeing is that there's an inline style set on the div#output that actually contains the code and results, and the height here appears to be calculated based on the default 300px data-height instead of the actual one.
Example here: http://docs.brightcove.com/en/video-cloud/di-api/getting-started/quick-start-di.html - if you inspect the codepen element, you'll see that the data-height is set to 574, but the height for the #output div is set to 266px.

**Comment by chriscoyier** [comment]
There is definitely something weird going on there @rcrooks. We'll look into it as soon as we can. 

It's not affecting all embeds everywhere ([reduced test case](http://s.codepen.io/chriscoyier/debug/gPyazZ)) so we need to figure out what is happening in that exact instance.

**Comment by rcrooks** [comment]
Thanks for the response. Interesting….I didn’t do anything special — just
adjusted the height in the embed dialog and then copied and pasted the code.
Robert

Robert Crooks Director of Learning Services Brightcove, Inc
On Tue, Feb 16, 2016 at 5:53 PM, Chris Coyier <notifications@github.com> wrote:
There is definitely something weird going on there @rcrooks [https://github.com/rcrooks] . We'll look into it as soon as we can.

It's not affecting all embeds everywhere ( reduced test case [http://s.codepen.io/chriscoyier/debug/gPyazZ] ) so we need to figure out what is happening in that exact instance.

—
Reply to this email directly or view it on GitHub
[https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/97#issuecomment-184908117] .[https://github.com/notifications/beacon/AAl0YUkuPbFRxSZO4Oub5a1YVqz0c0I6ks5pk5_pgaJpZM4HajMV.gif]

**Comment by KimTapia** [comment]
All my embedded pens are busted as well, the height no longer being respected.  Also, I don't know if this is related at all, but my custom theme that worked wonderfully is no longer being respected either.

**Comment by chriscoyier** [comment]
We've tracked this down to a missing `/team/` in the URL for team-owned embeds. We'll be working on a fix very soon. I'm thinking you won't even have to change any code on your side when the fix goes out.

**Comment by rcrooks** [comment]
Thanks, Chris - that’s awesome!

Robert Crooks Director of Learning Services Brightcove, Inc
On Thu, Feb 18, 2016 at 10:24 AM, Chris Coyier <notifications@github.com> wrote:
We've tracked this down to a missing /team/ in the URL for team-owned embeds. We'll be working on a fix very soon. I'm
thinking you won't even have to change any code on your side when the fix goes
out.

—
Reply to this email directly or view it on GitHub
[https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/97#issuecomment-185773241] .[https://github.com/notifications/beacon/AAl0Ye65-nROaxl4v3NapOG8B0wozRYaks5pldm7gaJpZM4HajMV.gif]

**Comment by quezo** [comment]
@rcrooks @KimTapia  We found a solution for this bug. We were doing a not so smart redirect from our server but it's fixed now.

**Comment by KimTapia** [comment]
Thank you everyone!!
