### ISSUE TITLE
Small UI Bug: Error on pen tagging showing at 4, not 5.

### ISSUE THREAD

**Issue by chrisburgin95** [CodePen/CodePen-Bug-Reporting-Only#98]
The "5 only" text turns red once 4 tags have been entered not 5. Kinda took me back at first and I had to count a few times. Am still able to enter 5 tags though.

![screen shot 2016-02-15 at 7 11 25 pm](https://cloud.githubusercontent.com/assets/1278846/13063662/5e52dd3e-d418-11e5-8c17-6ad00700bbea.png)

**Comment by tholman** [comment]
This is intended as more of a warning ... like "You're getting close to 5!" ... rather than a "you're over the limit!"

...

Can see how it was confusing though.
