### ISSUE TITLE
@debug doesn't work in Sass indented syntax, only SCSS

### ISSUE THREAD

**Issue by lukewatts** [CodePen/CodePen-Bug-Reporting-Only#99]
So I know the @debug logging to the console is a really new feature and one I'm delighted you've added. Anyways, it doesn't seem to work with the indented Sass syntax at all.

If I try the following:

```sass
$list: (1, 2, 3, 4, 5)
@debug length($list)
```
Nothing happens in the console.

However, if I go to setting for the pen and change to SCSS and add in the semicolons:
```scss
$list: (1, 2, 3, 4, 5);
@debug length($list);
```
I get:
```bash
Line 2 DEBUG: 5
```
as expected.

Thanks!

**Comment by tholman** [comment]
Heya!

This should be fixed now, tiny bug on our end!

http://codepen.io/tholman/pen/8210dec4de08a82a9e8103ce94e6671e

Thanks for reporting!

:raised_hands:

**Comment by lukewatts** [comment]
Awesome!

_________________________________________________

LUKE WATTS
Web Designer,  Developer and Digital Artist

Galway, Ireland

Tel: 00353 (0) 85 848 2765
Email: luke@luke-watts.com [mailto:luke@luke-watts.com]
Website: http://luke-watts.com [http://luke-watts.com]
_________________________________________________
On 16/02/2016 17:22:18, Tim Holman <notifications@github.com> wrote:
Heya!
This should be fixed now, tiny bug on our end!
http://codepen.io/tholman/pen/8210dec4de08a82a9e8103ce94e6671e [http://codepen.io/tholman/pen/8210dec4de08a82a9e8103ce94e6671e]
Thanks for reporting!
[:raised_hands:]
